### ISSUE TITLE
What is the relation between the event properties and status, config and fault properties?

### ISSUE THREAD

**Issue by e-grigorov** [eclipse/vorto#1006]
Based on the [documentation](https://www.eclipse.org/vorto/documentation/function_block_dsl/), it seems that the event properties are those properties which will be sent as a part of the event. Let's say if there is a event notification about the value change, the event properties can contain:
* the new value
* the old value
* the value change timestamp

It will be designed as:
```
events {
  valueChanged {
    mandatory newValue as double
    mandatory oldValue as double
    mandatory timestamp as long
  }
}
```
The issue is that these event properties are valid only for the event, they are not part of the function block model. The model doesn't have new and old value properties. They are valid only for the event.

Is my understanding correct? If yes, how can I define events for status, config and fault properties? For example, if there is an eventable configuration property, what is the event representation?

**Comment by aedelmann** [comment]
@e-grigorov 
Your assumption is correct.
I would have to explicitely define an event for that property under "events" with the data model. 

For example:

configuration {
   mandatory temperature as float with {"eventable" : true}
}

events {
   TemperatureTooHigh {
        mandatory temperature as float
   }
}

**Comment by e-grigorov** [comment]
@aedelmann 
* What is the connection between the "temperature" configuration property and "TemperatureTooHigh" event? How can I understand that the event is related somehow to the property?
* There is duplicated metadata i.e. the configuration property and the event must share the same metadata. In this simple example that's the type but can be much more. Such duplication is not maintainable.

**Comment by aedelmann** [comment]
They are not connected IMO. In this case. I would suggest to get rid of these meta data eventable on properties Altogetber and leave just events category. This would eliminate the confusion and it would be much cleaner.

**Comment by e-grigorov** [comment]
> They are not connected IMO

We have a configuration property and its event definition. The event is about this configuration property.

>I would suggest to get rid of these meta data eventable on properties Altogetber and leave just events category.

In this case, how to express that the configuration property can send events?

**Comment by aedelmann** [comment]
> In this case, how to express that the configuration property can send events?
You could model this under the events category, couldn't you ?
Example:
```
configuration {  
   mandatory confProp as string
}

events {
  ConfigurationCompleted {
    mandatory confProp as string
}
}
```

**Comment by aedelmann** [comment]
@e-grigorov 
How about, we allow only eventable configuration or status properties to be referenced in events ?
Like: 
```
configuration {  
   mandatory confProp as string with {eventable:true}
   mandatory otherProp as int
}

events {
  ConfigurationCompleted {
    mandatory confProp as string //is valid and refers to the eventable confProp in configuration
    mandatory otherProp as int // would throw a validation error , as prop is not defined as eventable
}
}
```

**Comment by aedelmann** [comment]
Documentation about the vortolang is available here: https://github.com/eclipse/vorto/blob/master/docs/vortolang-1.0.md 
It also gives a better explanation about the different property types. 

Closing issue. If you feel it is not addressed, please re-open.
