### ISSUE TITLE
Hono Code Generator for Python is not working properly

### ISSUE THREAD

**Issue by maximilianschwab** [eclipse/vorto#1014]
When I would like to generate the Hono Python code from an Information Model with Eclipse, the corresponing application code will not be generatet. Nevertheless the Python classes for the Function Blocks and Information Models are generatet. Generating for example Hono Java code works as expected.

I'm using Windows 10, Eclipse DSL Tools Version Oxygen.3a Release (4.7.3a) and Vorto Toolset 0.10.0.M3.

Any help appreciated! Thanks!

**Comment by aedelmann** [comment]
Have u tried generating from the repository directly without using the eclipse toolset ? Does that work ? U need to push your model to the repo first tho.

**Comment by aedelmann** [comment]
Can u give me the info model u are trying to generate python code for ?
