### ISSUE TITLE
Vorto missing in Eclipse perspective and "new project"

### ISSUE THREAD

**Issue by wiresio** [eclipse/vorto#1018]
Just installed Vorto package in latest Eclipse DSL Photon 64bit (Windows 10) and have no Vorto neither in perspective nor "new project". Is that issue known? Tried to install from both marketplace and toolset update site.

**Comment by aedelmann** [comment]
Try a earlier version of eclipse. We didn’t test on very latest. Thx

**Comment by wiresio** [comment]
Ok. Works with Eclipse Oxygen.
