### ISSUE TITLE
Vorto documentation -> 404

### ISSUE THREAD

**Issue by wiresio** [eclipse/vorto#1019]
Not sure whether this is the right place for my request:
Trying to get hands on Vorto, I was looking for information how to import function blocks or information models from files or the Vorto Repository. However all pages seem to be down, only Google has something cached.
So: How to realize an import or find the documentation?
My goal is to find a way how an information model described via Web of Things Thing Description can be imported into Vorto such that code (for e.g. ESP8266) can be generated out of it.

**Comment by aedelmann** [comment]
I Guess you are referring to the Schema.org semantic descriptions referenced by WoT descriptions right ?  
We Are releasing a new milestone of Vorto 0.10.0.M4 next week which provides an importer API with which u can exactly do that. 
Here is the current documentation : https://github.com/eclipse/vorto/blob/development/repository/repository-importer/Readme.md 

There is also a link to a IPSO importer for your reference. If y need support for the impl, lemme know. 

Which documentation results in 404? Can u gimme the link? 

Thanks.

**Comment by wiresio** [comment]
Sounds great - this is what I am looking for!

Thanks for the link to the actual documentation - Google pointed me to some outdated pages.

**Comment by andrew-from-pretoria** [comment]
For those who have reached this page, note that the link above (3 Aug 2018) is now broken

"Here is the current documentation : https://github.com/eclipse/vorto/blob/development/repository/repository-importer/Readme.md"
