### ISSUE TITLE
Unicode support?

### ISSUE THREAD

**Issue by e-grigorov** [eclipse/vorto#1027]
There is a sample like:
```
namespace` com.mycompany.fb
version 1.0.0
displayname "Surprise"
description "Surprise"
functionblock Surprise {
	status {
		mandatory surprise as string "Überraschung"
	}
}
```
All generators dump: "?berraschung" instead of "Überraschung". It seems that there is an issue with the unicode support.

**Comment by aedelmann** [comment]
Thanks. We are Looking Into that.

**Comment by aedelmann** [comment]
Hi @e-grigorov 
Would you be keen on sharing with us your fix for this problem ? I would run through some internal testings and provide it in the next release. What do you think?

**Comment by e-grigorov** [comment]
Our test environment is using Xtext load option:
```
Injector injector = new FunctionblockStandaloneSetup().createInjectorAndDoEMFRegistration();
XtextResourceSet resourceSet = injector.getInstance(XtextResourceSet.class);
resourceSet.addLoadOption(XtextResource.OPTION_ENCODING, "UTF-8");
...
```

**Comment by aedelmann** [comment]
Hi @e-grigorov 
Awesome. Can u Pull Request this fix ?
