### ISSUE TITLE
Issue with model repository in Eclipse

### ISSUE THREAD

**Issue by Philago** [eclipse/vorto#1044]
Hello,

I used to be able to search the vorto model repository from the vorto plug-in in Eclipse (Oxygen 3A), but not anymore. Now I hit the error message that follows:

"Please make sure that the URL to the repository is entered correctly in your Eclipse Settings (Window -> Preferences -> Vorto -> Information Model Repository)"

I did not change the URL I have and the URL seems fine : http://vorto.eclipse.org

Does someone what is happening ?

Thanks !

Philippe

**Comment by aedelmann** [comment]
Hi Philippe, 
the REST API of the Repository has changed and the current Repository Sandbox vorto.eclipse.org has already been upgraded using the new REST - API. The Eclipse Tool set, on the other hand, is not changed to it. In fact, we froze the further development of the eclipse toolset and would encourage you to create models directly from the Vorto Repository.

**Comment by Philago** [comment]
Hello, thank you for your quick answer

So in the vorto repository, as soon as I create models, are they viewable by everyone? Or can I work on them on my side and keep them "private" and then submit them to the community later ?

Thanks

**Comment by aedelmann** [comment]
The models u create in the repository will be in draft mode and visible for all authenticated users. But only you as the model owner is allowed to edit it.  Once you think your model is completed you can release the model which will then be reviewed by us and made visible for everybody including anonymous users.

**Comment by aedelmann** [comment]
Hi @Philago. 
We are working on the feature, that a draft model is by default "private" and only visible by the specific model owner. However this is a rather big change and would not be available so soon, probably towards the end of the year.
In the meantime, as an interim solution, I can offer to provide a docker image of the repository so you can easily set up your own local version of the repository and create models via the web editor. 
Would that help you ? 

Cheers, Alex

**Comment by Philago** [comment]
Hello @aedelmann,

Thank you very much for your message !

The "private" option would be great.

We already went for the docker image (https://hub.docker.com/r/eclipsevorto/vorto-repo/) to keep working. We haven't finished to set it up yet. The docker image is 1 year old, maybe you have a newer docker image ? By the way, is there a way to keep working with the Eclipse module (which we found conveniant) with a docker image ? Maybe with  a docker image of the repository before the update on the interface ?

Thank you

Philippe

**Comment by aedelmann** [comment]
Hi @Philago 
1) Sadly we do not have a newer version yet. We excluded automated docker image creation from our build pipeline coz we were facing problems. I created a separate issue for that: https://github.com/eclipse/vorto/issues/1047
2) The image that you have will most likely work with the "old" Eclipse plugins. You might wanna give that a go. May I ask why u found the Eclipse plugins convenient ?

**Comment by Philago** [comment]
Hello @aedelmann,

thank you for your answers.

We found the Eclipse plugin conveniant because we can work on our models (based on IPSO models or new models we create) on our side if we want to and we can put the Eclipse project on a repository in our version control system, so that several people can work on the models at the same time

Philippe

**Comment by aedelmann** [comment]
Yes. You would need to add models to it first.

**Comment by aedelmann** [comment]
Closing issue, as it seems to be resolved. Please re-open otherwise.
