### ISSUE TITLE
Tenant Management API

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#1089]
**Why Multi Tenancy ?** 
Device manufacturers have the requirement to store their device / Vorto models in their own separate, secure repository workspace, without interfering with other models from other manufacturers. Each manufacturer would like to manage the visibility of their models themselves. In order to accommodate this request, with the multi - tenancy feature,  it is possible to share the same instance of the repository whereby each tenant specific data is stored in an isolated fashion. This avoids spinning up a separate and costly repository instance for each manufacturer.

**What data would be specific for each tenant?**
- Models
- Accounts
- Users/Roles
- Generators

**Confirmations:**
- Tenant Management API, that allows a system/user to create a tenant in the shared Vorto Repository, secured by admin role
- During initial tenant creation, the tenant ID and namespace(s) are passed. It must define the default namespace for this tenant. 
- The Tenant Admin can add additional namespaces afterwords. The Tenant Manager Component must validate these namespaces for any conflicts.
- Namespaces must be unique across all tenants and must be validated during tenant creation
- The tenant is configured with the DB Identity Provider by default (in order to resolve roles for users)
> Identity Provider SPI, that allows to implement different identity providers in the future, e.g. keycloak or Bosch IoT permissions
- Any authenticated user can create a tenant in the repository via a self-serivce. Depending via which oauth provider the user authenticates, the tenant is configured using the same oauth provider.
- After a tenant is created in the repository, a user can use the tenant-specific Repository - REST Endpoints to create, modify, delete and query models (see other issue)
- When a model is created with a namespace, not fullfilling the namespace configuration of the tenant, it leads to a Bad Request Error.

**Comment by erlemantos** [comment]
[/] mkk

**Comment by erlemantos** [comment]
[ ] test

**Comment by erlemantos** [comment]
- [ ] test
- [x] test 2

**Comment by aedelmann** [comment]
See https://github.com/eclipse/vorto/issues/1402
