### ISSUE TITLE
Vorto repository doesn't run the importers in isolation

### ISSUE THREAD

**Issue by e-grigorov** [eclipse/vorto#1101]
The concrete issue is that our importer is using ASM 6.2. The Vorto repository is using ASM 5.0.1. As a result, the importer is flooded with 5.0.1 and doesn't work correctly. It seems that the importers need some kind of isolation.

**Comment by aedelmann** [comment]
Hi @e-grigorov 
I agree. I was thinking of that as well the past weeks. How about following a similar concept as the generator plugins and run each Importer as a service plugin that can be deployed separately ?
That would solve your issue, right ?

**Comment by e-grigorov** [comment]
I have no background about the generators infrastructure and cannot provide a valuable feedback.

**Comment by aedelmann** [comment]
See https://github.com/eclipse/vorto/issues/1111
