### ISSUE TITLE
ModelId.getFileName() has been removed

### ISSUE THREAD

**Issue by e-grigorov** [eclipse/vorto#1108]
It seems that this method has been removed as a part of #973. I would categorize such clean up as a backward incompatible change. Is it by incident or this method is permanently removed?

**Comment by e-grigorov** [comment]
We have a similar use case. Our importer can operate as a stand-alone CLI tool, Maven plug-in etc. All these integrations generate files with the Vorto models. So far, we used this method to build the file names.

Do you have a list with the backward incompatibilities? Do you think that they(some of them) can go though deprecation phase?

**Comment by aedelmann** [comment]
Hi @e-grigorov 
Yes, I agree. We will mark these kind of functionality as deprecated and will then remove it in the future releases. In this particular case of yours, I will add this back and mark it accordingly.

**Comment by e-grigorov** [comment]
> Yes, I agree. We will mark these kind of functionality as deprecated and will then remove it in the future releases. In this particular case of yours, I will add this back and mark it accordingly.

Is it possible to do so for all changes? We just realized that org.eclipse.vorto.repository.api.ModelId has been removed.
