### ISSUE TITLE
Error Page

### ISSUE THREAD

**Issue by Scriptkiddi** [eclipse/vorto#1132]
Add an error page to handle server errors gracefully
> 
<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Wed Nov 07 05:23:08 UTC 2018</div><div>There was an unexpected error (type=Internal Server Error, status=500).</div><div>No value present</div></body></html>

**Comment by kolotu** [comment]
I'm working on this one.
