### ISSUE TITLE
Add Generator Plugin SDK Documentation

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#1145]
Pre-requisite:
Setup Vorto Repository and run as docker container (with generator authentication)
1. "Hello World" Generator Implementation (Implementation, Properties File containing url etc , logo) 
2. Package as micro service (Spring Boot Application + Configuration)
3. Run generator
4. Adding parameter to generator
5. Advanced Topic: How it works together with mapping files
6. Hook into Eclipse Vorto Repository 
6.1. Email with servicekey, endpoint url of generator

**Comment by Scriptkiddi** [comment]
see #410 #411
