### ISSUE TITLE
Add travis ci check to validate all readme links

### ISSUE THREAD

**Issue by Scriptkiddi** [eclipse/vorto#1150]

**Comment by Scriptkiddi** [comment]
this should be more detailed we can add "remark-preset-lint-recommended","remark-preset-lint-markdown-style-guide" to the check and fix the results

**Comment by aedelmann** [comment]
@Scriptkiddi Isn't this already done ?

**Comment by Scriptkiddi** [comment]
not yet there is some checking but i would recommend adding the whole linting tool in there

**Comment by Scriptkiddi** [comment]
this is done as far as the ticket goes pls close
