### ISSUE TITLE
Integration Tests + FW which test the REST v1 API

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#1175]
- Integration Test FW which makes it very easy to implement integration tests for the Repository REST API
- Implementation of Integration Tests using / validating the Test Framework

**Comment by vlvanchin** [comment]
Here are the list of tasks to be carried out to fulfill the following:

> * Integration Test FW which makes it very easy to implement integration tests for the Repository REST API
> * Implementation of Integration Tests using / validating the Test Framework

1. To setup the integration test project in Github
2. To setup an environment for the integration tests to execute
3. To configure Travis CI build to execute the integration tests before the merge to Development branch

**Comment by vlvanchin** [comment]
4. To get CQs for the new libraries used in this regard
