### ISSUE TITLE
Descriptions in DSL for operation signature

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#119]
The DSL should offer a description for the individual operation parameters.

**Comment by erlemantos** [comment]
Would this suffice?

<code>
operations {
		drive(leftWheelSpeed as float "Speed of left wheel", rightWheelSpeed as float "Speed of right wheel") returns boolean
	}
</code>

**Comment by aedelmann** [comment]
I think that would suffice. What would also be good in this context to adjust the formatter so it becomes more readable like:
 `
operations { 
drive(leftWheelSpeed as float "Speed of left wheel", 
rightWheelSpeed as float "Speed of right wheel")

} `

**Comment by OlafWeinmann** [comment]
Sounds good to me!
