### ISSUE TITLE
Pagination doesnt work on last page

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#1203]
Steps to reproduce:
1. Go  to search
2. Go to last page (page shows only one model)
Expected: Pagination shows to go to other models
Actual: Pagination bar is missing

**Comment by vlvanchin** [comment]
Dear @aedelmann 
Just checked this on Eclipse Vorto site, it seems that the pagination is working as expected.

**Comment by aedelmann** [comment]
It seems that it is only broken if a page has only 1 item to display
