### ISSUE TITLE
Unable to delete an stale function block

### ISSUE THREAD

**Issue by vlvanchin** [eclipse/vorto#1205]
Steps to reproduce:
- from the explorer tab, select the  FB (draft status) that you would want to delete
- click on the delete button, provided it is your own model

Actual outcome:
- the repo goes down by not displaying any models in the explorer tab

Expected outcome:
- the selected model (FB) should be deleted and returns to the Explorer tab.

**Comment by aedelmann** [comment]
Vanchin.  U cannot reproduce it based on your steps. I think it is a special case. I would not spend time on this right now.
