### ISSUE TITLE
Replace web cdn references to maven coordinates

### ISSUE THREAD

**Issue by nagavijays** [eclipse/vorto#121]
In Vorto repository, webpages uses direct cdn references, instead replace it with maven coordinates to bundled it together. 
For e.g in server\repo-ui\index.html

`<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.2.0/css/font-awesome.css" rel="stylesheet" type="text/css" />`

can be replaced with 

`<script type="text/javascript" src="webjars/font-awesome/4.2.0/css/font-awesome.min.css"></script>`

by adding respective maven coordinates in pom.xml

```
<dependency>
    <groupId>org.webjars</groupId>
    <artifactId>font-awesome</artifactId>
    <version>4.2.0</version>
</dependency>
```

**Comment by aedelmann** [comment]
Fixed and available for repository and editor.
