### ISSUE TITLE
Database connection timeout Vorto Repository

### ISSUE THREAD

**Issue by nagavijays** [eclipse/vorto#129]
Database connection timeout during inactivity on vorto repository. 
Affected Services:
- Generators & Generators List
- Login
Attached stack trace. 
[timeout_error.txt](https://github.com/eclipse/vorto/files/195125/timeout_error.txt)

**Comment by gavinying** [comment]
I will be working on it.

**Comment by gavinying** [comment]
Done. 
Tested over night.
