### ISSUE TITLE
Spin-up Code Generators (including example generators) on vorto-dev

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#1291]
For easier Integration testing and QA, the generators should also be deployed and registered to vorto-dev

Source Branch: development

**Comment by vlvanchin** [comment]
Dear @aedelmann ,
Both the official generators and the example generators are deployed in Vorto-dev environment in AWS.
Please check and close this issue.

**Comment by aedelmann** [comment]
Hi Vanchin. 
It’s taking it from development branch right ? 
Yes they are deployed.

**Comment by vlvanchin** [comment]
Dear Alex,
Yes, the official generators are taken from development branch.
