### ISSUE TITLE
Pull Requests additional automated checks before merge

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#1327]
In order to be safer , whether a Pull Requests fullfills the necessary Definition of Done requirements, additional checks are performed automatically upon every Vorto Contribution. A committer of the Vorto Project can use Github to see at one glance, whether all checks were successful and the contribution can be merged safely into the main codebase. 

**Current checks are:**
- Travis CI Build (Unit, Integration Tests, Documentation Linkbreak detection)
- License Header / Code Formatting Checks
- Smelly Code via Codacy Plugin
- Eclipse Contributor License Agreement Check

This issue enhances the checks by :
- SonarCloud Code/Test Coverage
- Compliance (Security Vulnerabilities, License Checks)
- Codacy for Code Warnings, etc

The checks follow the github commit status. 
The CLM Scan and AV Result is published to a private S3 bucket and linked from the details link. The S3 Bucket is secured and can only be accessed by the Vorto Team.

**Optional:**
Check of all libs (including transitive) whether an Eclipse CQ has been created.

**Comment by Scriptkiddi** [comment]
Enforce linters for any language you use (even, e.g., HTML/CSS)
Enable autoformatting (to avoid code style discussions)
Enforce complexity scoring in linters (⬅️ biggest win)
No production console access unless for (logged+alerted) emergencies
Make it easy to recreate a production-like state in development (sanitized)
Have one-step-to-reinstall development environments
