### ISSUE TITLE
Change email on vorto.eclipse.org

### ISSUE THREAD

**Issue by Scriptkiddi** [eclipse/vorto#1331]
People can not send emails when they are not subscribed to that list so start using some different email address
> Using vorto-dev
> To post a message to all the list members, send email to vorto-dev@eclipse.org. You must be subscribed to the list before you can post. To access a web archive of this list, visit the vorto-dev Archives or subscribe to this list's RSS feed

**Comment by aedelmann** [comment]
I would suggest to keep this email there but put a remark + link here for the community to subscribe first.

**Comment by vlvanchin** [comment]
Issue raised in Bugzilla, link below:
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=544203
