### ISSUE TITLE
Vorto DSL Eclipse Plugins

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#1348]
This allows developers to install the Vorto DSL Eclipse Plugins into their Eclipse IDE.

**Comment by andrew-from-pretoria** [comment]
The Vorto Eclipse Toolset has been deprecated. 

"The Eclipse Vorto IoT Toolset Plugins are no longer supported. Instead you can simply use the Cloud-based Editors in the Vorto Repository." 

(Ref https://github.com/eclipse/vorto/blob/master/docs/release-notes.md )
