### ISSUE TITLE
New Website Contact Section not working as expected

### ISSUE THREAD

**Issue by vlvanchin** [eclipse/vorto#1356]
How to reproduce: (locally)
- configure the "email" property in the config.toml
- spin up http://localhost:1313/ 
- go to 'contact' section and try to send out a test email. Will realize that there is no way to give the email id of the sender

Expected:
- the sender should be able to provide their email id
- the recipient email id field need to be displayed

Actual:
- the email (textfield) is configured as the  "to" email and displayed, but there is no place holder to have the sender's email
- the "to" email (textfield) need not be displayed, as it should implicitly be sending to the Vorto-dev team.

* Till this is fixed, we need to disable the "Contact" section.

**Comment by vlvanchin** [comment]
Dear Alex,

The contact section to send out emails with the sender's email address to the Vorto Development team is done and deployed to vorto.git  site for the site update.

The site update takes a very long time, as i realized it took 40mins for the site to be updated with the latest changes.

**Comment by aedelmann** [comment]
Working now. Closing issue.
