### ISSUE TITLE
Manage DRAFT models for anonymous users

### ISSUE THREAD

**Issue by erlemantos** [eclipse/vorto#1369]
How to reproduce:

Don't log in. Click on a model.

Expected: No workflow action for non-logged in users
Actual: Workflow action appears. Workflow Action dialog also appears but is non-functional

**Comment by aedelmann** [comment]
Hi @erlemantos 
I caannot reproduce this: 
If i click on a model as you stated. like http://vorto-dev.eu-central-1.elasticbeanstalk.com/#/details/com.bosch.iot.suite:OctopusSuiteEdition:1.0.0
It does not have any workflow actions.

**Comment by erlemantos** [comment]
@aedelmann 

Try opening a model in Draft state ...

**Comment by aedelmann** [comment]
@erlemantos 
What do you suggest to deal with DRAFT models as anonymous users? 
I think, this could be caused by users deleting their account with Vorto making all their models (including DRAFTS) set to anonymous. Then they would also be visible to everybody.

**Comment by erlemantos** [comment]
Let's refine no. 2 because i'm not very clear about it.

2. Claim Functionality: The claim button appears for logged-in users, when they go to the model detail of a model in a Draft state but whose owner is anonymous. The claim button would then set the new permission (FULL ACCESS) of the model to the claimer (the logged-in user ).

Is that correct?

**Comment by aedelmann** [comment]
Thats right. I would remove the current REST - Claim function and make that completely part of the Workflow , as an action on draft state.
