### ISSUE TITLE
Remove Permission Entry Edit Button

### ISSUE THREAD

**Issue by erlemantos** [eclipse/vorto#1370]
Steps in Reproduction:

Log in. Open a model you own. Go to Permissions tab. Add an entry. Then try editing that entry.

Expectation: Should be able to edit the user-id of the entry
Reality: UserID textbox is readonly

**Comment by aedelmann** [comment]
Hi @erlemantos 
I would say expected is : Edit but is not visible.

**Comment by erlemantos** [comment]
So, if I make a mistake in typing the user-id, I should just delete it and make another one? There is no way to edit the user-id that I typed?

**Comment by aedelmann** [comment]
If you create a new user and this user-id is not existing, it is expected that during the permission creation, an error pops up saying that this user is not existing in the system

**Comment by erlemantos** [comment]
I see. Anyhow, removing the edit button is the simpler fix.

**Comment by erlemantos** [comment]
Tested this again and because we already have the READ/WRITE option, I think there's no need to remove the EDIT button. I'm closing this issue now.
