### ISSUE TITLE
Measurement unit in DSL not working

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#1375]
Steps:
1) Create enum 
2) Create entity referencing enum as measurement unit
Example:
mandatory value as float with {measurementUnit:Unit.Celcius}

Expected: no validation errors
Actual: validation error

**Comment by geglock** [comment]
I got the same errors again; so it seems to be broken (again)?

**Comment by mena-bosch** [comment]
Hi @aedelmann, I've just been notified that this seems to still occur in prod. 

See following fb definition:

> vortolang 1.0
> namespace vorto.private.geglock.test
> version 0.0.1
> displayname "MyFb"
> description "Functionblock for MyFb"
> using org.eclipse.vorto.Unit;1.0.0
> 
> functionblock MyFb {
>    status {
>       value as double with { measurementUnit: Unit.second }
>    }
> }

Can we have a chat tomorrow?

**Comment by aedelmann** [comment]
Measurement unit enums Need to be specified full qualified. Can u try that ?

**Comment by mena-bosch** [comment]
@aedelmann cheers, that worked.

**Comment by mena-bosch** [comment]
Follow-up: is there any task I haven't found / plan to resolve without fully qualified path, or should there be some caveat in the vortolang specs?

**Comment by aedelmann** [comment]
It’s definitely good to mention This caveat in the current Vorto Lang spec. Nonetheless , u can create an improvement issue For making it possible to not specify as full qualified. Shouldn’t be too difficult.
