### ISSUE TITLE
Eclipse/bsinno - development branch is not in sync with Eclipse/vorto - development 

### ISSUE THREAD

**Issue by vlvanchin** [eclipse/vorto#1376]
> Eclipse/bsinno - development branch is not in sync with Eclipse/vorto - development 

> Confirmation
* both the development branchs in Eclipse/vorto and Eclipse/bsinno should have the same number of commits and the commit ids must be same.

> Steps:
* create a separate branch, fixBranch from a common commit 
* to rebase the fixBranch (bsinno) with development (vorto)
* to recommit all the delta commits from development (bsinno) to fixBranch (bsinno)

**Comment by aedelmann** [comment]
@vlvanchin Is this been fixed now ?

**Comment by aedelmann** [comment]
fixed.
