### ISSUE TITLE
Vorto Xtext grammar and Java interfaces are out of sync

### ISSUE THREAD

**Issue by e-grigorov** [eclipse/vorto#1382]
I am looking at model-0.10.0.M11.jar, org.eclipse.vorto.model:
```
public enum ConstraintType
{
  MIN,  MAX,  STRLEN,  REGEX,  MIMETYPE,  SCALING;
  
  private ConstraintType() {}
}
```
and at org.eclipse.vorto.editor.datatype-0.10.0.M11.jar, Datatype.xtext:
```
enum ConstraintIntervalType: min = 'MIN' | max = 'MAX' | strlen = 'STRLEN' | regex = 'REGEX' | mimetype = 'MIMETYPE' | scaling = 'SCALING' | default = 'DEFAULT' | nullable = 'NULLABLE' ; 
```
DEFAULT and NULLABLE are missing in the Java interface. As a result, all models which are using these constraints don't work via REST API.

**Comment by aedelmann** [comment]
Hi @e-grigorov 
thanks for detecting this. We will add this support in the upcoming 0.10 release.
