### ISSUE TITLE
Improve Arduino Generator

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#1395]
Attached you will find a generated and adapted code from this simple Infomodel https://vorto.eclipse.org/#/details/com.bosch.iotacademy.demo:Illuminance:1.0.0 

In it, I have made the following generator relevant changes: all line numbers reference the attached version of the code ;)

1 rearranged configuration order (lines 14 - 46)
2 moved hono_authId definition to configuration (from line 194 to 36)
3 added comment on var name of sample numeric value (lines 48-54 and roughly 237)
4 uppercased fingerprint placeholder (line 25)
5 added more verbose serial output to setup_wifi() and corrected typo in comment (lines 103-115)
6 cleaned up first comment in setup()-function, necessary due to 2 (line 192) 
7 changed telemetry topic to append deviceId instead of clientId, to be more in line with Hono/Hub documentation (line 198-199)
8 corrected typo in publish data header comment (line 96)

Additional Info in Tutorial needed for MAC Users:
The ESP32 Development board's ports will not be recognized by the Arduino IDE 
since there are several drivers that are missing on a Mac. 
1.	Download the drivers through the SiLabs website: https://www.silabs.com/Support%20Documents/Softwar...
2.	Install the drivers onto the computer
3.	Plug in the ESP32 through the micro-usb cable to the computer, and the port will appear on the Arduino IDE under Tools>>Ports.

**Comment by jacewski** [comment]
[IlluminanceApp.zip](https://github.com/eclipse/vorto/files/2879438/IlluminanceApp.zip)
Hi this is where you will find the above mentioned file....
