### ISSUE TITLE
A user can create a new tenant 

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#1402]
**Why Multi Tenancy ?**
Device manufacturers have the requirement to store their device / Vorto models in their own separate, secure repository workspace, without interfering with other models from other manufacturers. Each manufacturer would like to manage the visibility of their models themselves. In order to accommodate this request, with the multi - tenancy feature, it is possible to share the same instance of the repository whereby each tenant specific data is stored in an isolated fashion. This avoids spinning up a separate and costly repository instance for each manufacturer.

What data would be specific for each tenant?

Models
Accounts
Users/Roles
Generators

**Confirmations:**
- Any authenticated user is allowed to create tenants via a Self Service UI once they have logged in via Github. 
- Tenant Management can be done when the sys admin clicks on 'Manage' link
- Lists all tenants currently existing in the system
- When creating a new Tenant, it expects the following input:
a) Unique Tenant Key (e.g. PT-MT) - mandatory
b) Default Namespace prefixed with vorto.private. - mandatory
c) Tenant Administrator UserId  - mandatory (person who manages the tenant, e.g for assigning users to the tenant). An account for this userId must exist, otherwise it would lead to an error "User does not exist in system". This means, the user must have logged in to the system and been auto-provisioned before the system admin can specify the userId.
d) Tenant OAuth Provider - mandatory. Pre-selected is Github ID 
e) Additional Namespaces , prefixed with vorto.private. - optional
- Tenant Key and namespaces and tenant admin userId are validated

Once tenant is created
- the newly created tenant key appears in the list of available tenants for the sys admin (under manage link). The admin can click on the details for the tenant to find out more about its configuration. 
- the system has created a new workspace for the tenant, identifiable by the tenant key (where models, attachments can be stored later for the specific tenant)

**Comment by erlemantos** [comment]
Who are the system administrators? Those with ROLE_ADMIN?

**Comment by aedelmann** [comment]
A System Administrator is a person who has administrative rights to the entire Repository, including managing tenants whereas a Tenant Administrator has admin rights to manage the tenant only.
