### ISSUE TITLE
Vorto tutorial correctness - Connect a Java based device sample

### ISSUE THREAD

**Issue by kiranpradeep** [eclipse/vorto#1415]
1. I am following the Java based device sample [document](https://github.com/eclipse/vorto/blob/master/docs/tutorials/connect_javadevice.md). The documentation appears incorrect in Step 4 at editing AUTH_ID and DITTO TOPIC.
2. I corrected AUTH_ID to [Technical Device ID]@[HONO_TENANT] and DITTO_TOPIC to [namespace]/[Technical Device ID]. Then, the messages are getting published to Bosch IoT Hub. But there is no reflection of values in Vorto console portal under Dashboard tab. The distance is always zero (auto refresh).

**Distance Sensor App Console Log**
> 2019-02-24 19:36:08 INFO  HonoMqttClient:47 - Creating Hub Client for [ssl://mqtt.bosch-iot-hub.com] with Client Id [com.example.kpp018:0001]
> 2019-02-24 19:36:09 INFO  HonoMqttClient:62 - Connecting to Hono.
> 2019-02-24 19:36:11 INFO  HonoMqttClient:76 - Hono Client CONNECTED.
> 2019-02-24 19:36:11 INFO  HonoMqttClient:86 - Sending topic [telemetry/t55fd66b7f91347f9b4b07c85947f7f0e_hub/com.example.kpp018:0001] message [{"path":"/features/distance","headers":{"response-required":false},"topic":"com.example.kpp018/0001/things/twin/commands/modify","value":{"properties":{"configuration":{"applicationType":"","currentCalibration":""},"status":{"minMeasuredValue":94.0,"minRangeValue":60.0,"sensorUnits":"","sensorValue":92.0,"maxMeasuredValue":27.0,"maxRangeValue":5.0}}}}]
> 2019-02-24 19:36:11 INFO  HonoMqttClient:88 - Send done.

**Endpoint Configuration from the portal:**

- DeviceId=com.example.kpp018:0001 
- AuthId=com.example.kpp018:0001@t55fd66b7f91347f9b4b07c85947f7f0e_hub 
- Endpoint=mqtt.bosch-iot-hub.com 
- Topic=telemetry/t55fd66b7f91347f9b4b07c85947f7f0e_hub/com.example.kpp018:0001 
- ClientId=com.example.kpp018:0001

**Comment by vlvanchin** [comment]
Dear Kiran Pradeep,

Thank you for the feedback by trying Vorto. We will update you about this issue soon. 

Regards
Vanchin

**Comment by aedelmann** [comment]
Hi @kiranpradeep 
Please make sure you have booked the asset communication package (beta) once. The demo console is restricted to show only data of a single instance. Can you please verify ?

**Comment by kiranpradeep** [comment]
@aedelmann I am sorry. I am new to Vorto and not sure if I fully understood 
> booked the asset communication package (beta) once

So I went ahead and delete all things in portal (Thing Browser page) except one which my distance sensor app sends data to. How can I verify if I have only booked the asset communication package (beta) once?

.

**Comment by aedelmann** [comment]
@kiranpradeep 
You would need to go to the Bosch IoT Suite Portal Subscription page (https://accounts.bosch-iot-suite.com/subscriptions) which lists all your Bosch IoT Suite Service subscriptions. This has nothing to do with Vorto btw. By right, you should only see one subscription there, namely the Asset Communication Subscription.

**Comment by kiranpradeep** [comment]
@aedelmann Yes. I checked and have only 1 subscription in that page. Attached image.
![vorto](https://user-images.githubusercontent.com/1491933/53310266-2b2a7080-38d2-11e9-95d6-a5e9e6d45ada.png)

**Comment by aedelmann** [comment]
Hi @kiranpradeep 
I cannot reproduce your problem. I get the correct values in the console. 

Can you verify that you have a java client configuration similar to this, see below? 
Btw: Did you set the ditto namespace as default in your things/ditto solution configuration ? 

// Hono MQTT Endpoint
	private static final String MQTT_ENDPOINT = "ssl://mqtt.bosch-iot-hub.com";

	// Your Tenant
	private static final String HONO_TENANT = "t932f4726de374d108498d1e038323232_hub";

	// Your DeviceId
	private static final String DEVICE_ID = "org.mycompany:471100"; //dittonamespace:techDeviceID
	
	// Device authentication ID
	private static final String AUTH_ID = "471100@t932f4726de374d108498d1e038323232_hub";
	
	// Ditto topic , e.g. com.mycompany/4711
	private static final String DITTO_TOPIC = "org.mycompany/471100";

**Comment by kiranpradeep** [comment]
Mine is as below. I cannot see any difference.

```java
	// Hono MQTT Endpoint
	private static final String MQTT_ENDPOINT = "ssl://mqtt.bosch-iot-hub.com";

	// Your Tenant
	private static final String HONO_TENANT = "t55fd66b7f91347f9b4b07c85947f7f0e_hub";

	// Your DeviceId
	private static final String DEVICE_ID = "com.example.kpp018:0001";
	
	// Device authentication ID
	private static final String AUTH_ID = "0001@t55fd66b7f91347f9b4b07c85947f7f0e_hub";
	
	// Ditto topic , e.g. com.mycompany/4711
	private static final String DITTO_TOPIC = "com.example.kpp018/0001";
```

**Comment by aedelmann** [comment]
the namespace you specify during the thing creation must match with the namespace you have set as default namespace in the things solution configuration. There is a link to the configuration page below the namespace input field (during thign creation). Otherwise it wont let you even create the thing properly. In your case, you must set the default namespace to 'com.example.kpp018'

**Comment by kiranpradeep** [comment]
@aedelmann To make sure it was correctly setup, I deleted all things and created a new one. Redownloaded the source code and ran the distnace application after updating properties. That didn't help.

**Comment by aedelmann** [comment]
@kiranpradeep Did you set the default namespace in https://things.eu-1.bosch-iot-suite.com/solution/namespace ?

**Comment by kiranpradeep** [comment]
@aedelmann That appears set.
![namespace](https://user-images.githubusercontent.com/1491933/53312022-5bc1d880-38d9-11e9-8763-9fce3834e3b0.png)

**Comment by aedelmann** [comment]
1) Are you behind a company proxy ? 
2) During thing creation, did you get a successful registration page ?
3) Did you download the server certificate and isntalled it locally for your java client ?

**Comment by kiranpradeep** [comment]
1. No. Home network. All ports open. Or else the MQTT publish (port 8883) would have failed.
2. Yes. I got a successful registration page. The thing is also listed in Thing Browser page.
3. Downloaded the server certificate and copied as hono.crt into resources folder. I skipped that step once and MQTT SSL connection failed then.

**Comment by aedelmann** [comment]
You might wanna try setting a complete new default namespace and re-create a thing with the new namespace.
