### ISSUE TITLE
Automated Upload of Docker images to DockerHub is failing

### ISSUE THREAD

**Issue by vlvanchin** [eclipse/vorto#1416]
The Jenkins server build of Docker images are not getting uploaded to DockerHub.

- Comply with the Eclipse guidelines for dockerhub integration:
https://www.eclipse.org/projects/handbook/#resources-dockerhub
--> All docker images are pushed to eclipse org
- Remove eclipsevorto org and all images

**Comment by Scriptkiddi** [comment]
Can you upload them manually from the Jenkins server?

**Comment by vlvanchin** [comment]
Yes...possible. But need to do the automation.

**Comment by aedelmann** [comment]
@vlvanchin Can you check this ?
