### ISSUE TITLE
Eclipse Hono Generator  for Arduino serialize entity type function creates invalid json

### ISSUE THREAD

**Issue by jacewski** [eclipse/vorto#1421]
In 
https://github.com/eclipse/vorto/blob/c3f246e6db9624e1171b38a93417373ccf28651d/generators/generator-eclipsehono/hono-arduino/src/main/java/org/eclipse/vorto/codegen/hono/arduino/ArduinoEntitySoureTemplate.xtend 

the generated serialize() function adds one too many commas at the end of the status properties
```
        String «dataEntity.name»::serialize() {
            String result = "\"«dataEntity.displayname»\": {";
                «FOR status : dataEntity.properties»
                    result += "\"«status.name»\": " + String(«status.name») + ",";
                «ENDFOR»
                result += "}";
            return result;
```

**Comment by vlvanchin** [comment]
We will check and fix it. Thank you for the feedback.
