### ISSUE TITLE
Fix breaking changes on ESP8266 Core library V 2.5.0 in Arduino Generator

### ISSUE THREAD

**Issue by jacewski** [eclipse/vorto#1422]
Since [version 2.5.0 ESP Core](https://github.com/esp8266/Arduino/releases/tag/2.5.0) uses BearSSL which allows for chain validation of server certificates. The axTLS that is used by the Arduino generator is marked as deprecated. This should also effect all documentation based on this generator. More Info https://github.com/esp8266/Arduino/tree/2.5.0/doc/esp8266wifi#axtls-client-secure---deprecated and https://github.com/esp8266/Arduino/blob/2.5.0/doc/esp8266wifi/bearssl-client-secure-class.rst

**Comment by vlvanchin** [comment]
Hi,

Thank you for the feedback... We will check ans update the generator.

Vanchin

**Comment by aedelmann** [comment]
Closing this issue as it is addressed in https://github.com/eclipse/vorto/issues/1827
