### ISSUE TITLE
Proposal - Ignore Readme files from Codacy check

### ISSUE THREAD

**Issue by timgrossmann** [eclipse/vorto#1431]
Judging from the "issues" on Codacy, it has some trouble with `.md` files. 

Considering that README files are not adding any actual "issues" into the code base, this seems to be odd behavior, especially when trying to fix them in the actual files still resolves in the same error due to parsing trouble (or whatever).

Especially considering the README file as an aesthetic introduction and representation of the project, it should not be restricted by non-modifiable linting rules.

@someshku @aedelmann

**Comment by aedelmann** [comment]
Yeah, agree. We have set this to ignore alrady in codacy.
