### ISSUE TITLE
Building of Docker Images within TravisCI gives Errors

### ISSUE THREAD

**Issue by vlvanchin** [eclipse/vorto#1446]
### Root cause
TravisCI server on building Vorto repository throws the following exception.
```
The command '/bin/sh -c apt-get update && apt-get install -y python3 python3-yaml wget' returned a non-zero code: 100
The command "docker build --build-arg JAR_FILE=./repository/repository-server/target/infomodelrepository.jar -f docker/Repository_Dockerfile -t eclipsevorto/vorto-repo:nightly .;" exited with 100.
```
### Actual outcome
The Pull Request fails 

### Expected outcome
The docker images must be created and pushed to Docker hub as nightly.

**Comment by aedelmann** [comment]
The problem with possible solution is mentioned here: https://stackoverflow.com/questions/55361762/apt-get-update-fails-with-404-in-a-previously-working-build
