### ISSUE TITLE
UX Improvements for Tenant Management

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#1451]

**Comment by somesh-kumar** [comment]
Improvements identified:

1. Change label Tenant Key to Tenant Id (aligns nicely with the naming convention in Hono and Ditto)
2. When a user creates a tenant make the user admin for that tenant
3. When a user intends to delete a button pop-up a dialog box asking to confirm the deletion
4. When a user intends to delete a user linked to a tenant administrated by him show a confirmation dialog

**Comment by somesh-kumar** [comment]
Improvements identified:

1. Change label Tenant Key to Tenant Id (aligns nicely with the naming convention in Hono and Ditto)
2. When a user creates a tenant make the user admin(all roles) for that tenant
3. When a user intends to delete a button pop-up a dialog box asking to confirm the deletion
4. When a user intends to delete a user linked to a tenant administrated by him show a confirmation dialog
5. Improve the add namespace dialog box by pre-appending the textbox with label "vorto.private."
6. Automatically mark the first tenant created by the user as default
7. Don't allow a user to delete himself from the users of a tenant if he is the admin of that tenant
8. Move manage users from a separate tab into a dialog box, trigger the dialog box from a button in the manage tenant screen
9. Upon first login guide a new user on how to get started with the repo
10. Make the labels for attaching roles more meaningful
11. In the dialog box for creating models/data types/function blocks improve the UX by better labelling the single "." being shown before a textbox

**Comment by erlemantos** [comment]
[+] Change label Tenant Key to Tenant Id (aligns nicely with the naming convention in Hono and Ditto)
[+] When a user creates a tenant make the user admin(all roles) for that tenant

**Comment by emantos** [comment]
- Change Cancel to Close in adding users. Change color schemes
