### ISSUE TITLE
Vorto Dashboard - Data Storage and Charts

### ISSUE THREAD

**Issue by timgrossmann** [eclipse/vorto#1466]
#### In order to make the Vorto Dashboard more useful, we need to introduce data persistence and charts that display the information specific values over time.

@jacewski proposed looking at the [iot-suite examples](https://github.com/bsinno/iot-things-examples) for reference. 

In order to keep this project Bosch iot-suite oriented, one possible data storage integration could [IoT Insights](https://www.bosch-iot-suite.com/service/insights/) be.

Displaying historic data for information model specific data will be helpful to discover trends and errors in integrations.

- [ ] Discuss the type of storage type to be used (document based DB / time series DB)
- [ ] Enable solution developers to decide between locally stored data and cloud synced DB access (maybe Bosch IoT-Suite Insights)

**Comment by aedelmann** [comment]
Closing issue as dashboard is not part of this repository. Please re-open on eclipse/vorto-examples
