### ISSUE TITLE
Vorto Dashboard - Vorto Console "Roadblock"

### ISSUE THREAD

**Issue by timgrossmann** [eclipse/vorto#1469]
#### Talking about the chance for the dashboard to be used in trainings, additional effort has to be put into thinking about and describing the approach to create Things from Information Models without the Vorto Developer Console.

This could possibly be done by simply using the Swagger UI.
Considering the user friendliness of trainings, additional thoughts and effort might be invested in making the creation of Things more convenient than working with Swagger. 

- [ ] Create additional documentation on how to create a Thing with the Swagger UI instead of the currently described Vorto Developer Console

**Comment by aedelmann** [comment]
Fixed with new Provisioning Postman script Generator. Do you agree ?

**Comment by timgrossmann** [comment]
@aedelmann Absolutely agree!
