### ISSUE TITLE
Website Hudson/jenkins job failing

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#1494]
The current web site deployment job on Eclipse Jenkins for Vorto is failing. According to logs, it seems to be a permission problem.

**Comment by vlvanchin** [comment]
Opened a Bugzilla ticket for this issue.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=546620

**Comment by aedelmann** [comment]
Fixed by setting the cacheDirectory of Hugo to the $workspace
