### ISSUE TITLE
Usage of AWS Email Service to send Emails

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#1500]
Confirmations:
- Repository is configured with AWS Email Service on DEV/PROD , used to send out emails

**Comment by aedelmann** [comment]
Hi @somesh-kumar 
Can you check what service we can use on AWS for sending out emails? What domain can we configure there for sender information ?

**Comment by somesh-kumar** [comment]
One option could be to use AWS SES SMTP, https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-smtp.html 

Java example: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-using-smtp-java.html

**Comment by aedelmann** [comment]
Configured SES
