### ISSUE TITLE
Vorto to Protobuf Schema

### ISSUE THREAD

**Issue by zubairhamed** [eclipse/vorto#151]
Here's a thought. Protobuf is a framework for serializing data as well embedding the structure of the data.

Wouldn't it be interesting that a vorto model could be used to generate a Protobuf message structure.
Ref: https://en.wikipedia.org/wiki/Protocol_Buffers

Z

**Comment by aedelmann** [comment]
Sounds interesting. You mean the generation would generate a client stub and server skeleton producing/consuming these protobuf messages? 
We could potentially link it to the existing MQTT generator to send protobuf messages as part of the mqtt payload, would that be possible?

**Comment by aedelmann** [comment]
Vorto protobuf and gRPC generator is available on http://vorto.eclipse.org/#/generators
