### ISSUE TITLE
Optional / mandatory use of function blocks in information models

### ISSUE THREAD

**Issue by ankraft** [eclipse/vorto#153]
Hi,

I like to propose the following feature. In some cases, not all function blocks are not necessarily available in an information model. This might be the case when a prototypical device is defined, which may or may have not a implemented a specific function block.
This might look like this:

```
infomodel LightSwitch {
    functionblocks {
        mandatory switch  as Switch
        optional powerConsumption  as PowerConsumption
    }
}
```

Here, the function block _switch_ is mandatory (the default) and the function block for measuring the power consumption _powerConsumption_ is optional.

This would make the storing of general device models from various standards possible, since those device models usually have optional and mandatory function blocks (or equivalents).

Andreas

**Comment by OlafWeinmann** [comment]
Hi Andreas,

I agree! This is an important feature which we'll provide asap!

Cheers,

Olaf

**Comment by aedelmann** [comment]
In this case, I would suggest to define specific information models that really expose the functionality that a device has.

**Comment by ankraft** [comment]
I don't agree. Device models are different from data models. Please reconsider this decision. 

Not supporting optionals would disable the possibility to integrate external data models that have optional attributes (actually most of them support optional elements). One of the goals was to that Vorto can act as a repository for, for example, oneM2M device and service definitions.
This is why we aligned and contributed the work. Optionals are really important to support generic data models. They are also necessary when it comes to inheritance of functionalities.

**Comment by ankraft** [comment]
Thank you very much for re-opening this issue.
Do you think the *optional* keyword can be added as shown in the example above?

**Comment by aedelmann** [comment]
Hi @ankraft 
thanks to @Ebolon, this issue has been fixed. We are rolling out a new milestone release end of this month, containing this fix among others. Please feel free to try it out by downloading the nightly build toolset. 
Thanks.
