### ISSUE TITLE
Repo container was not responding as it was not able to write to default logs

### ISSUE THREAD

**Issue by vlvanchin** [eclipse/vorto#1541]
- problem statement
  - trying to access https://vorto.eclipse.org was not responding gave 502 Gateway Error.
- Expected 
  - should display the models list page
- Actual 
  - was displaying 502 Gateway Error.

**Comment by vlvanchin** [comment]
- findings
  - the repo container was not able to connect for viewing the logs
  - no logs was displaying
  - not able to stop or restart the container
- fix
  - option left to kill this container and restart the service
  - all data is still in tact
  - basic testing

**Comment by aedelmann** [comment]
@vlvanchin Can you change the title of this issue with the problem that you have found out from your analysis ? That way we can fix it. According to the current issue title, prod is not accessible , but you had restarted it so this issue has been fixed.
