### ISSUE TITLE
Multi - Tenancy Bugs / Improvements #1

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#1549]
Bugs:
- Deleting of model not working (Screen freezes)
- Creating of new version of existing model not working (screen freezes)
- Creating a reference from FB to other datatype not working (Throws error: Cannot resolve reference vorto.private.aedelmann:Unit:1.0.0)
- Creating a new model not working

**Comment by aedelmann** [comment]
Hi @erlemantos 
some of the issues have been fixed and I am not able to reproduce them anymore on dev
1. Deleting of models works
2. Creating a new version works
3. Creating new model works

**Comment by erlemantos** [comment]
Hi @aedelmann 

Have you tried testing the "Creating a reference from FB to other datatype not working"? It should also be fixed already.
