### ISSUE TITLE
events are not generated

### ISSUE THREAD

**Issue by alex0002** [eclipse/vorto#1559]
With a functionblock which contains events, those are not generated anywhere.

Based on examples, using

vortolang 1.0
namespace alex
version 1.0.0
displayname "Camera"
category Camera
using alex.Presence; 1.0.0

infomodel Camera {
	functionblocks {
		presence as Presence
	}	
}

and

namespace alex
version 1.0.0
displayname "Presence"
category demo

functionblock Presence {
	status {
		mandatory objectDetected as boolean
		mandatory objectCount as boolean
	}
	events {
		DataChanged {
			xValue as float
			yValue as float
			zValue as float
		}
	}
	operations {
		breakable off()
	}
}

when I generate source I would expect get a datastructure "DataChanged" somewhere. But with any generator I tried nowhere does it appear. It seems that events are completely ignored.

**Comment by aedelmann** [comment]
Hi @alex0002 
Which generator are you referring to ?

**Comment by alex0002** [comment]
Hi,
back from vacation I now have time to test again. Though suddenly all the experimental generators on the webpage have disappeared ..

I tested:
Bosch IoT Suite/Java ---> no DataChanged method/structure anywhere
Bosch IoT Suite/Arduino --> no DataChanged method/structure anywhere
Bosch IoT Suite/Python --> no DataChanged method/structure anywhere
Bosch IoT Suite/Provision Things --> no DataChanged method/structure anywhere --> OK, I didn't expect it here
Bosch IoT Suite/Dashboard --> gives "File Not Found"

Eclipse Ditto --> yes it does generate a DataChanged JSON schema
Eclipse Hono/Java --> no DataChanged method/structure anywhere

Of course the generators should generate a template of how to send events to the backend system. If we must write this code ourselves there is no reason to use the generators at all.

**Comment by aedelmann** [comment]
Hi @alex0002 

1) We no longer support the experimental generators. Is there a specific generator of those, you were particularly interested in ? 
2) The Bosch IoT Suite Generator only supports the generation of code for telemetry data. It does not (yet) support events as well as command and control. This would need to be implemented in future versions of the generator. 
Regarding dashboard, we are fixing the link at the moment, so it will work again by the end of the day. 

I created an issue for the support of events for Bosch IoT Suite Generator: https://github.com/eclipse/vorto/issues/1598

**Comment by kolotu** [comment]
The generation of events in the Bosch IoT Suite Generator is handled with #1598
