### ISSUE TITLE
Update node-mapper version

### ISSUE THREAD

**Issue by somesh-kumar** [eclipse/vorto#1582]
Update the node-mapper npm package version to 0.11.0

**Comment by aedelmann** [comment]
@somesh-kumar 
why this version ? Cant u just define a patch version 0.10.2 ?

**Comment by somesh-kumar** [comment]
Until 0.10.4 has already been used, while figuring out the correct versioning scheme and trying it with travis. I can either do 0.10.5 or move it to beta under 0.11.0, so when we actually release 0.11.0 I can drop the beta. What do you prefer?

**Comment by aedelmann** [comment]
@somesh-kumar . In this case you prepare it for next version 0.11 which we are going to release end of june.
