### ISSUE TITLE
User deletes his account who owns a repository

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#1610]
When a user deletes his account via Settings in the Repository:
- If the user owns at least 1 repository, the deletion is aborted, and a message is prompted, saying that he should either transfer ownership of his repository to another person or remove the repository (under repository management). Transfer of ownership can be achieved by adding another user as tenant administrator and removing himself as an admin.
- If the user does not own any repository, the user account is removed and all his models are anonymized.

**Under Repository Management:**
- Repositories which contain **public** **released** models, can never be deleted, as these models might be used other repositories or external applications.

**Comment by somesh-kumar** [comment]
When a user deletes his account via Settings in the Repository:
**Scenario A "User does not own any repository but is collaborator for other repositories"**
- Anonymization of all models, creator and modifiedBy
- User is removed
- No models will be deleted
- He is removed as collaborator from other repositories, where he is member of

Scenario B "User owns repository by himself without any collaborators, containing only private models"
- Repository is permanently removed (if there are no released models)
- Anonymization of all models, creator and modifiedBy (
- User is removed

Scenario C "User owns repository together with other user"

... to be refined
