### ISSUE TITLE
Vorto demo feedback, UI and other improvements

### ISSUE THREAD

**Issue by somesh-kumar** [eclipse/vorto#1615]
1. Hide/Remove the non-anonymous api's from Swagger
2. In the roles assignment window change the "Administrator" word to upper case
3. Rename "cancel" label to "close" in add collaborators window
4. Verify whether "/api/v1/models/{modelId}/content" returns the full flat json for a model

@aedelmann : Please review and prioritize the issue.

**Comment by alex0780** [comment]
Prioritizes items
1. 
3.
4.
2.

**Comment by timgrossmann** [comment]
@somesh-kumar 
3. will be resolved by https://github.com/eclipse/vorto/issues/1614
