### ISSUE TITLE
Vorto Web Editor: broken tutorial link

### ISSUE THREAD

**Issue by andrew-from-pretoria** [eclipse/vorto#1624]
Link is broken in website. Gives 404 error.

Steps to reproduce:
1. Visit 
https://github.com/eclipse/vorto/tree/33b98c02c4830f15af1d8450974e8d2421f25583/server/devtool/webeditor .

2. At bottom of page, see "You can refer to the tutorial here."

3. Click on link embedded in the text "here" ( https://github.com/eclipse/vorto/blob/development/tutorials/tutorial-create_and_publish_with_web_editor.md ).

Expected:
Tutorial on using Vorto Web Editor.

Actual:
404 error.

**Comment by somesh-kumar** [comment]
Hi @andrew-from-pretoria ,

Vorto web editor has been deprecated. We will update the documentation to mark it deprecated.

You can use the cloud based application https://vorto.eclipse.org/ to create Vorto models. Refer to the getting started guide at https://github.com/eclipse/vorto/tree/master.
