### ISSUE TITLE
Non Vorto file import results in Error

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#1628]
Steps taken:
1. Log in to repository
2. Own a repository with namespace com.ipso.smartobjects
3. Go to Import and choose LwM2M
4. Choose a Lwm2M XML and click 'Upload'
5. Choose Import
Expected: Model was successfully imported into the com.ipso.smartobjects repository
Actual: Error 'Bad Request. Server down'

**Comment by Jeffy4241** [comment]
For information when importing Lwm2M XML after a successful update I add  'Bad Request. Server down' in the following cases : 
- parenthesis in property name 
- TS suffix in property name

**Comment by aedelmann** [comment]
Fixed
