### ISSUE TITLE
Why Property Suffix TS is forbidden

### ISSUE THREAD

**Issue by Jeffy4241** [eclipse/vorto#1630]
I want to declare a property with the name "xxx UMTS" but Vorto throws : 

> org.eclipse.vorto.repository.core.impl.validation.ValidationException: On line number 33 : Invalid property name with suffix "TS"

I just wonder why it explicitly forbidden as coded in /core-bundles/language/org.eclipse.vorto.editor.datatype/src/org/eclipse/vorto/editor/datatype/validation/DatatypeValidator.xtend

**Comment by aedelmann** [comment]
Hi @Jeffy4241 
this is indeed a bug. Will fix along for the next release. Thx.

**Comment by aedelmann** [comment]
Fixed and merged with development
