### ISSUE TITLE
Issues while trying to create repository

### ISSUE THREAD

**Issue by someshku** [eclipse/vorto#1631]
Steps to recreate issue: 
- Navigate to create repository
- Provide a namespace name which already exists
- Click create, you will see an error "Namespace request already exist"
- At this time the namespace changes to vorto.private.xxx
**Expected**: Only the name should be shown in textbox without vorto.private
Change error message to  "Requested namespace already exists"
- Change the name and click create, same error shows up
**Expected**: A new namespace should get created

**Comment by someshku** [comment]
@aedelmann: Please prioritize

**Comment by aedelmann** [comment]
I already fixed this.
