### ISSUE TITLE
Outdated "Getting Started" instructions on Vorto web page.

### ISSUE THREAD

**Issue by andrew-from-pretoria** [eclipse/vorto#1634]
Decsription:
Outdated instructions posted at "Getting Started". (https://github.com/eclipse/vorto/blob/development/docs/gettingstarted.md )

Where:
Scroll down to "Learning Path"

The problem:
The instruction "Describe your first device in 5 minutes using the Vorto Web Editor" is inaccurate since the Vorto Web Editor has been deprecated.

Desired outcome: 
Replace this instruction with a reference to the Cloud-based editing tool.

**Comment by aedelmann** [comment]
Closing as this issue is referring to current dev branch.
