### ISSUE TITLE
DSL grammar written using BNF notation

### ISSUE THREAD

**Issue by andrew-from-pretoria** [eclipse/vorto#1640]
Problem: 
Persons who are starting with Vorto have to understand the DSL grammar. However, the grammar notation is not explained.

Solution: 
Add a comment on the pages that currently describe the language to the effect that a modified version of the Backus–Naur form/Backus normal form (BNF) is applied.

Affected pages:
1. 
https://github.com/eclipse/vorto/blob/development/core-bundles/docs/dsl_grammar_infomodel.md

2. 
https://github.com/eclipse/vorto/blob/development/core-bundles/docs/dsl_grammar_functionblock.md

3.
https://github.com/eclipse/vorto/blob/development/core-bundles/docs/dsl_grammar_datatype.md#datatype-dsl-grammar-reference

**Comment by aedelmann** [comment]
Hi @andrew-from-pretoria 
Your issue should be addresses with the latest vortolang 1.0 specification. Please re-open if not.
