### ISSUE TITLE
Device Provisioning Generator Problem on dateTime type

### ISSUE THREAD

**Issue by timgrossmann** [eclipse/vorto#1656]
##### Upon generation of a Postman device provisioning script using the Bosch IoT Suite generator on the Vorto Repository, the generated script has errors in the body section of the request.

The problem is that values with the data type `dateTime` are not put into quotes. 

```json
"properties": {
  			"status": {
  				"lastChange" : 2019-04-01T18:25:43-00:00,
  				"isTrue" : false
  			}
  		}
```

In order to fix the body, we have to add quotation marks around the `dateTime` type field.

```json
"properties": {
  			"status": {
  				"lastChange" : "2019-04-01T18:25:43-00:00",
  				"isTrue" : false
  			}
  		}
```

**Comment by aedelmann** [comment]
Fixed
