### ISSUE TITLE
Expose REST Endpoint to allow users to import Vorto models 

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#1667]
In order to allow 3rd party toolchains to automate import of Vorto Models into the repository, the Repository must provide a public REST endpoint.

**Confirmations:**
- REST Endpoint for models **upload** (accepts a single file or ZIP of models). It returns a uploadHandle along with a model validation report
- REST Endpoint for models **import** (accepts the uploadHandle), which actually performs the model import into the repository.

**Comment by hristobojilov** [comment]
Hello again Alex,
Please also consider supporting importing of Vorto models from JSON format too.
