### ISSUE TITLE
Can't retrieve attachments from models

### ISSUE THREAD

**Issue by Jeffy4241** [eclipse/vorto#1681]
steps to reproduce : 
-open mapping model https://vorto.eclipse.org/#/details/com.ipso.smartobjects:Push_button_lwm2m:1.1.0
-click on file attached: 
**Expected** : browser download manager opens
**Observed** : `Erreur d’analyse XML : aucun élément trouvé
Emplacement : https://vorto.eclipse.org/api/v1/attachments/com.ipso.smartobjects:Push_button_lwm2m:1.1.0/files/3347_1_1.xml
Numéro de ligne 1, Colonne 1 :`

**Comment by aedelmann** [comment]
Ok. Thx for noticing. Will be looking at it.

**Comment by aedelmann** [comment]
Merged with Development
