### ISSUE TITLE
"Only my models" broken in Chrome

### ISSUE THREAD

**Issue by andrew-from-pretoria** [eclipse/vorto#1692]
Summary:
Chrome does not display my models, but Firefox does.

My objective:

When logged in to https://vorto.eclipse.org , I want to see models the models I created.
I do this by checking the box on the left labeled "Only my models".

The problem:

When using Chrome ( Version 75.0.3770.100 (Official Build) (64-bit)), no models are displayed at all - not even the official models.

However, when using Firefox( 60.7.2esr (32-bit) ), all my models are displayed as expected.

Ideal outcome:

My models should be displayed when using Chrome ( Version 75.0.3770.100 (Official Build) (64-bit)).

**Comment by MayilKannanKumarBosch** [comment]
Hi Andrew,
We have recently made a major release of vorto 0.11, as per our testing we no more see this issue, please retest and let us know if you still face the same issue.

**Comment by aedelmann** [comment]
Closing due to no response from user. Please re-open if problem still exists.
