### ISSUE TITLE
Developer Documentation "How to implement a code generator"

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#170]
The current documentation about how to implement a generator is out-dated. 
This developer documentation should explain:
1) How to get started quickly with Vorto Generator Wizard in Eclipse
2) Implement a small and easy generator that can be run in Eclipse & server side
3) Extend the generator with using mappings + Mapping API to generate a variation.

**Comment by gavinying** [comment]
I will be working on it.
