### ISSUE TITLE
Managing Repositories: tutorial does not correspond to Vorto 0.10.1

### ISSUE THREAD

**Issue by andrew-from-pretoria** [eclipse/vorto#1703]
Summary:

The Vorto 0.10.1 web user interface does not provide a "Manage" option as described in the tutorial.

Detail:

The "Managing Repositories"  tutorial available at < https://github.com/eclipse/vorto/blob/development/docs/tutorials/create_repository.md > 

describes a "Manage" option as indicated in the tutorial image:
![image](https://user-images.githubusercontent.com/966067/60264975-c9602e80-98e4-11e9-9e61-caccc4089bd1.png)

However, when I am logged in, no "Manage" option is available:
![image](https://user-images.githubusercontent.com/966067/60264770-50f96d80-98e4-11e9-8d73-41bfcd5ff428.png)

The problem:
As a logged in user, I am unable to manage my repository as described in the tutorial.

**Comment by aedelmann** [comment]
Hi @andrew-from-pretoria 
You looking at the documentation that is currently on our development branch and not yet released. we gonna release this mid of July.
