### ISSUE TITLE
Downloading device image results in HTTP ERROR 406

### ISSUE THREAD

**Issue by andrew-from-pretoria** [eclipse/vorto#1704]
When attempting to download a device image in the repository, Chrome gives HTTP ERROR 406 and Firefox creates an empty file (zero bytes).

Replicate:
1. login with your github account.
2.  Select "Explore" menu option.
3. Select a model, e.g. Bosch' "TDL".
4. On the page that opens, select "Attachements" ( https://vorto.eclipse.org/api/v1/attachments/com.bosch.bcx:TDL:1.0.0/files/tdl.jpg )

Outcome: 
The attachment can't be viewed or downloaded.

**Comment by aedelmann** [comment]
Merged with Development
