### ISSUE TITLE
Documentation about 0.11 features

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#1707]
Update documentation about 0.11 features
1) How to create own private namespace and manage collaborators
--> Explaination of roles (creator, user, promoter, publisher, reviewer, admin)
2) How to publish Models

**Comment by aedelmann** [comment]
@somesh-kumar  Can you take this up :)

**Comment by aedelmann** [comment]
Hi @timgrossmann 
Can you take this up ?

**Comment by aedelmann** [comment]
Hi @timgrossmann 
Can you link this documentation from 
1) Getting Started
2) Migration Page
3) Add a Help Icon under **Manage** in Vorto Repository

Also, please remove the old Documentation (in itially created by Mayils)

**Comment by timgrossmann** [comment]
#1722
