### ISSUE TITLE
Search Filters not shown

### ISSUE THREAD

**Issue by timgrossmann** [eclipse/vorto#1726]
It seems like there is a problem with the search checkboxes:
- Display my models only
- Display public models only

![image](https://user-images.githubusercontent.com/16529337/60423096-00557d80-9c20-11e9-8ece-f8e9e7fc2674.png)

They are not displayed anymore

**Comment by aedelmann** [comment]
Are you logged in ?

**Comment by aedelmann** [comment]
closing issue as user was not logged in and that was expected behavior.
