### ISSUE TITLE
Can't import Vorto models to nested namespaces

### ISSUE THREAD

**Issue by hristobojilov** [eclipse/vorto#1748]
Let's imagine that I have 2 models:
```
vortolang 1.0

namespace com.mycompany.project1
version 1.0.1

entity Time {
}
```

and:
```
vortolang 1.0

namespace com.mycompany.project2
version 1.0.0

entity Time {
}
```
and I have a tenant with default namespace **com.mycompany.** Now when I try import these from my zip **models.zip** containing those 2 models using standard Vorto importer. I'm forced to select target namespace and after the conversion only 1 model is discovered and the namespace name is incorrect i.e. **com.mycompany**. It should be possible to import models with sub namespaces of the tenant one otherwise there are so many name clashes that it's literally impossible to place every model in one root namespace. This was working perfectly in version 0.10.

**Comment by aedelmann** [comment]
We could make the namespace selector optional, which would then use the namespaces coming from the model. If the user does not own this namespace or is not collaborator of it, it would anyway not allow to import it. What do you think ?

**Comment by hristobojilov** [comment]
Hello Alex,
I think that the namespace **com.company** should be owned by the specific tenant of that company and nobody else except this tenant and perhaps super users (admins) should be allowed to import anything starting with this prefix in order to avoid faking the source of the model. However it should be possible to grant access to other users potentially everyone to read those models. There are very similar policies in web.xml i.e certain url path is accessible for specific user set.

**Comment by aedelmann** [comment]
Hi @hristobojilov 
What you described is the exact behavior of what we are going to release. Only the namespace owner and users that the owner authorizes, is able to import models into that namespace. If you try to upload models with a namespace, you are not set as an owner of, then the repository wont allow you to do that. 
In your example above, you would need to be owner of com.mycompany. Now if you want to import models of namespace com.mycompany.sub, the importer would allow you to do this. 

At the moment the importer namespace selector is not optional, which means , any namespace that you try to import, would be converted to the specified namespace. I can see your point of preserving the namespace suffix in the imported models. 
So the idea here would be to specify the namespace in a selector, and the importer would validate if the imported models comply to the namespace you have selected. It would NOT change the original namespace but take it "as-is" and import it. If it comes accross any model not complying to the specified namespace, it would convert it.

**Comment by hristobojilov** [comment]
It's perfectly acceptable for me to allow imports of models to sub namespaces **com.mycompany.sub** or to convert everything to **com.mycompany** based on user choice. However it doesn't looks reasonable to "flatten" the whole structure if the model namespace starts with **com.mycompany** and put it into a single namespace. If I have a model placed inside **org.apache.whatever** referenced by a model inside **com.mycompany** probably **org.apache.stuff** it should become **com.mycompany.org.apache.stuff** rather than **com.mycompany** because the latter may cause unwanted name clashes.

**Comment by aedelmann** [comment]
Good point. Will consider
