### ISSUE TITLE
Create Mapping button not displayed

### ISSUE THREAD

**Issue by timgrossmann** [eclipse/vorto#1754]
#### Somehow in some instances, the create mapping button is not being displayed.

**Setup**:
- Dev system
- Logged in with GitHub
- Official Namespace

**Situation**:
For an imported Information Model, and one of the publicly visible, the Create Mapping Button does not get displayed (even after reloading the page several times)

![image](https://user-images.githubusercontent.com/16529337/60562449-30b92b00-9d8a-11e9-88c5-119abd3a2d9e.png)

![image](https://user-images.githubusercontent.com/16529337/60562450-331b8500-9d8a-11e9-9d03-ab1c15bc1f77.png)

For a newly created Information Model, the Create Mapping button gets displayed. 

![image](https://user-images.githubusercontent.com/16529337/60562446-2dbe3a80-9d8a-11e9-9952-0137379cfc9e.png)

**Comment by aedelmann** [comment]
Hi @timgrossmann Already fixed. Can you verify ?

**Comment by timgrossmann** [comment]
@aedelmann Seems to be fixed 👍 
Works fine for Information Models of my own namespaces now.

However, shouldn't I also be allowed to create mappings for `Released` and `Public` models?
![image](https://user-images.githubusercontent.com/16529337/60643127-b9a49500-9e64-11e9-872a-6ed054514c77.png)

**Comment by aedelmann** [comment]
you are right. should be possible. its a bug. I am on it

**Comment by aedelmann** [comment]
Not a bug coz it seems that u are not model creator for the namespace org.eclipse.vorto. Therefore it is expected behaviour not showing u the button. :)
