### ISSUE TITLE
Minor: Footer chopping off

### ISSUE THREAD

**Issue by somesh-kumar** [eclipse/vorto#1758]
![footer](https://user-images.githubusercontent.com/31053926/60583516-aa1e4100-9dbd-11e9-8b06-fbca6352b178.jpg)
Opened the Vorto repository in Firefox (resolution full-hd), part of the footer is chopped off. Refer attached screenshot.

**Comment by aedelmann** [comment]
Probability: High
Impact: Very low

**Comment by aedelmann** [comment]
fixed
