### ISSUE TITLE
User should not be allowed to proceed with creating a model without selecting a tenant.

### ISSUE THREAD

**Issue by somesh-kumar** [eclipse/vorto#1760]
As a user I try to create a model without selecting a namespace in the dropdown, I do not see any error even though model creation fails.

Steps to reproduce:

1. Login to repository
2. Click on Create Model
3. Select Information Model
4. Enter a name and without selecting a namespace in dropdown click Next
5. Click create. No error is displayed

Actual:
- Selecting namespace should be mandatory
- Proper error should be displayed if save fails

**Comment by aedelmann** [comment]
Fixed and merged in development
