### ISSUE TITLE
Error exporting models under account settings

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#1764]
Steps taken:
1) Login 
2) Create a bunch of models under your name
3) Go to Account Settings (by clicking on your user ID , next to Log out)
4) Click 'Export Data'
Expected: Zip download containing all models that you had created
Actual: 50x ERROR

Hint: Should be a simple fix. I realized that the called url contains double slashes //

**Comment by aedelmann** [comment]
@erlemantos 
Can you check whats wrong and fix it?

**Comment by erlemantos** [comment]
Will check it

**Comment by aedelmann** [comment]
Hi @erlemantos 
Can you also fix the colors of the buttons of the account settings page:
Delete Button: remains red but also has trash icon
Export Data: btn-default css class
Save: btn-primary css class (should be blue button)
