### ISSUE TITLE
Circular reference in "Vorto Docker Images"

### ISSUE THREAD

**Issue by andrew-from-pretoria** [eclipse/vorto#1777]
At  "Vorto Docker Images" < https://github.com/eclipse/vorto/tree/development/docker >, the text "...follow the the GitHub OAuth App section to optain one point to the current page.

Update the link to point to "GitHub OAuth App section".

**Comment by andrew-from-pretoria** [comment]
Ah, there is actually a section on the same page (bottom). 

Suggestion: update the text to read " ...follow the the GitHub OAuth App section lower down on this page to obtain one." and remove the link embedded in the text "GitHub OAuth App section".

**Comment by MayilKannanKumarBosch** [comment]
I am taking this...

**Comment by aedelmann** [comment]
Fixed
