### ISSUE TITLE
Mapping creation inconveniences

### ISSUE THREAD

**Issue by timgrossmann** [eclipse/vorto#1784]
#### I'm currently working with the Mapping Editor on a given Information Model.

After playing around with it for a bit, I realized that it seems like:
- There is no way to re-open a mapping model in the editor again. (Only editable in the model editor where I have to write the code itself). 

- There is no indication that after some wait time, I've been logged out of the repository and that is why it can't map anything anymore.  Having a note or error message here would be really helpful what to do since I can't see it.

- When I create a new Mapping with the `Create` button, there is also no way to use the mapping editor for easy usage.

- There is no link to documentation that explains the syntax or what to write

--- 

What are your thoughts on that, @aedelmann

**Comment by aedelmann** [comment]
Hi @timgrossmann 
1) There is but it is somewhat hidden. You would need to open the Information Model and you find a link under Mappings. I agree, we need something less hidden :). How about the Mapping button in the top has also a way to open an existing mapping specification in stead of just creating one ? 

2) This would be addressed here: https://github.com/eclipse/vorto/issues/1735 , Correct ?

3) The thing is that you can create a payload mapping only for an existing information model. I guess what you are getting at is to "see" the possibility to create payload mappings directly from the 'Create Model' wizard. Or what do you have in mind?

4) Agree, we need that. Can we add this to the 'Getting Started' with Mappings documentation , possibly in the appendix of the document to show the grammar.

**Comment by timgrossmann** [comment]
1. Resolved in  4137fe70eeca60516377da77a2666bb0134f2afd

2. Yes, thank you.

--- 

3. I see, does it make sense to have the option to create a mapping from the `+ Create Model` dialog then?

4. On it 👍

**Comment by aedelmann** [comment]
> I see, does it make sense to have the option to create a mapping from the + Create Model dialog then?
Yes, it does. I created an issue to track this: https://github.com/eclipse/vorto/issues/1793 

Closing this issue, as other issues for tracking are created.
