### ISSUE TITLE
Add release notes to Release 0.11

### ISSUE THREAD

**Issue by timgrossmann** [eclipse/vorto#1795]
#### Since the release notes are a little bit hidden in the docs folder, I think it would make sense to enrich the [GitHub Releases](https://github.com/eclipse/vorto/releases) release of `0.11` with the notes themselves, using the `Draft new Release` in the releases section.

This way, users will instantly see the additions in the new version without searching the repository.

---

Example visuals of release
![2019-07-12_11h09_53](https://user-images.githubusercontent.com/16529337/61099857-59ca7180-a496-11e9-96ee-98c5f6747645.png)

**Comment by aedelmann** [comment]
@timgrossmann 
Good idea.
