### ISSUE TITLE
Non org.eclipse.vorto function blocks show up as abstraction during model creation

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#1802]
Steps to reproduce
1. Login with Bosch or GitHub id as user with model creator permission
2. Create new information model with 'Create Model'
3. During model creation, the Vorto abstraction wizard page shows. Select 'org.eclipse.vorto'
4. Open Drop down 
Expected: Drop down only shows function blocks in org.eclipse.vorto namespace
Actual: All public released function blocks are displayed

**Comment by erlemantos** [comment]
I'll take this
