### ISSUE TITLE
If user opens a dialog / modal and accidentally clicks outside of modal, it closes and all entered data Is lost.

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#1814]
Steps to reproduce
1. Login
2. Create Model which opens dialog
3. Click outside the modal
Expected: Teh modal remains open
Actual: The modal closes and all data which was entered is lost.

This behaviour should be for all available modals/dialogs.

**Comment by MayilKannanKumarBosch** [comment]
I am taking this...
