### ISSUE TITLE
Sys admins not able to view released models 

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#1816]
Steps taken 
1. Login as sys admin 
2. Search a released model of somebody’s namespace. Make sure u are not a collaborator of that namespaxe
3 go to model details 
Expected : model details is shown
Actual: redirect to login page

**Comment by erlemantos** [comment]
Is this still reproducible? I can't reproduce this in vorto-dev. I log in as erlemantos. I can open released models in com.timgrossmann even if I'm not a collaborator in that namespace.

**Comment by aedelmann** [comment]
I came across this recently on prod system. I had to make myself explicitly a collaborator with view rights to see the model details. 
Not sure in what scenerio this bug appears. We can keep it open for now. But lower prioritise it.
