### ISSUE TITLE
"Add Reference" Button on new model Release missing

### ISSUE THREAD

**Issue by timgrossmann** [eclipse/vorto#1823]
When creating a new ~release~ version of an Information Model, the `Add Reference` button is **not available** to quickly and conveniently add new references.   
Only after reloading the model page, the `Add reference Button` is Visible

**Comment by aedelmann** [comment]
@timgrossmann Isn't that expected behaviour to not show the add reference button for released models, as they cannot be changed anyway ?

**Comment by timgrossmann** [comment]
@aedelmann Sorry, my bad.
Updated the description to say what I actually meant. Creating a new version of the model instead of a new release.

**Comment by timgrossmann** [comment]
@aedelmann Also, just tested it again and it seems that this was a one time problem I can't reproduce today. Maybe it was a problem of me switching network connections in-between.
Seems to work fine now
