### ISSUE TITLE
Add search expression for searching specific parts of the model id (namespace, name, version)

### ISSUE THREAD

**Issue by erlemantos** [eclipse/vorto#1833]
Add a search expression that can be used to filter specific parts of the model id (namespace, name, version)

_/api/v1/search/models?expression=namespace:\<namespace\>_ - exact search
_/api/v1/search/models?expression=namespace:\<namespace\>*_ - wildcard search

Since we are using "name:\<part of model id\>" as a search expression right now, maybe we can change this to "modelId:\<part of model Id\>" so we can use "name:\<name\>*" to do an exact or wildcard search on the name field of the modelId, just to harmonize our API.

So, in effect:

_/api/v1/search/models?expression=namespace:\<namespace\>_ - exact search on namespace
_/api/v1/search/models?expression=namespace:\<namespace\>*_ - wildcard search on namespace
_/api/v1/search/models?expression=name:\<name\>_ - exact search on name of modelId
_/api/v1/search/models?expression=name:\<name\>*_ - wildcard search on name of modelId
_/api/v1/search/models?expression=version:\<version\>_ - exact search on version of modelId
_/api/v1/search/models?expression=version:\<version\>*_ - wildcard search on version of modelId

_/api/v1/search/models?expression=modelId:\<any parts of the modelId\>_ - our current "name:\<expr\>" search

**Comment by mena-bosch** [comment]
Currently looking at the search and documenting as I go. Currently the free-text search seems to be using match prefixes for all values (it actually appends an asterisk if none present). Also not sure about robustness of edge-case where multiple identical search tags are used. Happy to take this if no one currently working on.
