### ISSUE TITLE
Improve Arduino Generator when functionblock name is equal to "value"

### ISSUE THREAD

**Issue by jacewski** [eclipse/vorto#1838]
If a functionblock name equals ``value``  the resulting Setter method tries to set ```value=value``` which results in using the private variable instead of the Setter parameter.

**Comment by aedelmann** [comment]
Steps to reproduce:
1. Go to Vorto Repository and open Illuminance FB
2. Generate Arduino Code (Bosch IoT Suite)
3. Extract zip and open Illuminance.c 
Expected: 
setSensorValue(SensorValue _value) {
value = _value
}
Actual: 
setSensorValue(SensorValue value) {
value = value // CONFLICT 
}

**Comment by somesh-kumar** [comment]
Working on it.
