### ISSUE TITLE
Vorto Repository Swagger OAuth Flow with Bosch ID and Github not working

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#1840]
Steps taken
1. Go to https://www.eclipse.org/vorto/swagger
2. Open 'Authorize'
3. Add client ID and clientSecret for your Github OAuth App
4. Confirm with OK
Expected: OAuth token authenticated , so user can make authenticated requests
Actual: No OAuth token available

**Comment by kolotu** [comment]
seems to be fixed - works now.
