### ISSUE TITLE
The model tree in perspective allows to be resizable by the user.

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#187]
The individual tree viewers in the Vorto perspective are currently fixed size. 
It would be a nice little feature to make the views adjustable in height.

**Comment by laverman** [comment]
I experienced, that this is really wanted when creating many models and add dependencies using the drag&drop mechanism. It becomes very cumbersome to drag an datatype zzType on another datatype aaType since it scrolls very slowly :-) :+1:
