### ISSUE TITLE
Attribute Comments not working with OpenAPI Generator

### ISSUE THREAD

**Issue by philbuettner** [eclipse/vorto#1872]
The comments are processed by the OpenAPI generator and included in the yml specification file. However, these are not displayed when visualizing the document. I guess the comments are  inserted in the wrong place.

![grafik](https://user-images.githubusercontent.com/25966235/62468277-fb8f6680-b795-11e9-95fe-65637bc94b9d.png)

![grafik](https://user-images.githubusercontent.com/25966235/62468292-021dde00-b796-11e9-822a-9d6b07b647b4.png)

![grafik](https://user-images.githubusercontent.com/25966235/62468512-88d2bb00-b796-11e9-9fa8-c92f13dafbd3.png)

**Comment by aedelmann** [comment]
Hi @philippebuettner 
You are right. These descriptions should be appearing in the generated documentation. We take a look at it.

**Comment by MayilKannanKumarBosch** [comment]
Hi @philippebuettner,
As per the below swagger-api documentation thread,  the description field and $ref field cannot co-exist, and any description should exist only where the $ref values point to.

Hence even if the yml specification file has the description, it will be ignored during visualization.

https://github.com/swagger-api/swagger-editor/issues/1184

For example, in the issue which you have reported, any description to 'powerMeter', 'deviceInfo' etc. should be given in the description where they are referenced and no additional description is possible in the location where they are referred.

Thank You.

**Comment by aedelmann** [comment]
Hi @philbuettner 
Closing this issue, as from my perspective, there is nothing we can do at this point.

**Comment by aedelmann** [comment]
Hi @philbuettner 
Thanks for the info. @MayilKannanKumarBosch what do you think ?
