### ISSUE TITLE
Get latest model without specifying version

### ISSUE THREAD

**Issue by philbuettner** [eclipse/vorto#1878]
Is it anyhow possible when using a generator like openapi to get the latest model without specifying the version? Now we have for instance:  

`curl -X GET "https://vorto.eclipse.org/api/v1/plugins/generators/openapi/models/${namespace}:${model}:${version}?digitaltwin=boschiotthings" -H "Accept: application/octet-stream" -H "Authorization: Bearer ${token}" --output ./${workdir}/${model}.yml`

It would be nice, if I could specify the version variable as 'latest' or leave it out to get the current model.

**Comment by aedelmann** [comment]
Hi @philbuettner 
at the moment, you must specify the version, I am afraid. Though, It is an interesting idea of yours to specify something like LATEST, as in maven. Will look into that.

**Comment by philbuettner** [comment]
Hi @aedelmann 
are there any news regarding this issue?

**Comment by kolotu** [comment]
I'm taking this one up.

**Comment by philbuettner** [comment]
Unfortunately, this is not working with "latest" nor "LATEST", if TAG replaces version, e.g. "1.0.0". 
The requests always results with 406 - not acceptable. 
Could you please check this?
