### ISSUE TITLE
Unwanted character in model preview

### ISSUE THREAD

**Issue by somesh-kumar** [eclipse/vorto#1886]
Steps to reproduce:

1. Open repository
2. Click on any model
3. Scroll to the bottom of page, you will see an angular bracket (refer attached screenshot)

**Comment by somesh-kumar** [comment]
<img width="460" alt="Unwanted Character" src="https://user-images.githubusercontent.com/31053926/63400181-85316c00-c405-11e9-99ec-3be71ea22e90.png">

**Comment by aedelmann** [comment]
Fixed
