### ISSUE TITLE
Docker image v0.11.0 not working

### ISSUE THREAD

**Issue by w4tsn** [eclipse/vorto#1889]
The repository image for 0.11.0 is not working, following the guide and setting it up with `./data/db` correct access rights for mysql) and `./data/repo` folders, `vorto-variables.env` and the `docker-compose.yml`. 

How to reproduce
---

1. Follow the guide under [docker/Readme.md](https://github.com/eclipse/vorto/blob/development/docker/Readme.md)
2. Create directories for vorto and mysql and specify them in docker-compose file
3. docker-compose up

What happens
---

The application tries to start and crashes just before it would normally run. It complains about jks keystore file not found and tomcat crashes.

[vorto-0110-crash.txt](https://github.com/eclipse/vorto/files/3524491/vorto-0110-crash.txt)

What should happen
---

The application should normally start without requiring any keystore file. The changes of the new bosh IoT feature introducing [this config](https://github.com/eclipse/vorto/blob/411b876425f57b6c39e0736635ea46244ec36e51/repository/repository-server/src/main/resources/application-local.yml) should be reflected in the docker `README.md` and wherever it might cause this break.

**Comment by w4tsn** [comment]
I can confirm now that the current :nightly build is working. Is it planned to publish 0.11.3 or 0.12 and succeeding builds to docker hub again?

**Comment by aedelmann** [comment]
We are releasing 0.12 end of the month with these changes.
