### ISSUE TITLE
OpenAPI Generator - Available authorizations: BoschID

### ISSUE THREAD

**Issue by philbuettner** [eclipse/vorto#1890]
The OpenAPI documents generated via the OpenAPI generator provides an 'Authorize'-Button. Besides the token based authorization mechanisms bearerAuth and thingsApiToken, there is also an authorization code grant flow via BoschID provided.  

But without the ability as a 'normal' user to define an authorization callback URL via CIAM, it is difficult to use the Bosch ID. Also, even if one could define an authorization callback URL, how will one make an endpoint available to complete the authorization code grant flow?

I wonder, if it makes sense to list the BoschID as available authorization for the OpenAPI document? What is the background of this?

**Comment by aedelmann** [comment]
Hi @philbuettner 
Bosch IoT Things supports authentication via BoschID OAuth. I agree, this makes only little sense for this generated OpenAPI Swagger Documentation. We should remove it as well as GitHub and only provide the bearer token variant. Would that work for you ?

**Comment by philbuettner** [comment]
I would suggest to keep bearerAuth and thingsApiToken.

**Comment by aedelmann** [comment]
@philbuettner 
AFAIK, the thingsApiToken is not required, if bearer token is passed along to Things, or am I wrong ?

**Comment by aedelmann** [comment]
Removed Bosch ID and only specified bearerToken in generated spec.
