### ISSUE TITLE
OpenAPI Generator - Status defined as object

### ISSUE THREAD

**Issue by philbuettner** [eclipse/vorto#1891]
When generating OpenAPI documents from Vorto models,  the error handling objects always contains an attribute 'status' which provides the HTTP status of an error:
`{
  "status": 0,
  "error": "string",
  "message": "string",
  "description": "string",
  "href": "string"
}`

But at the same time the properties object of a feature always contains a status object, which contains the actual properties:
`  "properties": {
    "status": {
      "batteryLevel": "low"
    }
  }`
`"properties": {
    "status": {
      "connectionState": "available",
      "name": "string",
      "serialNumber": "string",
      "deviceId": "string",
      "deviceModel": "string",
      "manufacturer": "string",
      "profile": "string"
    }
  }`

This looks to me as it was intended to provide 'status' as an attribute in each object, instead of nesting the attributes of properties in a status object. Could this be?

Otherwise, would it be possible to remove the 'status' object and put all attributes directly into the 'properties' object?

**Comment by aedelmann** [comment]
Hi @philbuettner 
Status object is required by Eclipse Ditto / Things Service. Therefore we cannot remove it.

**Comment by philbuettner** [comment]
I see, the 'status' object is part of the Vorto model and should used beside 'events', 'operations' and 'configuration' for a better structuring of the model.
