### ISSUE TITLE
OpenAPI Generator- Feature definitions seems redundant

### ISSUE THREAD

**Issue by philbuettner** [eclipse/vorto#1892]
The feature endpoint like the following returns both the properties and the definition:
`/things/{thingId}/features/{feature}` 
returns
`{
  "definition": [
    "string"
  ],
  "properties": {
...
  }
}`

So it seems to be obvious that the following endpoint, provides only the definition as this is a normal JSON notation:
`/things/{thingId}/features/{feature}/definition`
returns 
`["string"]`

Hence, to document the definition endpoint seems to be redundant. Would it be possible to leave this out to get a more compact OpenAPI document?

**Comment by aedelmann** [comment]
Hi @philbuettner 
> Hence, to document the definition endpoint seems to be redundant. Would it be possible to leave this out to get a more compact OpenAPI document?

You mean, leave out this REST - API endpoint altogether ? I agree, this is redundant and honestly not so useful to just request the definition field, as you get it anyway if you ask for the entire feature.

**Comment by philbuettner** [comment]
Yes, I meant only for the OpenAPI document. Great, thank you!
