### ISSUE TITLE
OpenAPI Generator - Define Vorto model attribute as multiple 

### ISSUE THREAD

**Issue by philbuettner** [eclipse/vorto#1893]
In com.bosch.sh:SmartHomeController:1.0.0 we defined an attribute 'scenario' as multiple. Unfortunately this is not recognized by the OpenAPI Generator. So it looks like, that there is only one scenario for each Smart Home Controller. 

To implement a workaround seems to be easy. But should we adjust the model at this point or will the generator be adjusted here?

**Comment by aedelmann** [comment]
Hi @philbuettner 
yes, multiple fields on Information Models level are not supported in the current Swagger because there is no easy mapping to the Things Feature structure. Why do you use scenario as a multiple field ? Could it be modelled differently ?

**Comment by philbuettner** [comment]
Yes, we will model it in a different way.
