### ISSUE TITLE
Bug: Cannot delete a namespace

### ISSUE THREAD

**Issue by somesh-kumar** [eclipse/vorto#1927]
A non-admin user is unable to delete his namespace.

Steps to reproduce:

1. Sign-in with your non-admin account
2. Click on Manage Tab
3. Delete your namespace
4. A dialog box appears with a message, "Namespace cannot be deleted because it contains public models"

Expected:
Since the user does not have any models he should be able to delete his user.

Note:- If user is fast enough to hit the delete button then he is able to delete the namespace successfully.

**Comment by aedelmann** [comment]
fixed
