### ISSUE TITLE
User can bypass the T&C during first login

### ISSUE THREAD

**Issue by somesh-kumar** [eclipse/vorto#1936]
Steps to reproduce

1. Signin as a new customer
2. T&C pop-up will be displayed, ignore it and click on Explore tab

Actual Result: User is able to bypass the T&C popup during first Sign-in.

Expected Result: User should not be able to bypass the T&C screen

**Comment by erlemantos** [comment]
https://github.com/eclipse/vorto/pull/1951 - pull request

So, basically, for this issue, we converted the T&C to a modal dialog that cannot be dismissed. This takes care of the user being tempted to click on any link. We also added the privacy policy as among those the user needs to accept.
