### ISSUE TITLE
BUG: Transferred ownership of my namespace, still couldn't delete my account

### ISSUE THREAD

**Issue by somesh-kumar** [eclipse/vorto#1940]
I tried to delete my account after transferring the ownership of my namespace to another user. The deletion failed with no message.

Steps to reproduce:
1. Signin
2. In your custom namespace create a model and make it public
3. Add a collaborator and give the person full permissions to your namespace
4. Ask the collaborator to remove you from the namespace
5. Delete your account

Expected Result: Account is successfully deleted and all your models become anonymized

Actual Result: User is stuck at Delete Account pop-up with the following response

Request URL: https://vorto-dev.eclipse.org/rest/accounts/USER_ID
Request Method: DELETE
Status Code: 401 

Issue occurs only in case of a published model.

**Comment by erlemantos** [comment]
I'll take this

**Comment by somesh-kumar** [comment]
Working as expected
