### ISSUE TITLE
BUG: Comments do not get anonymized after user deletes his account

### ISSUE THREAD

**Issue by somesh-kumar** [eclipse/vorto#1952]
Steps to reproduce:

1. Sign-in
2. Make a comment on any existing model which is not in your namespace
3. Delete your account

Expected: The comment should become anonymous

Actual: The comment continues to show the user-id

**Comment by aedelmann** [comment]
Please fix this also for this current release by end of the week :)

**Comment by somesh-kumar** [comment]
@aedelmann , could you rename the files with the "colon" in filename. None of us can pull on our windows machines due to invalid filename.

**Comment by erlemantos** [comment]
These particular files:

https://github.com/eclipse/vorto/blob/development/repository/repository-core/src/test/resources/sample_models/payloadmapping/org.eclipse.vorto:Battery:1.0.0.fbmodel

https://github.com/eclipse/vorto/blob/development/repository/repository-core/src/test/resources/sample_models/payloadmapping/org.eclipse.vorto:MyDevice:1.0.0.infomodel

https://github.com/eclipse/vorto/blob/development/repository/repository-core/src/test/resources/sample_models/payloadmapping/org.eclipse.vorto:Voltage:1.0.0.fbmodel
