### ISSUE TITLE
Recursive walk-through in generator plugin template not always working

### ISSUE THREAD

**Issue by w4tsn** [eclipse/vorto#1954]
I've written a ditto skeleton generator plugin template. It's build with the Plugin API v2 using Vorto 0.11.3-nightly. In my models I have a generic base fbmodel with configuration and status. Several other fbmodels extend this model without adding new fields to config or status. Having 7 functionblocks defined in an infomodel, only the 7nth will be processed correctly and receive the parents properties, all others will only receive an empty properties section.

See my [vorto-ditto-skeleton-generator](https://github.com/w4tsn/vorto-ditto-skeleton-generator) project for reference how I'm using the generator as micro-service in a docker-container.

What is wrong?
---

The generator does not always traverse through the `extends` dependencies and return all of the configuration and status properties. This might be a bug or a flaw in my template.

How to reproduce
---

My used docker-compose file looks like this: 
[docker-compose.yml.txt](https://github.com/eclipse/vorto/files/3622506/docker-compose.yml.txt)

A working and verified image is [on docker hub](https://cloud.docker.com/u/lionax/repository/docker/lionax/vorto-ditto-skeleton-generator): `lionax/vorto-ditto-skeleton-generator:latest`

The vorto-variables.env looks like this:

```env
# Generell settings
GENERATOR_USER=vorto_generators
GENERATOR_PASSWORD=1234
VORTO_PORT=8080
CONTEXT_PATH=/

# Repository
DATASOURCE=mysql
AUTH_PROVIDER=github
ADMIN_USER=<your-github-user>
GITHUB_CLIENT_ID=<your-github-client-id>
GITHUB_CLIENT_SECRET=<your-github-client-secret>
PLUGINS=<base64 encoded json structure>

# Generators
VORTO_URL=http://repository:8080
3RD_PARTY_SERVICE_URL=http://generators:8080

# database
MYSQL_USER=root
MYSQL_ROOT_PASSWORD=<your-mysql-password>
MYSQL_DATABASE=vorto
```

Used example infomodel and fbmodels [othermo.meter_Heat_1.0.0.zip](https://github.com/eclipse/vorto/files/3622501/othermo.meter_Heat_1.0.0.zip)

[The skeleton template](https://github.com/w4tsn/vorto-ditto-skeleton-generator/blob/master/generator-eclipsedittoskeleton/src/main/java/com/othermo/vorto/plugin/dittoskeleton/templates/ThingSkeletonTemplate.xtend) can be found [in my skeleton project on github](https://github.com/w4tsn/vorto-ditto-skeleton-generator).

How should it be?
---

If the template is correct, the generator should in any case return all properties of a model and it's parents.

**Comment by aedelmann** [comment]
Hi @w4tsn 
we could reproduce your problem and working on a fix right now, which we will ship in a patch release the next few days.

**Comment by aedelmann** [comment]
fixed
