### ISSUE TITLE
BUG: Namespace validation

### ISSUE THREAD

**Issue by somesh-kumar** [eclipse/vorto#1977]
Unable to create a model if namespace name has numbers e.g. xxx.xxx.123

Steps to reproduce
1. Signin
2. Create a new namespace vorto.private.1920
3. Create a information model in this namespace
4. Check network response in browser

Expected: Model should be created successfully

Actual: Model creation fails with no error, error can be checked through browser console network response

**Comment by aedelmann** [comment]
fixed
