### ISSUE TITLE
BUG: Rest API /policy is invoked with a 404 response each time a model is opened

### ISSUE THREAD

**Issue by somesh-kumar** [eclipse/vorto#1979]
Rest API /policy is invoked with a 404 response each time a model is opened

Steps to reproduce
1. Signin
2. Open browser console
3. Open any model

Actual: An error appears in console
angular.js:9827 GET https://vorto-dev.eclipse.org/rest/models/xxxxxxxxxx/policy 401(for a normal user), 404 (for a sys admin)

Expected: No errors should appear in browser console

**Comment by aedelmann** [comment]
fixed
