### ISSUE TITLE
Bulk Operations on models

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#1982]
Add batch-operations: mark a number of infomodels/functionblocks/datatypes and perform operations on them (e. g. change namespace, release, withdraw, delete, ...). Doing this manually for a large number of models was super time consuming.

Also important is to have explicit confirmation dialogs before bulk operations happen.

Functionalities:
   * Select a list of models (ideally list of checkboxes)
   * Allow Releasing of Models Bulk
   * Allow Withdrawing of Models Bulk
   * Allow Deleting of Models Bulk

**Comment by mena-bosch** [comment]
This sounds interesting. Let me know the suggested priority on this one @aedelmann - assuming the task is not "taken" already.

**Comment by aedelmann** [comment]
Hi @mena-bosch 
We should refine this issue first. I think this issue splits into two forms of bulk operations:
1. Cascade bulk: An operation on a single model can cascade down to all referenced models without explicitly selecting them. A confirmation dialog could pop up , where the user can select the cascade option with a checkbox check.
2. Selective Bulk operation in search: The user selects multiple models that he/she sees in the search result and then executes the bulk operation on them. This again could perform a bulk as specified under option 1. 

What do you think ?

**Comment by mena-bosch** [comment]
@aedelmann sorry, I kind of lost track of this one. Will revisit when time allows - hopefully soon. 
@kolotu for visibility - you can assign to me if you like.

**Comment by kolotu** [comment]
Option 2 will be followed up here: https://github.com/eclipse/vorto/issues/2333

**Comment by kolotu** [comment]
Specifications for the implementation of this issue: 
Cascade bulk: An operation on a single model cascades down to all referenced models without explicitly selecting them. A confirmation dialog pops up that warns the user that all referenced models will be automatically affected as well.

**Comment by t-gauss** [comment]
Will look into this.

**Comment by t-gauss** [comment]
PR [here](https://github.com/eclipse/vorto/pull/2346)
