### ISSUE TITLE
Add JSON Skeleton to Ditto Generator

### ISSUE THREAD

**Issue by w4tsn** [eclipse/vorto#1993]
The ditto generator plugin shipped with this repository requires a JSON skeleton feature for several use-cases regarding the integration of ditto and vorto.

Based on [this standalone docker service implementation](https://github.com/w4tsn/vorto-ditto-skeleton-generator) I want to implement and provide this feature. I'm planning on using the configuration UI from the helloworld-example as a starting point to add this feature as additional configurable option to the existing generator in this repository.

A distant related issue from ditto is [ditto#247](https://github.com/eclipse/ditto/issues/247), which is about coupling vorto infomodels on a thing level. Implementation of this would trigger an update of this feature.

**Comment by kolotu** [comment]
Hi @w4tsn, 

What do you mean by JSON skeleton? If you want to create a Ditto Thing JSON based on a Vorto Information Model, this has been implemented within the Ditto Generator as part of #2104.

**Comment by w4tsn** [comment]
Yeah, that was the plan. I used this issue to track that and was also working on something but didn't find the time to submit a PR.

That closes the issue ;)
