### ISSUE TITLE
Excessive verbosity in Vorto tutorial

### ISSUE THREAD

**Issue by andrew-from-pretoria** [eclipse/vorto#2028]
In the tutorial at https://github.com/eclipse/vorto/blob/development/docs/tutorials/create_mapping_pipeline.md , this sentence can be improved: 

"As mentioned earlier, we are going to design an architecture, that makes our application being able to consume data from any geolocation sensor vendor, with the help of Vorto Mapping Specifications."

Suggested version:

"As mentioned earlier, we are going to use the Vorto Mapping Specifications to design an architecture that allows our application to consume data from any geolocation sensor vendor."

**Comment by somesh-kumar** [comment]
@andrew-from-pretoria , thinking of changing the sentence to "Let's design an architecture, that makes our application being able to consume data from any geolocation sensor vendor, with the help of Vorto Mapping Specifications."

The How? in my opinion is quite important, which in this case is the mapping engine. What are you thoughts?

**Comment by andrew-from-pretoria** [comment]
**@somesh-kumar** How about: "One of the challenges faced in IoT is that vendors use their own payload representations. JSON and CSV are two examples of payload representations. Vorto Mapping Specifications together with Normalisation Middleware is a mechanism we will use to normalise the various payload representations. Once this has been done, our application will be able to consume data originating from any geolocation sensor vendor. To achieve this, a Vorto Mapping specification must first be written for each expected payload representation."

**Comment by aedelmann** [comment]
Replace representation with formal and it’s good to go :) 
This will fit together with the image update u provided.

**Comment by andrew-from-pretoria** [comment]
Adding aedelmann's suggestion: "One of the challenges faced in IoT is that vendors use their own payload formats. JSON and CSV are two examples of payload formats. Vorto Mapping Specifications together with Normalisation Middleware is a mechanism we will use to normalise the various payload formats. Once this has been done, our application will be able to consume data originating from any geolocation sensor vendor. To achieve this, a Vorto Mapping specification must first be written for each expected payload format."

**Comment by andrew-from-pretoria** [comment]
@somesh-kumar I do not rights to make the changes. Will you upload the changes?

**Comment by aedelmann** [comment]
You can fork the project, make the changes and make the Pull Request.

**Comment by Ineskouka** [comment]
I will take
