### ISSUE TITLE
Tutorial image: suggested changes

### ISSUE THREAD

**Issue by andrew-from-pretoria** [eclipse/vorto#2030]
![overview_suggested changes](https://user-images.githubusercontent.com/966067/66993217-772d5e00-f0cb-11e9-8a2b-dfdacea58dc5.png)
On page vorto/docs/tutorials/create_mapping_pipeline.md , image vorto/docs/images/tutorials/decouple_tutorial/overview.png , in section "Decouple IoT solutions from connected device data" I suggest that "Payload" be changed to "Payload Format" /"Normalised Format". Also, a new Vorto Model block be added that feeds into the existing Vorto Middleware block, and the existing Vorto block be renamed. I include a crude image showing the suggested changes.

**Comment by Ineskouka** [comment]
I can take
