### ISSUE TITLE
tutorial/create_mapping_pipeline - Suggested rewording

### ISSUE THREAD

**Issue by andrew-from-pretoria** [eclipse/vorto#2035]
On page vorto/docs/tutorials/create_mapping_pipeline.md ( https://github.com/eclipse/vorto/blob/development/docs/tutorials/create_mapping_pipeline.md ), Step 2 reads "Step 2: Sending geolocation data to MQTT". 

Proposed rewording: "Step 2: Sending geolocation data to Bosch IoT Hub using MQTT protocol."

**Comment by Ineskouka** [comment]
i will take
