### ISSUE TITLE
Support searching for models that contain a search string in their name

### ISSUE THREAD

**Issue by stheves** [eclipse/vorto#2046]
When searching for models I can use a wildcard (*) at the end of my query but not at the beginning. I want to search for models which _contain_ a search string in their name. That is currently not possible. **Example:**
Given the following request:
`https://vorto.eclipse.org/api/v1/search/models?expression=InformationModel%20name%3AIllum%2A`
I would expect to find all models which contain the search string 'Illum' but the result is empty. I can also not specify the wildcard (*) at the beginning of the expression thus makes it impossible to find the Vorto model "SimpleIlluminance"

**Comment by mena-bosch** [comment]
Hi @stheves , I am looking at this ticket at the moment. 

My understanding is that the ticket underlines two problems with the search: 

1. No full support for wildcard searches - this is simply not implemented (yet). Only a final wildcard works (it is in fact added automatically in the web GUI when searching for names, but not in REST). 
2. Multiple free-text (i.e. untagged) terms don't play well with each other. 

I have started working on a broader change to the search when most notably:

* Multiple wildcards per term would be supported (e.g. `*Ill?m*`)
* For clarity, only the name search would allow untagged terms, while e.g. the model type would 
require a tag i.e. `type:InformationModel` (or not so useful but still supported: `type:*nformation*`)
* And many other improvements...

The problem with this approach essentially boils down to time - it would be a non trivial change and require significant documentation. 

My questions for you: 

1. Are my assumptions with regards to your requirement correct? If not, can we maybe clarify on gitter?
2. What is the urgency of your requirement? Could it wait for the full change, e.g. end of December or would you rather have some prototype done more urgently?

Thanks

**Comment by stheves** [comment]
Hi @mena-bosch , for us it would be sufficient to have a wildcard at the beginning _and_ at the end of a search query e.g. `*illum*`.  It would also be helpful if the search works case-insensitive, meaning a search query `*IlluM*` and `*illum*` will return the same results or at least we can specify how the cases should be treated by the search API. We do not need other wildcards e.g. `"?"`. 
This feature request here is _not_ urgent. We can wait until the end of December, no problem.

**Comment by mena-bosch** [comment]
Thanks for the clarification @stheves , will keep you updated :)

**Comment by mena-bosch** [comment]
Hi @stheves, just a quick heads up: there is a big feature refresh of the search in the works - it has been merged to the development machine already although not yet released to production. The update covers this request as well as others, and is aimed at making the search more powerful, versatile and documented. Worth noticing in your case, it will allow you to use wildcards everywhere in the values, and will also be case-insensitive. We're still working through some obstacles, namely the new integration tests for the search require some connectivity that the development machine currently does not have, but I'm hoping this will be resolved soon. Thanks for your patience!
