### ISSUE TITLE
Closed projects still visible in Vorto Perspective

### ISSUE THREAD

**Issue by nagavijays** [eclipse/vorto#206]
When Vorto project is closed in Java and switch back to Vorto Perspective the project still appears in combobox. The closed project should not shown in combobox to avoid eclipse errors.

**Comment by aedelmann** [comment]
Relates to #209

**Comment by laverman** [comment]
Although #209 is closed, this issue is still there. A "Refresh" Button would help, since currently the only workaround is to close and re-open the Vorto Perspective.
