### ISSUE TITLE
REST Endpoint for managing namespaces and collaborators

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#2061]
**Motivation**
Integration of Vorto and available namespaces from external services, e.g. Bosch Portal when subscribing to services

**Confirmations:**
- REST endpoints are secured whereby a needed OAuth2 token needs to be passed to identify the user
- OpenAPI / Swagger documentation
- Following REST Resources:

**Get Namespace details**
GET /api/1/namespaces/{namespace}
**Response**
200: Lists the namespace (see namespace object definition below)
403: User is not a collaborator for the given namespace
400: Namespace is not known or valid

**Gets all namespaces**
GET /api/1/namespaces
**Response**
200: Lists all namespace (see namespace object definition below), that the provided user is collaborator of

**Adding a collaborator to Namespace**
PUT /api/1/namespaces/{namespace}/collaborators/{userId}
Payload Request: Collaborator
**Response**
200: Successfully added
403: Not authorised to add collaborator. Only namespace admins are allowed to add collaborators.
400: Bad request

**Namespace**
- namespace name
- list of collaborator objects

**Collaborator object**
- ID (string, userID, e.g. githubID, ciamID, technicalUserID) - mandatory
- roles (enum: view, creator, ...) - mandatory
- provider key (enum: Github, BoschID, BoschSuiteAuth) - mandatory
- subject (string, only mandatory for provider == BoschSuiteAuth)

Hint:
The provider key must match the key of the OAuthExtension of the OAuthProvider Extension Point. Each OAuthExtension returns a key to uniquely identify the oauth provider.

**Comment by erlemantos** [comment]
I'll take this

**Comment by erlemantos** [comment]
@aedelmann 

Modify namespace Request
PUT /api/1/namespaces/{namespace}
Payload: The new namespace admin IDs and their provider IDs (Bosch ID, Github)

This is additive, right? It won't replace the old one, just adds the new ones in the payload?

**Comment by aedelmann** [comment]
Good question. I would replace it with the new set. What do you think ?

**Comment by erlemantos** [comment]
Sounds perfectly fine.
