### ISSUE TITLE
Generator Runner Spring Boot as alternative to lambda for running generators

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#2093]
Steps taken (during local development):
- Run the Generator Runner Spring Boot application locally
- Run the Vorto Repository locally , whereby its plugins configuration points to the local Generator Runner
- Open any Information model which you want to generate code for
- Click on Eclipse Hono Generator (right handsome) which opens the Generator Configuration popup
Expected: Popup displays 3 radio buttons with a selection of either Arduino, Java or python.
Actual: Popup does not display any selection. 

Some background info is required to work on this task. Each Code Generator provides meta information about  parameters that the generator can process. For example, the Eclipse Hono generator has a language parameter with a choice of values, namely Arduino, java, python. 
At runtime, the Vorto Repository requests the generator meta information and creates a default UI Configuration html snippet that it sends back to the Angular Controller to render. 

**Problem Analysis (so far)**
- The Generator Runner project does not process the code generator meta information for parameters at all and therefore does not create any UI that it sends back to the client.

**Comment by aedelmann** [comment]
Hi @mena-bosch 
I added some more info about this issue. Hope that clarifies it a bit more. If not, feel free to comment this issue :)

**Comment by kolotu** [comment]
I'm not sure, whether the Generator Runner is still needed. I'm currently investigating, whether it's feasible to run the generators as local AWS Lambdas, which would be better, since it's the same mechanism as on Dev / Prod.
I'll update this issue, when I have a conclusion on that.

**Comment by kolotu** [comment]
IMO this issue is not needed anymore. See #2223

**Comment by kolotu** [comment]
I'll tentatively close this. In case, we continue to use the Generator Runner, I'll reopen it.
