### ISSUE TITLE
Free memory/storage function blocks

### ISSUE THREAD

**Issue by e-grigorov** [eclipse/vorto#2097]
Currently, I am modelling information model where the [DeviceInformation](https://vorto.eclipse.org/#/details/org.eclipse.vorto:DeviceInformation:1.0.0) function block is used. This block contains totalMemory and totalStorage properties. Having them, I would like to provide the free memory and the free storage.

Are there Vorto function blocks to cover them? I cannot find such in the repo but they seem to be useful feature.

**Comment by aedelmann** [comment]
I would suggest to provide a second version having these additional properties. What do u Think ? I could add u as a collaborator to the Vorto namespace.

**Comment by aedelmann** [comment]
Hi @e-grigorov 
I added you as collaborator for org.eclipse.vorto namespace. You can now create a model there and propose for review.

**Comment by e-grigorov** [comment]
I have to complete the research of some more parameters.

**Comment by kolotu** [comment]
Hi @e-grigorov 
You have been added as collaborator to the org.eclipse.vorto namespace. 
If you have further questions, please create a new issue.
