### ISSUE TITLE
Processor speed function block

### ISSUE THREAD

**Issue by e-grigorov** [eclipse/vorto#2098]
I am modelling information model similar to [RaspberryPi](https://vorto.eclipse.org/#/details/org.eclipse.vorto.tutorials:RaspberryPi:1.0.0). The issue is that the model should have one function block more: processorSpeed. It seems that there is no such function block or I am missing something?

**Comment by aedelmann** [comment]
You are right. There is no speed functionblock. The raspberry pi could use this speed function block for the processor speed.

**Comment by aedelmann** [comment]
Hi @e-grigorov 
I added you as collaborator for org.eclipse.vorto namespace. You can now create a model there and propose for review.

**Comment by kolotu** [comment]
Hi @e-grigorov 
You have been added as collaborator to the org.eclipse.vorto namespace. 
If you have further questions, please create a new issue.
