### ISSUE TITLE
DeviceInformation function block supports only one software version

### ISSUE THREAD

**Issue by e-grigorov** [eclipse/vorto#2099]
I am using DeviceInformation function block on a device where different software packages are supported:
- OS
- Java
- App Framework

Currently, DeviceInformation supports only one softwareVersion property and it's not clear which is the software package. I would suggest an extension to this function block where multiple software packages are covered with some more details like name, version, vendor etc.

**Comment by aedelmann** [comment]
Similar to my comment to your other request properties you can add these to a new version of this function block. I will add u as a collaborator yo Vorto namespace. :)

**Comment by aedelmann** [comment]
Hi @e-grigorov 
I added you as collaborator for org.eclipse.vorto namespace. You can now create a model there and propose for review.

**Comment by kolotu** [comment]
@e-grigorov 
You have been added as collaborator to the org.eclipse.vorto namespace. 
If you have further questions, please create a new issue.
