### ISSUE TITLE
DeviceInformation function block should provide device name/model

### ISSUE THREAD

**Issue by e-grigorov** [eclipse/vorto#2100]
The device name/model is a common property used by all vendor. It'll be useful to have it in the DeviceInformation function block.

**Comment by aedelmann** [comment]
Hi @e-grigorov 
I added you as collaborator for org.eclipse.vorto namespace. You can now create a model there and propose for review.

**Comment by kolotu** [comment]
@e-grigorov 
You have been added as collaborator to the org.eclipse.vorto namespace. 
If you have further questions, please create a new issue.
