### ISSUE TITLE
DeviceInformation function block should provide hardware version

### ISSUE THREAD

**Issue by e-grigorov** [eclipse/vorto#2101]
The hardware version is widely used for routers/gateways. Currently, [DeviceInformation](https://vorto.eclipse.org/#/details/org.eclipse.vorto:DeviceInformation:1.0.0) function block provides info about the software version, it seems that it's a good candidate for the hardware version property.

**Comment by kolotu** [comment]
You have been added as collaborator to the org.eclipse.vorto namespace. 
If you have further questions, please create a new issue.
