### ISSUE TITLE
Network interface representation

### ISSUE THREAD

**Issue by e-grigorov** [eclipse/vorto#2103]
Initially, it's more a question than an issue. The tricky part is that I have a device more or less similar to the [RaspberryPi](https://vorto.eclipse.org/#/details/org.eclipse.vorto.tutorials:RaspberryPi:1.0.0). The device has a few network interfaces with their own properties like: name, IP, MAC etc.

The question is: how to model the network interfaces? I would like to express that they are part of my device.

**Comment by kolotu** [comment]
@e-grigorov 
I think the right way to model this, is to create a Function Block called NetworkInterface with IP, MAC, etc as status.

**Comment by e-grigorov** [comment]
@kolotu
Thanks for your reply. Actually, the network interface is a device by itself. I thought that Information Model is an option here. To me, the Function Block is more about the device features.

Is there a plan to define such model in org.eclipse.vorto namespace?

**Comment by kolotu** [comment]
@e-grigorov 
Yes a network interface is a device by itself, but I would say it also defines a generic feature that is the network connectivity. So IMO it would be valid to define it as FunctionBlock that can be used by all InformationModels that have a network interface - I would say there potentially many InformationModels that could use such a FunctionBlock. 
If applied to your use case, your device would be defined as InformationModel and it would use the NetworkInterface FunctionBlock. 

There is no plan on our side to create such a model, but you can create it yourself in the org.eclipse.vorto namespace.

**Comment by kolotu** [comment]
Tentatively closing this. If you need more information, I'll reopen it.
