### ISSUE TITLE
Code Generation Caching

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#2104]
Confirmations:
- Released models (models that do not change) are added as attachment to the model, for faster performance

**Comment by kolotu** [comment]
The Vorto Repository has an API to request a generated Ditto structure for a Vorto model. This API accepts a Vorto model ID. Internally the repository will check, whether the requested model is in state "Released" or "Draft". If it is in state "Released", the Vorto Repository will check, whether a generated Ditto structure for this model already exists in the cache - if it does, it returns the cached structure - if it does not, the Ditto structure for the model will be generated and put into the cache. If the model is in state "Draft", the Ditto structure will always be generated and never cached. 

The generation of the Ditto structure will be implemented in the Eclipse Ditto Generator. Ditto structures of released models will be saved as tagged attachments alongside the model. 

Caching of generation results will only be enabled for released generators. Experimental generators will not use caching.
