### ISSUE TITLE
Enable Validation for all Attachments

### ISSUE THREAD

**Issue by kolotu** [eclipse/vorto#2114]
When an attachment is created, it will only be validated, when it has the tag IMPORTED. Validation of attachments should always be enabled. 

See ModelRepository.java, attachFile()

**Comment by mena-bosch** [comment]
Having a look.

**Comment by mena-bosch** [comment]
Bit of a clarification on this. 

- The validation checks for size and file extension - the latter is: ext, pdf, doc, zip (see repo.attachment.allowed.extension in application.properties)
- The validation takes place _only_ when the attachment is **not** tagged as imported

The salient case when the method is invoked with an "IMPORTED" tag seems to be when importing models with dependencies - however in that case the file passed is the original zip file, so the validation would be successful - see AbstractModelImporter#postProcessImportedModel. 

There might also be another case when copying models from somewhere to somewhere else, as all tags are passed (i.e. it might include the "IMPORTED" for all I know) - however, this looks like it's dealing with already imported attachments, so they can hardly have an invalid extension (unless we decide one day that we want to remove something from the list - hopefully never). 

Other usages seem even safer. 

@aedelmann removing the filtering and PRing this shortly, let me know if you're ok with the reasoning above.

**Comment by mena-bosch** [comment]
PR [here](https://github.com/eclipse/vorto/pull/2156), in the meantime.

**Comment by aedelmann** [comment]
@mena-bosch 
sounds good to me. In the imported use case, the importer plugin takes care of validating the imported file, so it is ok that this use case is not considered in the attachment validation. 

Closing issue.
