### ISSUE TITLE
Integration Tests for Elastic Search functionality in Vorto Repository

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#2132]

**Comment by mena-bosch** [comment]
Working on this one already - will finalize and create a pull request once the bulk of the new feature is deemed acceptable and merged, see [here](https://github.com/eclipse/vorto/pull/2136).

**Comment by mena-bosch** [comment]
Pull request [here](https://github.com/eclipse/vorto/pull/2144) :smiley:

**Comment by aedelmann** [comment]
Hi @mena-bosch 
I leave this issue open, until a fix for travis and Jenkins CI is available. Have you found a solution for this yet ?

**Comment by t-gauss** [comment]
Hi @aedelmann ,
now it fetches the artifact for running an elasticsearch test instance via maven.
