### ISSUE TITLE
FunctionblockModel doesn't support Dictionary as property type

### ISSUE THREAD

**Issue by dprinov** [eclipse/vorto#2143]
When pulling a FunctionblockМodel that contains a property that is a Dictionary

```
              {
                    "attributes": [],
                    "mandatory": true,
                    "name": "installedSoftware",
                    "isMultiple": false,
                    "description": "list of all softwares of this type available on the device. using a map just to ensure search is possible. Use any unique key here",
                    "type": {
                        "key": "STRING",
                        "value": {
                            "name": "SoftwareDescription",
                            "namespace": "org.eclipse.hawkbit",
                            "version": "1.0.0"
                        },
                        "type": "dictionary"
                    },
                    "constraints": [],
                    "stereotypes": []
               }
```

The FunctionblockModel that is being parsed from this JSON contains a ModelProperty
with a wrong type - ModelId (type=null:null:null):

`
ModelProperty [attributes=[], isMandatory=true, name=installedSoftware, isMultiple=false, description=list of all softwares of this type available on the device. using a map just to ensure search is possible. Use any unique key here, type=null:null:null, constraints=[]]]"`

**Comment by dprinov** [comment]
It's a problem in _**org.eclipse.vorto.repository.api.impl.ImplementationBase**_, the Gson instance registers an adapter:
`.registerTypeAdapter(IReferenceType.class, new JsonDeserializer<IReferenceType>() ... `
that doesn't check for DictionaryType.

Maybe something like this in the gson adapter will fix the problem: 
```
if (jsonElement.getAsJsonObject().has("type") && jsonElement.getAsJsonObject().get("type").getAsString().equals("dictionary")) {
                return context.deserialize(jsonElement, DictionaryType.class);
              }
```

**Comment by aedelmann** [comment]
Hi @dprinov 
Thanks for the hint. We will look at it in the next bug fix release
