### ISSUE TITLE
Provide a way to mark an operation as a setter/getter for a particular property

### ISSUE THREAD

**Issue by n-kristev** [eclipse/vorto#216]
At the moment there is no clear relation between an operation which operates as a setter/getter for a particular property, and the actual property, apart from a naming convention like the one used in Java beans. It would be useful to be able to specify that an operation is a setter/getter for a particular property. This could be accomplished with a mechanism similar to the current "with" keyword, which provides some context for an operation:

```
properties {
    mandatory value as int
}

operations {
    changeValue(newValue as int) context {setter:value}
}
```

**Comment by aedelmann** [comment]
I like this idea of bringing context and cross referencing of operations with specific properties, like status or configuration properties.

**Comment by laverman** [comment]
I was wondering if this functionality isn't already there? Currently it is already possible to create properties and mark them as *readable*, *writable* or *eventable*.
The provided example could therefore be modeled:

```
properties {
    mandatory value as int with {writable: true}
}
```

I agree, that the setter method is not explicitly given. However, is this really necessary?

**Comment by n-kristev** [comment]
I agree that the readable/writable/eventable probably cover the majority of use cases for the code generators. But having the option to declare that an operation is a setter/getter for a property provides the additional flexibility (admittedly, very rarely needed) to have a getter/setter operation which does not follow the getX()/setX() naming convention.

**Comment by aedelmann** [comment]
Status has the semantics of readonly by default. Which means, a generator can automatically generate a getter method for this property. Configuration properties are readable and writeable (by default) which would translate into a getter and setter. 

Operations have a different semantics and provide course grained device functionality to execute certain logic on the device, that have only an indirect link to the properties defined in the FB. In this case, IMO, it does not make sense to add getter:setter on operation level.

**Comment by e-grigorov** [comment]
The point is that some getters don't follow getX convention. For example, what could be the getter of this boolean property: mandatory active as boolean?
Is it isActive or getActive?

Custom getters/setters can be helpful in such scenarios.

**Comment by kolotu** [comment]
@e-grigorov 
If you refer to the Java Beans specification there is only one valid option for a getter of a boolean property: 
`public boolean is<PropertyName>();
`
https://download.oracle.com/otndocs/jcp/7224-javabeans-1.01-fr-spec-oth-JSpec/

I don't see the necessity to model custom getters/setters in a Vorto model, as they do not add semantic information.
