### ISSUE TITLE
A way to add more documentation to Function blocks

### ISSUE THREAD

**Issue by n-kristev** [eclipse/vorto#217]
Currently, the only way to document a Function block is through the block's description, and then through properties/operation descriptions. However, this is not always enough - using Java and Javadoc, for example, there is no information about operation parameters or error conditions. It would be good to be able to have more detailed documentation on the Function block and the behaviour of its components.

**Comment by Ebolon** [comment]
Seems like this issue has already been resolved. I can use java comments everywhere.

Function block inherits from Datatype:
`grammar org.eclipse.vorto.editor.functionblock.Functionblock with org.eclipse.vorto.editor.datatype.Datatype`

Datatype from Terminals:
`grammar org.eclipse.vorto.editor.datatype.Datatype with org.eclipse.xtext.common.Terminals`

In the terminal rules there are already expressions for java comments included.

**Comment by n-kristev** [comment]
Agreed, with the current Function Block DSL  syntax all of the use cases I described in the issue are covered. Closing the issue as resolved.
