### ISSUE TITLE
An option to provide error conditions for operations

### ISSUE THREAD

**Issue by n-kristev** [eclipse/vorto#219]
Currently, there is no way to specify possible erroneous outcomes from executing operations inside Function blocks. Programming languages have different ways for handling this: a Java or C# program would define a set of Exceptions which can be thrown from the method execution; a C program would provide the error codes to be checked against errno, etc...
I think a possible option is to have an error condition marker for an operation, and then a language-specific mapping which would describe what the possible error conditions are in a way which will be understandable by code generators.

**Comment by aedelmann** [comment]
Hi Nikolaj, 
great idea. It is just a matter about the details the DSL ought to be exposing when it comes to errors of an operation. 
{code}
   operations {
       op(value as int) returns error // error is a keyword indicating that op might return an error
       anotherOp() returns string, error // op might return an ordinary result but also an error
   }
{code}

{code}
   operations {
       op(value as int) returns error with {errorDetail: Error.Too_High}
   }
{code}
