### ISSUE TITLE
Namespace owner usernames are not sorted

### ISSUE THREAD

**Issue by mena-bosch** [eclipse/vorto#2191]
This is at best a marginally cosmetic issue. 

In the `manage` section, the owners of a given namespace are listed, but not sorted (e.g. alphabetically or lexicographically). 

For a namespace with enough owners, this can be a little ugly. 

E.g.:
![Screenshot from 2019-12-23 14-36-02](https://user-images.githubusercontent.com/56636716/71360888-93e58680-2591-11ea-8811-b98c6d2ceb28.png)

**Comment by mena-bosch** [comment]
PR [here](https://github.com/eclipse/vorto/pull/2200).

**Comment by mena-bosch** [comment]
And looking like this now:

![better](https://user-images.githubusercontent.com/56636716/71968476-4c9ffc80-3205-11ea-9939-9a559d30174d.png)

**Comment by kolotu** [comment]
@mena-bosch  this issue is complete with your merged PR, right?

**Comment by mena-bosch** [comment]
> @mena-bosch this issue is complete with your merged PR, right?

Indeed, thanks.
