### ISSUE TITLE
Describing data types where all properties are optional, but at least one must be present

### ISSUE THREAD

**Issue by n-kristev** [eclipse/vorto#220]
A short example to visualise the point. There is a datatype describing a possible value range:

```
entity TemperatureRange {
    optional min as Temperature
    optional max as Temperature
    optional multiple possibleValues as Temperature
}
```

in could be that the range is only limited from above, or only from below. It is also possible to have the range limited to several discreet values, thus all of the properties are optional. However, in this scenario, at least one of the properties must be present, otherwise the range does not make sense. 
How could one describe such an entity in Vorto?

**Comment by aedelmann** [comment]
An entity referencing another entity cannot define constraints.
You can model your entity by using the Vorto built-in constraints for setting min and max values, for example:
{code}
optional temperature as int <MIN 0, MAX 30>
{code}
If you whatever reason wanna create your own range entity, you can define it like:
{code}
entity TemperatureRange {
    optional min as int <MIN 0>
    optional max as int <MAX 30>
}
{code}
As said, referenced entities cannot define constraints , only primitive types. That is why i changed your Temperature entity to int primitive.

**Comment by n-kristev** [comment]
The issue is not about defining constraints for a property inside a datatype, apologies if I have not described it clearly enough.
My use case is the following: there is a datatype that has several properties. Each one of these properties is optional, it can be present or missing. However, at least one of these property MUST be set for the datatype instance to be valid. Currently I could not find a way to describe this in Vorto. Using your example:
````
entity TemperatureRange {
  optional min as int
  optional max as int
}
````
In my model, a range defined like this must have either lower bound, upper bound, or both. However, since the model allows both properties to be optional, it is possible to have a TemperatureRange instance where neither is set, and there is no way to tell the code generator that it needs to make some additional checks on the data.

**Comment by aedelmann** [comment]
Interesting. So it is similiar like a XSD choice element, I assume? How should the DSL ideally look like in this case?

**Comment by n-kristev** [comment]
Hmm, I am not really sure how something like this could be represented either. A possible option could be to be able have subsets of properties inside the datatype definition, and provide some metadata for the entire subset. But this has the potential to become quite ugly and complicated.

**Comment by aedelmann** [comment]
Solved this issue by introducing a oneOf element 
Example:
`oneOf {
  option1 as int
  option2 as int
} `
