### ISSUE TITLE
Add proxy authentication support in java repository client

### ISSUE THREAD

**Issue by desislava-marinova** [eclipse/vorto#2203]
When building Repository Client (using 
`org.eclipse.vorto.repository.client.RepositoryClientBuilder`) only `proxyHost` and `proxyPort` could be configured, but sometimes proxy authentication is needed.
Add support for `proxyUsername` and `proxyPassword` configuration also.

**Comment by kolotu** [comment]
Hi @desislava-marinova, 
thanks for opening this issue. 
Proxy authentication for the java client has been implemented. It is already available in our development branch.
This feature will be included in the next release after 0.13.0, since that one is already built.

**Comment by desislava-marinova** [comment]
@kolotu , thank you!  Is there any presumable date/time-frame for the next release?

**Comment by kolotu** [comment]
@desislava-marinova we have not yet planned the scope the next release, so there is no date yet. But we will announce it, as soon as it is planned.
