### ISSUE TITLE
bug: concurrent running of ElasticSearch tests may produce interferences due to same ports in use

### ISSUE THREAD

**Issue by mena-bosch** [eclipse/vorto#2217]
This is a speculative resolution for a problem we have noticed only recently. 

One (or more) of the integration tests for ElasticSearch was failing to reindex a model when during the build on the Jenkins side, showing a socket timeout exception. 

Given how those tests work (an ES runtime is launched by Allegro on specific ports), I suspect that multiple concurrent builds testing the ES integration tests at the same time might actually be stepping on each others' feet, when the build processes are not isolated. 

I will try and randomize the ports used to spin the service with the following rules:

* must be 4 digit ports
* must not be the production ES ports, or other obvious entries

Hopefully this will limit the collisions well enough for the use case.

**Comment by mena-bosch** [comment]
PR [here](https://github.com/eclipse/vorto/pull/2218).
Local tests doing good - hopefully no surprise upstream.

**Comment by mena-bosch** [comment]
Looks like this solved _one_ problem, aka the socket timeouts, but still does not allow multiple non-isolated builds running the ElasticSearch tests concurrently - maybe it's just a limitation on Allegro's side...
Working with @t-gauss to see if we can't force throttling builds. 

Not sure what could be an alternative solution should that fail, save for disabling those tests (which does not sound like a great idea).

**Comment by t-gauss** [comment]
Hi @mena-bosch ,
being still a newbie in this topic I guess adding disableConcurrentBuilds() in the options block of the jenkinsfile could help as a temporary workaround.

**Comment by t-gauss** [comment]
Hi @mena-bosch ,
did the change and ran the tests locally before commit. Even there I got a timeout 
`Tests in error: 
  org.eclipse.vorto.repository.search.TypeSearchSimpleTest: Failed to start elasticsearch within time-out
  org.eclipse.vorto.repository.search.TypeSearchSimpleTest
`
Will look into it.

**Comment by t-gauss** [comment]
PR [here](https://github.com/eclipse/vorto/pull/2224).

**Comment by mena-bosch** [comment]
Thanks @t-gauss . This one was merged by @kolotu now so closing.
