### ISSUE TITLE
A Vorto primitive for map structure

### ISSUE THREAD

**Issue by n-kristev** [eclipse/vorto#222]
Map structures (sets of key/value pairs) are very common both in programming and in describing IoT devices. Vorto already has a sort of primitive for the other most commonly used data structire (list/array) with `multiple`. It would be convenient if Vorto provides a primitive for map structures as well.

**Comment by aedelmann** [comment]
DSL Proposal:
{code}
mandatory prop as Dictionary<int,string> // valid dictionary with type constraints
mandatory prop as Dictionary // valid dictionary without constraints 
{code}

**Comment by erlemantos** [comment]
I'm taking this ..
