### ISSUE TITLE
Creation of Mapping Models not possible anymore

### ISSUE THREAD

**Issue by laverman** [eclipse/vorto#223]
**Goal:**
*Create a mapping model for an existing Function Block Model*

**What are the steps taken**
Right-click on the existing Function Block Model -> `New Mapping Model`. The mapping model wizard appears. 

**Expected Behaviour**
After filling out all the required fields the `OK` button is enabled, and the model can be created by clicking on it

**Actual Behaviour**
The `OK` button is greyed out.

**Comment by erlemantos** [comment]
I'll take this
