### ISSUE TITLE
Visual feedback for Vorto Repository connection data in Eclipse preferences

### ISSUE THREAD

**Issue by laverman** [eclipse/vorto#224]
**Goal:** Enter URL and user credentials for the Vorto Informationmodel repository in Eclipse preferences.

**Steps taken**
Open `Window->Preferences->Vorto->Information Model Repository` and enter _URL_, _User_ and _Password_.

**After implementing**
The IDE provides visual feedback regarding the entered data. This could be done in two steps. A first step would check if the URL is correct and leads to the online repository. In a second step the user credentials are checked and confirmed.

**Comment by aedelmann** [comment]
Eclipse Toolset not supported any longer
