### ISSUE TITLE
Xtend template doesn't seem to compile

### ISSUE THREAD

**Issue by philbuettner** [eclipse/vorto#2260]
The PRs (#2170, #2111, #2054, #1964) I made on the OpenAPI Template (https://github.com/eclipse/vorto/blob/0.12.6/generators/generator-openapi/src/main/java/org/eclipse/vorto/codegen/openapi/templates/OpenAPITemplate.xtend) are merged in development, master, 0.12.5 and 0.12.6 but not reflected in production. 

It seems that the xtend template does not compile and therefore does not update.

**Comment by t-gauss** [comment]
Hi. I think it compiles. Problem is that the generator lambda running in production is old (4 Month). We will let you know as soon as its updated.

**Comment by t-gauss** [comment]
Hi @philbuettner .
@kolotu updated the generators on prod. Your changes should be reflected now.
