### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [eclipse/vorto#2275]
Hello Eclipse Vorto team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477).

If you are interested that the Eclipse Vorto project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>

```
We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by kolotu** [comment]
Hello @miklossy, thanks for letting us know - we are very interested in being mentioned on the Xtext community website. We will provide the information next week.

**Comment by kolotu** [comment]
@miklossy please find the information about the Vorto project below: 

```
<tr>

	<td><a href="https://www.eclipse.org/vorto/">Eclipse Vorto</a></td>

	<td>Eclipse Vorto offers a language to describe semantic models of digital twins, a repository to manage the semantic models, plugins to generate code or API documentation and payload mapping for telemetry data.</td>

	<td>Eclipse Public License v 2.0</td>

	<td>IoT, Language, Device Abstraction, Repository</td>

	<td>Alexander Edelmann, Menahem Raccah Lisei, Kevin Olotu, Somesh Kumar, Tobias Gauss, et al.</td>

</tr>
```

**Comment by miklossy** [comment]
Thank you @kolotu for providing the necessary information!

**Comment by miklossy** [comment]
The `Eclipse Vorto` project has been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).

**Comment by kolotu** [comment]
@miklossy  very cool - thanks!
