### ISSUE TITLE
refactory: temporarily rename the api/v1/namespaces resource path in the new Namespacecontroller

### ISSUE THREAD

**Issue by mena-bosch** [eclipse/vorto#2276]
The new `NamespaceController` is mapped to the `api/v1/namespaces` path, but presently not used by the UI (the path is only referenced in tests). 

This controller is not yet in production, but it would be released with 0.13. 

Since one of the concepts behind #2152 is to refactor everything "tenant" to "namespace", the controller will ultimately yield all namespace-related functionality. 

However for now, we do not want to commit to an official api and therefore, would rather change the path to `/rest/namespaces...`. 

If we release the controller as is, we will not be formally able to rollback. 

Better then to have it released in 0.13 with the mapping changed back to `/rest/namespaces` (no collision expected, even with other backup/restore/etc. mappings that are already using `namespaces` in their path). 

The task itself is trivial (one-liner change in the new controller, then some find-replace in tests). 

The implication are nil for now, since it's neither in use by the UI, nor has it been released yet. 

Ultimately after all tenant to namespace change are tested and validated, we can consider changing back every namespace-related mapping to `/api/v1`. 

This task should go to the 0.13 release once finalized.

**Comment by mena-bosch** [comment]
PR [here](https://github.com/eclipse/vorto/pull/2277).

**Comment by kolotu** [comment]
Cherry-picked the commit into the release branch.
