### ISSUE TITLE
Dialogue to request access to namespaces

### ISSUE THREAD

**Issue by kolotu** [eclipse/vorto#2291]
Vorto offers a dialogue to request access to namespaces for Oauth clients. 

This dialogue receives the Oauth client ID, Oauth issuer and client name as (URL-) parameters.

The dialogue offers a list of all visible namespaces (excluding vorto.private.* namespaces) and a login to include namespaces that are private and filter those that do not contain any visible models for the user. 

The user can select one or more namespaces. 

Emails will be generated to the owners of the selected namespaces. The emails contain the requested namespace, the Oauth client ID, Oauth issuer and client name.

**Comment by mena-bosch** [comment]
After discussion:

1. figure out where to request access to a namespace in the application
2. build the relevant form that pre-filters namespaces with models you can see AND owners who have email set up (with a disclaimer that if the namespace isn't there, then the owner should be contacted directly)
3. build the email sending process with a Vorto template


* follow up task 1: would be to warn folks that they need to set up their email if they want people to be able to request access to their namespaces
* follow up task 2: for not logged on users the user could put their OAuth client id manually in the form, similarly to the add technical user modal

**Comment by mena-bosch** [comment]
The work on #2288 could be repurposed to support this, with some button next to the filter that would allow searching namespaces beyond the current user's access and request access.

**Comment by mena-bosch** [comment]
Did not end up "integrating" with #2288, although the namespace management view has undercome a small re-design. 

Bulk of the work finalized. 
Remaining TO-DOs:

1. Wait until PR processed
2. Merge to dev
3. Test e-mail props and config work in dev
4. Add user subject to e-mail template (will help with technical user identification for the sake of the namespace managers notified)

**Comment by mena-bosch** [comment]
This is now feature-complete and will soon be merged to the dev branch. 
Highlights include: 

- Feature available through new button in "manage" toolbar, which has also been re-styled with a better button layout and overlay progress indicators for the occasion
- Allows searching for target namespace (min 4 characters)
- Can request access for oneself, or any existing technical user (min 3 characters - length limitation has been reduced by one globally and also impacts search when adding users to namespace)
- Sends subject if any, alongside username, in the e-mail to namespace administrator(s)
- Requires acknowledgement of sharing username (and subject if applicable) with NS administrator(s)
- Provides relevant error messages in case something went wrong, e.g. no administrator have an e-mail address set up, something went wrong with e-mail at connection or session level, etc.
- Shares as little personal data as possible, and offers administrators a chance to contact Vorto team in case of perceived abuse
- Barebones SMTP configuration in dev environment, pending resolution of domain-related decisions and subsequent verification with AWS for a production-grade SMTP server
