### ISSUE TITLE
Documentation URLs should start with https

### ISSUE THREAD

**Issue by Ineskouka** [eclipse/vorto#2297]
The documentation for the Bosch IoT Suite generator contains example requests that have incorrect URLs. They should start with https instead of http.
Links:
https://github.com/eclipse/vorto/blob/master/generators/generator-eclipsehono/Readme.md
https://github.com/eclipse/vorto/blob/master/generators/generator-eclipseditto/Readme.md

**Comment by Ineskouka** [comment]
I can fix This Issue.

**Comment by kolotu** [comment]
PR is merged.
