### ISSUE TITLE
Display a validation error message in the technical user dialogue

### ISSUE THREAD

**Issue by kolotu** [eclipse/vorto#2298]
When there is a validation error, an error message must be displayed that contains the validation rules. 

Follow up after #2208.

**Comment by mena-bosch** [comment]
The lack of validation message is likely due to my lack of enthusiasm for the original validation, which I set to simply 4+ alnum. 
Will add the error message with that same validation for now - hopefully we can fine-tune in the future.

**Comment by mena-bosch** [comment]
![image](https://user-images.githubusercontent.com/56636716/75036365-fbe11c00-54b1-11ea-873a-8aec80bee46e.png)
PR [here](https://github.com/eclipse/vorto/pull/2307).

**Comment by mena-bosch** [comment]
PR merged last week.
