### ISSUE TITLE
Create a WoT TDT Generator

### ISSUE THREAD

**Issue by kolotu** [eclipse/vorto#2344]
Create a generator that converts a Vorto Information Model into a Web of Things Thing Description Template (Specification here: https://www.w3.org/TR/wot-thing-description/#thing-templates).

**Comment by kolotu** [comment]
Also consider evaluating additional parameters (like protocol binding) as mentioned here: https://github.com/w3c/wot-discovery/issues/13

**Comment by kolotu** [comment]
Implementation currently on this branch: https://github.com/bosch-io/vorto/tree/webofthings_generator_no_lib

**Comment by kolotu** [comment]
Use own namespace "vorto.eclipse.org" in TDTs

**Comment by kolotu** [comment]
Leaving the generator in its current state, until needed.

**Comment by oscarfh** [comment]
@kolotu Any chances this gets merged to the mainstream or that the generator is provided as an external lib?

**Comment by kolotu** [comment]
@oscarfh it's currently not planned to merge it in its current state, since it generates only a partial TDT. WoT is currently introducing a new standard called Thing Model, which is conceptually more aligned with Vorto models, hence we want to wait for that standard to be finalized and then adapt the generator to use the Thing Model.

**Comment by oscarfh** [comment]
Ok, nice to know, thanks a lot!
