### ISSUE TITLE
Respect Functionblock Hierarchy in Ditto JSON Generator

### ISSUE THREAD

**Issue by t-gauss** [eclipse/vorto#2374]
Thanks @thjaeckle  for reporting this and providing an example:

> When using inheritance in Vorto Functionblocks, Ditto relies on that all Functionblocks in the hierarchy are added to the "definition" array, the first entry being the direct type.
> For example given that you have 3 functionblocks extending each other:

```
functionblock ColoredLamp extends Lamp {
...
}
functionblock Lamp extends Switchable {
...
}
functionblock Switchable {
...
}
```

> And a Ditto Feature "my-colored-lamp" shall follow the "ColoredLamp" definition.
> Then this must look like:

```
{
  "thingId": "foo:bar",
  "policyId": "foo:bar",
  "features": {
    "my-colored-lamp": {
      "definition": [
        "org.eclipse.vorto:ColoredLamp:1.0.0",
        "org.eclipse.vorto:Lamp:1.0.0",
        "org.eclipse.vorto:Switchable:1.0.0"
       ],
       "properties": {
          ... whatever ...
        }
     }
  }
}
```

> What is important is that "ColoredLamp" is the first entry (e.g. Developer Console relies on that in order to identify the actual followed type).
> 
> This "flattening" of the inheritance hierarchy is needed by Ditto because otherwise Ditto won't be able to search for all features which implement the "org.eclipse.vorto:Switchable:1.0.0" functionblock.
>

**Comment by t-gauss** [comment]
I think we need a mechanism to clean the generator "caches". Otherwise the changes will not become visible for existing models/functionblocks. @kolotu , @mena-bosch WDYT?

**Comment by kolotu** [comment]
@t-gauss  @mena-bosch  
The idea was that the generator version changes, whenever there is a change in the implementation. However since we use 1.0.0-SNAPSHOT this will no longer work. 
So this mechanism could be a good idea IMO.
