### ISSUE TITLE
Update Elasticsearch to version 6.8.8

### ISSUE THREAD

**Issue by kolotu** [eclipse/vorto#2377]

**Comment by mena-bosch** [comment]
Issue probably not impacting Vorto but some due diligence remains - plus it's not a bad idea to upgrade.

**Comment by mena-bosch** [comment]
PR [here](https://github.com/eclipse/vorto/pull/2378). 
Depends on CQs for ES 6.8.8 and Lucene 7.7.2. 
ES upgraded on AWS to 6.8 for dev. 
Will have to:

- Wait for CQs
- Once merged in dev, upgrade to ES 6.8 on prod instance too
- Deploy to prod

**Comment by mena-bosch** [comment]
CQ resolved and upgrade merged in dev back then.
