### ISSUE TITLE
Local generator execution using SAM-cli always returns base64 encoded String

### ISSUE THREAD

**Issue by t-gauss** [eclipse/vorto#2386]
When you try to execute the generators locally using the sam cli, the generator result is always base64 encoded which is not very convenient (you need to manually decode it). The local execution and execution in AWS should behave the same.

**Comment by t-gauss** [comment]
Please assign this to me.

**Comment by kolotu** [comment]
@t-gauss I think this can be configured on the API Gateway. I haven't figured out the correct setting though. 
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings-workflow.html

**Comment by t-gauss** [comment]
Hi @kolotu .
It took a while but I did:
`"Globals": {
    "Api" : {
      "BinaryMediaTypes" : ["*~1*"]
    }
  },`

Wanted to add this to the corresponding template.

**Comment by kolotu** [comment]
@t-gauss looks good to me! thanks!

**Comment by t-gauss** [comment]
PR [here](https://github.com/eclipse/vorto/pull/2388) .
