### ISSUE TITLE
Reserved words cannot be part of the namespace

### ISSUE THREAD

**Issue by kolotu** [eclipse/vorto#2402]
Currently reserved words like "status" or "fault" cannot be part of a namespace name.
It needs to be decided whether to allow the usage or it must be prominently documented that this is not permitted (similar to #2382). 
Error messages must be displayed in case the user enters an invalid namespace name (see also #2394).

**Comment by gruetter** [comment]
I would strongly suggest to **allow** _fault_, as it has a specific semantic meaning and should not be replace with something like _error_ or _failure_. Remember: a _defect_ can lead to a _fault_ which can cause a _failure_ - all three very distinct things.

**Comment by kolotu** [comment]
Allowing as many keywords in namespaces as possible by the grammar.
'fault', 'status', 'events', 'operations', 'breakable', 'category', 'configuration',  'description' will be allowed.

'dateTime', 'functionblocks', 'infomodel', 'mandatory', 'namespace', 'optional', 'version', 'dictionary', 'extension', 'functionblock' will remain forbidden - allowing those keywords would make parsing the DSL impossible.

**Comment by kolotu** [comment]
Actually dateTime is fine to use in the repository, since it automatically lowercases all namespaces.
