### ISSUE TITLE
Add a "createdBy" field to the user table

### ISSUE THREAD

**Issue by mena-bosch** [eclipse/vorto#2503]
The field would reference the username of the user if they went through the human process of signing up, or the "parent" user if this is a technical user, programmatically created by another user. 
This would allow:

- The _possibility_ to chain-delete technical users by a user who is deleting their account (might cause more damage than it solves)
- Some tracking capability, e.g. if ever any abuse of ToS is perpetrated by a technical user, the human person responsible is the user referenced by "createdBy"

This seems a bit over-engineered, but I don't really like the "legal void" around creating puppet users with no bound acknowledgement of the ToS and privacy policy. 

A lighter approach would be to display a disclaimer with the usual checkbox for users creating technical users, but without the "createdBy" field, no actual abuse would be trackable (as unrealistic as the occurrence would seem).

**Comment by mena-bosch** [comment]
@t-gauss @kolotu thoughts? Maybe I'm just being paranoid...

**Comment by kolotu** [comment]
I think this would be a good addition, to create a link between human users and technical users acting on their behalf.

**Comment by mena-bosch** [comment]
**Digression**

I implemented a gate in the process of creating a technical user on the fly with the "request access to namespace" form (in its standalone, parametrized version - currently the only operation mode allowing on the fly tech user creation). 
Essentially it's an additional check box asking the authenticated user to acknowledge that the ToS and privacy policy apply to their user as well as to the technical user they are about to create. 
I think I should add this in the "give access to namespace" form as well (need to find shorter names for those forms).
Further more, when the versions of the request form that do not feature yet creating a technical user are changed by #2460 (which would enable e.g. the modal request form to provide with tech user creation), the same checkbox should be in place. 
Will create an ad-hoc issue for that.

Even with this additional step in place when ever a user is allowed to create a technical user, I would still justify this "createdBy" field as an additional safety in case something goes wrong.

**Comment by kolotu** [comment]
Aside from the legal aspect, it could also be helpful for managing technical users, to have the link to it's creator.

**Comment by mena-bosch** [comment]
> Aside from the legal aspect, it could also be helpful for managing technical users, to have the link to its creator.

Yup that's what I meant by "The possibility to chain-delete technical users by a user who is deleting their account", although I expect there might be less dangerous / more useful functionalities to be devised out there.

**Comment by mena-bosch** [comment]
Notes after discussion:

- make the field non-nullable and refer to user id rather than username
- while migrating, pre-populate current data with self-references (aka we will "assume" that existing technical users just created themselves), and the application for this will only concern future technical users

**Comment by mena-bosch** [comment]
There is another quite important reason to implement this task, that just came to my mind: while the creation of technical users takes place in the UI by design, there is nothing preventing an observing user from figuring out the REST call in use to create technical users, and automating the creation of any given number of technical users. 

As we do not have access logs, an authenticated user could virtually create 1, 24, 24k or whatever number of technical users per [insert time unit here], thus saturating the Vorto tables and potentially causing the repository to malfunction. 

The `createdBy` field could be used to implement a **quota** of technical users per human user, similar to the one we have in place for private namespaces. 

I think this is worth pushing the priority for this task @kolotu way up.

**Comment by mena-bosch** [comment]
After discussion: the non-null constraint is too tricky to apply. 
If we applied it, we'd need to lock the user table when new users sign up to Vorto, since instead of a transparent insert we'd need to specify the created_by id of a new user to be the last ID in the table + 1. 
We can still leave the constraint to an existing user ID but make it nullable, and add the relevant defensive code to ensure that if null, the created_by for any given user is to be interpreted as the user's own id ("created themselves"). 
We can also add an update right after inserting a new user contextually to a human sign up, so the created_by is assigned the generated user ID.

**Comment by mena-bosch** [comment]
Base task done and merged to dev. 
Follow-up tasks created  - see links above.
