### ISSUE TITLE
Example Code Generators

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#251]
Describes what the purpose of the generator is and what it generates. 

This documentation issue deals with all generators currently available as example code generators.

**Comment by MichaelGuenther** [comment]
Alex,
which details should be described per generator and where can I get the necessary information from?
Michael

**Comment by aedelmann** [comment]
Hi Michael. 
You can find Some documentation here
https://github.com/eclipse/vorto/blob/development/server/generators/Readme.md

**Comment by MichaelGuenther** [comment]
Hi Alex,
to keep consistent and minimize text maintenance, what about linking from a (new) documentation page to the Readme.md of the particular generator (just like in [https://github.com/eclipse/vorto/blob/development/server/generators/Readme.md](https://github.com/eclipse/vorto/blob/development/server/generators/Readme.md))?

**Comment by MichaelGuenther** [comment]
Alex,
as we discussed, I've made a documentation page on Example Code Generators provided by Vorto with a link to [https://github.com/eclipse/vorto/blob/**master**/server/generators/Readme.md](https://github.com/eclipse/vorto/blob/master/server/generators/Readme.md). Furthermore, I've re-arranged the section's structure and, thus, the sub menu of the **Code Generator** menu item.
