### ISSUE TITLE
Enabling Eclipse as an authentication provider alongside GitHub makes usernames potentially non-unique and potentially breaks access control

### ISSUE THREAD

**Issue by mena-bosch** [eclipse/vorto#2529]
Before enabling authentication with Eclipse as a provider (see #2330), the only OAuth provider that used arbitrary usernames was Github (Bosch providers use UIDs in some form or another). 

The user table has been designed with no user name uniqueness in mind originally, although it actually *had* unique usernames,  since none of the OAuth providers supported would "step on each other's toes" in that regard.

The lack of uniqueness restriction on one end, and the fact that there can be two identical usernames belonging to two different users on the other has the potential to break access control entirely throughout the application. 

There are two alternative solutions to this, and an immediate workaround:

- **Solution 1**: enforce usernames unique. This would require less changes in the code base or DDL, but prevent sign up of users whose username matches another user. It would also leverage the authentication provider we persist when any user signs up, to restrict access to only that username + authentication provider association. 
- **Solution 2**: re-write every bit of authorization code based on username only, since a repository search by username would no longer be sufficient to identify the right entity. Any former authorization call that only resolves the user by username would now check for their authentication provider as well. This is much more work potentially, but would produce safer code in the end. 
- **Immediate workaround**: disable authentication through Eclipse for now, as it's the newest provider and still has few to no users in dev (none in prod since it hasn't been deployed there).

**Comment by JulianFeinauer** [comment]
@mena-bosch shouldnt it be possible to distinguish between an id which is prefix + username like "eclipse:j.feinauer@..." or "github:j.feinauer@..." and the name itself which is just the id without the prefix (would be "j.feinauer@..." in both cases but doesnt matter there.
Shouldnt this be doable without too much change in the application?

**Comment by kolotu** [comment]
The original implementation of SuiteAuth used the "sub" field of the token as user ID to create/identify the Vorto user - this has now been changed to use the "ext/orig_id/sub" field, which contains a CIAM Bosch ID (S-***), so when you login, you will retrieve your Bosch ID user. This behaviour (retrieving a user from a potentially different authentication provider, was considered a bug in the context of Github/Eclipse, but is the desired behaviour for Bosch ID/ SuiteAuth. This needs to be considered, when addressing the Github/Eclipse issue.
