### ISSUE TITLE
Update DSL Grammar

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#253]
Additional grammar elements:

- Constraints defintion for operation params & return type
- Documentation of operation params
- Measurement Unit
- new breakable keyword for operation to indicate errors
- Dictionary object type

**Comment by erlemantos** [comment]
I'll take this

**Comment by MichaelGuenther** [comment]
Hi Erle Czar,
can you trigger me when you have finished your work, so I can update the DSL grammar documentation section(s) from editorial point of view? I propose you to push your working branch, so I can work on it. At the end, I'll trigger you to push the branch and make the pull request.

**Comment by erlemantos** [comment]
Hi Michael,
I sent you the markdown files via email.

**Comment by erlemantos** [comment]
Committed now, and pull-requested.

**Comment by MichaelGuenther** [comment]
Hi @erlemantos and  @aedelmann.
where can I get the complete generated Vorto DSL definition from? I need it for updating the current outdated documentation (Appendix: Model DSL Reference) because I guess there are some additional changes beyond your latest in the **253_Updates_On_DSL_Grammar** branch. And are there any syntax descriptions/hints from you or your colleagues on any wiki sites or so?
Michael

**Comment by erlemantos** [comment]
For Datatype --
_bundles/org.eclipse.vorto.editor.datatype/src/org/eclipse/vorto/editor/datatype/Datatype.xtext_

For Functionblocks --
_bundles/org.eclipse.vorto.editor.functionblock/src/org/eclipse/vorto/editor/functionblock/Functionblock.xtext_

For Information Models --
_bundles/org.eclipse.vorto.editor.infomodel/src/org/eclipse/vorto/editor/infomodel/InformationModel.xtext_

For Mapping --
_bundles/org.eclipse.vorto.editor.mapping/src/org/eclipse/vorto/editor/mapping/Mapping.xtext_

**Comment by MichaelGuenther** [comment]
@erlemantos, what is the tool of your choice to convert xtext to NF? I could install it and do the converting by myself...

**Comment by erlemantos** [comment]
I don't know of any tool to do it automatically. I'll update it.

**Comment by MichaelGuenther** [comment]
You're doing it by hand?!?

**Comment by erlemantos** [comment]
Yes. :D It's not too tedious.

**Comment by erlemantos** [comment]
Btw, I've already modified the appendix to include the changes we made to the DSL.
