### ISSUE TITLE
Vorto CLI Tool

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#254]
1) Introduction to the CLI tool
2) Examples, e.g search for models, invoking code generators

**Comment by nagavijays** [comment]
Will take up this issue.

**Comment by aedelmann** [comment]
Great, Vijay. A documentation about the current CLI tool already exists. In this issue, we would need to verify if the explanation there is uptodate.

**Comment by nagavijays** [comment]
Yes. Thats right. Will improve and modify (if necessary) the existing documentation available at http://www.eclipse.org/vorto/documentation/vorto-repository/cli-tool/cli-tool.html. 

I noticed that the documentation is targeted mainly for Windows. Should we include notes for Mac/Linux as well??? Or the users derive it themselves?

**Comment by aedelmann** [comment]
Good point. I think we should mention the other supported platforms as well.
