### ISSUE TITLE
Performance issues with model loading

### ISSUE THREAD

**Issue by kolotu** [eclipse/vorto#2559]
Currently loading a model is significantly slower on DEV than it is on PROD. 
The main reason seems to be related to loading the model's dependencies and usages - to resolve the usages all namespaces (i.e. modeshape workspaces) are being searched, by logging into them and querying them. The more namespaces there are and the more access rights the current user has, the longer this operation will take. 

For anonymous users, this doesn't seem to be a problem - anonymous access to models is reasonably fast. 

There are multiple angles to tackling the issue: 

1. Reducing the workspaces that are being searched (i.e. ignoring private workspaces for non-sysadmin users): https://github.com/eclipse/vorto/pull/2557
2. Improving the operation itself (role/permission handling) through different/more caching or a more efficient implementation

Another aspect are sub-namespaces - currently sub-namespaces are resolved by loading all namespaces and then iterating until the owner-namespace is found. 
A different approach could be splitting the namespace into its pieces and trying to resolve them step-by-step (i.e. org.eclipse.vorto.sub: try org, then org.eclipse, then org.eclipse.vorto)
Another - more sophisticated - approach would be to use a fulltext index on the namespace name column to search by similarity - this only requires a single DB query to resolve a subnamespace. 

Test scenario: 
Local environment with data from dev. Loading times are measured in seconds.

| |PMSMotor|Temperature| WasherWAT286H8SG|PowerState|
|---|---|---|---|---|
|Prod instance regular user| 2 | 3 | 2 | 8 | 
|Prod instance sysadmin user| 4 | 4 | 2 | 8 | 
|Dev instance regular user| 8 | 9 | 8 | 16 | 
|Dev instance sysadmin user| 13 | 38 | 11 | 35 | 
|Local improved dependency handling regular user | 2 | 2 | 1.5 | 4 | 
|Local improved dependency handling sysadmin user | 12 | 18 | 12 | 28 | 
|Local fulltext index regular user | 10 | 17 | 10 | 25 | 
|Local fulltext index sysadmin user | 10 | 14 | 10 | 40 | 
|Local fulltext index sysadmin user more caching | 8 | 13 | 9 | 20 | 
|Local fulltext index regular user more caching | 8 | 13 | 9 | 22 |

**Comment by mena-bosch** [comment]
Quite a few topics here have been optimized I think: 

- #2557 is closed
- Other optimization tasks are closed except for #2610 (which I'm working on presently)
- Virtual namespace resolution is now centralized, _and_ cached within request scope with its own map (resolution still uses recursion with RTL fragment processing - I still think this is the safest implementation)

@kolotu Maybe we can close this already, or fine-tune it to what's left to do?

**Comment by kolotu** [comment]
yes i think we can close this one already.
