### ISSUE TITLE
Experiment with performance improvement on ModelRepositoryFactory#getUserRoles

### ISSUE THREAD

**Issue by mena-bosch** [eclipse/vorto#2562]
The method is invoked with extreme frequency and due to the recent refactory in table design, performs two select queries instead of one with many nested joins. 

It would be worth experimenting with either: 

- Add the ModeShape workspace ID as a foreign key field referenced by the user namespace roles, in order to avoid retrieving the namespace by workspace ID and therefore sparing one select query, or
- If that fails due to design reasons or does not improve performance sufficiently, attempt caching the user namespace roles table (which would be second choice because of the difficulties in coordinating with multiple Vorto instances running)

One middle-ground solution with caching would be to do so with a form of time-based expiry, since the method is called a number of times within the same context (hence data is almost guaranteed to not change).

**Comment by t-gauss** [comment]
For a simple example (getting one model with some references) its fetching the roles for a user in a namespace again and again from the database. In the example I tested to obtain the jcrsession the hibernate log showed 5 select queries vs 1 with the old implementation.

**Comment by mena-bosch** [comment]
Now that we have the latest data, and execution time for the method alone is 6 fold in dev vs prod, we can be sure that the double query (dev) performs less than the query with joins (prod - joins not being logged but it's obvious given the table design and JPA entities).

As discussed, the "real" solution would not be to optimize the db here, but rather figure out how to avoid for this method to be called a number of time with the exact same parameters - which might require a deep-dive into the way Vorto talks to ModeShape. 

Since that analysis might take long and any consequent re-writing might come with regressions/caveat, we could also consider caching the method invocation at class level (aka not even caching the Spring repository for user/namespace roles. 

This way we can trigger a cache at first method invocation mapping composite workspaceId+username -> roles, and make it expire a minute or so later. 
Subsequently the repeated identical invocations for a single model would only run the queries once, and the caching would expire quickly.  
Note again that this would only be a "patch" - the real issue to me is still the large number of "in session" calls for one single model.

**Comment by mena-bosch** [comment]
As discussed, the patch so far includes the reduction of direct queries to the DB by:

- Looking up the namespace from the JCR workspace ID as a join rather than two separate selects
- Caching a map of roles by composite workspace ID + username, for each request (so iterated invocations with the same parameters within the same request return cached data rather than talking to the DB)

While the patch seems to have a positive impact on performance, it needs more testing. 

There are also further improvements under discussion, namely:


1. Caching at repository level (would require better eviction scoping e.g. for concurrent Vorto instances, or based on request scope, etc.) - feasibility still uncertain, or...
2. Caching at service level, for all namespace/role-related queries but with the same mechanism presently implemented

**Comment by mena-bosch** [comment]
Caching implemented for user roles and namespaces. 
Multi-threaded model content solution resolved thanks to @kolotu 's help. 
Merged to dev. 
Next step will likely be addressing the large number of redundant or easily reduced networking calls from the UI when loading a model - ideally it will become only one call each model details page load.
