### ISSUE TITLE
Installation Guide Vorto Toolset

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#258]
Automatic Installation:
IDE for Manufacturers : https://marketplace.yatta.de/profiles/ziXJ
IDE for Platform Vendors: https://marketplace.yatta.de/profiles/4PTx
IDE for Solution Developers: https://marketplace.yatta.de/profiles/KezX

Manual Installation:

1) Prerequisite:
- Mars for DSL Developers
- Java 8

Getting toolset:
1) Update Site 
2) Update Archive
3) Eclipse Marketplace

**Comment by andrew-from-pretoria** [comment]
The Vorto Eclipse Toolset has been deprecated. 

"The Eclipse Vorto IoT Toolset Plugins are no longer supported. Instead you can simply use the Cloud-based Editors in the Vorto Repository." 

(Ref https://github.com/eclipse/vorto/blob/master/docs/release-notes.md )
