### ISSUE TITLE
Show not found page if information model could not be found

### ISSUE THREAD

**Issue by stheves** [eclipse/vorto#2601]
When trying to access the information model details page for a model which does not exist, you get an infinite loading indicator. It would be  better if the user would get a message that the information model does not exist (or cannot be accessed).

Can be tested with the following link:

https://vorto.eclipse.org/#/details/asdfasdfaf:aasdjkfhak:asihda

**Comment by mena-bosch** [comment]
Not sure if this has been long broken or just never implemented n the UI. 
PR [here](https://github.com/eclipse/vorto/pull/2618) - expect it should be merged soon.

**Comment by mena-bosch** [comment]
Merged to dev.
@stheves give me a shout if you'd like me to notify you when this goes to prod.
