### ISSUE TITLE
Add links API to Swagger documentation

### ISSUE THREAD

**Issue by kolotu** [eclipse/vorto#2651]
Add the new endpoint to retrieve links to the Swagger documentation: 

GET `/api/v1/attachments/{modelId}/links`

For example: https://vorto.eclipse.org/api/v1/attachments/com.bosch.iot.suite.example.octopussuiteedition:OctopusSuiteEdition:1.1.0/links

**Comment by tanmayj2020** [comment]
I want to contribute to this issue , can you guide me

**Comment by kolotu** [comment]
Hi @tanmayj2020 sure.

This issue is about adding documentation of the new HTTP endpoint to our Swagger documentation. You can see the rendered Swagger documentation here: 
and this is the matching source file: /vorto/docs/specs/vorto_repository-1.0.yml

The endpoint is about retrieving links that have been attached to a model. The only parameter is the path parameter `modelId`. The description of the endpoint, description of the parameter parameter and the example need to be added to this file in the same pattern as for the other HTTP endpoints already documented in that file.

**Comment by kolotu** [comment]
@tanmayj2020 pls also have a look at our [CONTRIBUTING](https://github.com/eclipse/vorto/blob/development/CONTRIBUTING) file

**Comment by baidaadarsh** [comment]
Hey,

@kolotu  I have submitted a pull request for the above issue would request you to please review the same.
