### ISSUE TITLE
Allow IDs to begin with a number

### ISSUE THREAD

**Issue by laverman** [eclipse/vorto#266]
**Current State:**
IDs are allowed to begin with a ('a'..'z'|'A'..'Z'|'_'). 

**After implementing this feature:**
IDs are allowed to begin with ('a'..'z'|'A'..'Z'|'_'|'0'..'9'). However, to allow separation from e.g. `integer`, IDs cannot exist solely of numbers.

**Examples**

```
3-Axis as int  // Correct
3-Axis2 as int // Correct
5635 as int    // Incorrect
axis as int    // Correct
```

**Comment by nagavijays** [comment]
Most of the compilers don't allow variables starting with number. (eg. c, java). Code Generators have to do additional step in converting the variable name according to the target language. 
I could think of making use of 'description' field to describe about the field in free text and can consumed in whatever format desired.

**Comment by OlafWeinmann** [comment]
I agree that most of the compilers don't allow this. However the Vorto device descriptions should be technology agnostic - and we need a way for specifying these "original" names. Currently LWM2M related models are affected by this constraint. Wouldn't it make sense to adapt the code generator infrastructure accordingly?

**Comment by nagavijays** [comment]
Yes. Makes sense, if the code generator can handle for these variables correctly. 

Currently the variable doesn't allow hyphen (-), however it allows underscore (_). In example hyphen was used. So should both symbols (-, _) be allowed?

**Comment by laverman** [comment]
Well spotted :+1: 
I'd say, both should by allowed. But I'm open for any counter-arguments.

**Comment by aedelmann** [comment]
Original names can be put in mappings,  e.g. LWM2M Mappings. Processing of these kind of variable names is going to be more complex. Most languages do not support it for good reasons :)
