### ISSUE TITLE
Could not resolve placeholder 'suite_clientid' in value "${suite_clientid}"

### ISSUE THREAD

**Issue by tobias-zeptio** [eclipse/vorto#2660]
When running the nighly docker image, I get the error:

`Could not resolve placeholder 'suite_clientid' in value "${suite_clientid}"`

Adding `args.update({"suite_clientid": "foo"})` in run.py doesn't help, and neither does `args.update({"suite.oauth2.enabled": false})`

**Comment by kolotu** [comment]
This should be resolved by providing an arbitrary value for the environment variables eidp_clientid and eidp_secret. 
We should add this as default configuration in the vorto-variables.env

**Comment by tobias-zeptio** [comment]
Adding `EIDP_CLIENT_ID=foo EIDP_CLIENT_SECRET=foo` doesn't help.

**Comment by kolotu** [comment]
Okay let me try to analyze it on my local machine

**Comment by kolotu** [comment]
@tobias-zeptio Are you using the docker image from docker hub, or are you building it yourself?

**Comment by tobias-zeptio** [comment]
I'm using `eclipsevorto/vorto-repo:nightly`

**Comment by kolotu** [comment]
I've been able to reproduce the error - I'll look into a fix now

**Comment by tobias-zeptio** [comment]
I see you have made a change. Will the docker image be updated automatically?

**Comment by kolotu** [comment]
I merged a change that fixed it locally, the build process in the Travis-CI pipeline is slightly different, hence I'd need to double check, whether everything works now after the build is complete. The build also updates the nightly image automatically.

**Comment by kolotu** [comment]
The nightly image looks good now - you can try again now.

**Comment by kolotu** [comment]
merged changed to 1.0.0 release branch.

**Comment by tobias-zeptio** [comment]
Yes, it works now with these fixes.
