### ISSUE TITLE
Adding Generic/Custom OAuth 2.0 Authentication

### ISSUE THREAD

**Issue by tobias-zeptio** [eclipse/vorto#2680]
I would like to add a generic OAuth2 Authentication to this application. So instead of using github or bosch Iot, you could point the authentication to a generic implementation using Auth Code and/or Client Credentials flow.

Has this been investigated before, and would the IOAuthProvider abstraction support this?

**Comment by kolotu** [comment]
No this has not been investigated before, but this would be a great addition. Feel free to use this issue for it. 

I think the IOAuthProvider is generic enough to support it, but I haven't looked in detail yet. It should be worth a try.

**Comment by mena-bosch** [comment]
Worth recalling that our authorization system is not robust enough yet to handle users from different OAuth providers but with identical usernames, see #2529 for details. @kolotu let's discuss this tomorrow, maybe we can prioritize?
