### ISSUE TITLE
Create leshan code generator

### ISSUE THREAD

**Issue by gavinying** [eclipse/vorto#279]
1. Generate leshan java code for lwm2m objects from Vorto infomodels (Information models, function blocks, datatypes); 
2. Include sample code;

**Comment by aedelmann** [comment]
Can you briefly describe what the generator does exactly? Does it create both server and client stubs (similiar to the Vorto coap generator) that takes functionblocks as an input and creates leshan messages from it?

**Comment by gavinying** [comment]
@aedelmann, 
In my current design, it will generate client stubs based on vorto models, and it is not going to generate server side code based on below considerations, 
1) Server side is generic to all LWM2M objects, it should be able to take any object as long as it is defined in object definition files (xml or json), leshan core library already includes a default LWM2M object definition file for server; 
2) Server side always takes devices as the abstracted objects, theoretically no need to implement any specific code, so it is not necessary to generate code stubs; 
3) Practically, server and clients are usually one-to-many relationship, which is different from coap sender-receiver messaging concept, so that I think it is not necessary to generate server code together with client code; 

Above is just my thoughts of creating leshan code generator, and welcome inputs from team and others. Thanks!

**Comment by aedelmann** [comment]
I see, so the generator only generates leshan client stub code. What client stub functionality is it going to generate?

**Comment by gavinying** [comment]
Each LWM2M object will be described as a function block in vorto context, and leshan code generator will generate corresponding java class for each LWM2M object, e.g. generate Device.java for Device object. 
To be more specific, leshan code generator will help to do below jobs, 
1) Generate all resources as different java types of fields (e.g. int, float, String, ...) based on the definition of LWM2M object; 
2) Extend BaseInstanceEnabler class to implement LwM2mInstanceEnabler interface required by leshan framework; 
3) Generate code skeleton, e.g. setter and getter methods for users to implement their own logic;
