### ISSUE TITLE
Include third party dependencies into static folder

### ISSUE THREAD

**Issue by mapero** [eclipse/vorto#328]
The repository can not be hosted on a local network without an internet connection.

**Reason**
The repository has several dependencies on js and css files hosted on external servers, e.g.: bootstrap, font-awesome, jquery ...

**Solution**
Include the dependencies in the static folder of the repo-ui project.

**Comment by aedelmann** [comment]
Alternative solution: Add a maven dependency to these web jars

**Comment by aedelmann** [comment]
This has been fixed and no internet connectivity is needed to render Vorto UI.
