### ISSUE TITLE
Adding Modeldependency empties model

### ISSUE THREAD

**Issue by laverman** [eclipse/vorto#339]
**Actions taken:**
Create new DataTypes A and B. Started specifying A by inputting properties. 
- Saved the model (model is valid, no errors)
- closed the model
- Add dependency by dragging model B on model A

**Expected Result:**
- Model A is only changed in terms of adding a new "using" statment

**Actual Result:**
- "Using" statement is added
- model A is reset -> all input properties are deleted

**Comment by erlemantos** [comment]
I'll investigate this
