### ISSUE TITLE
Defintion of a Project-Namespace

### ISSUE THREAD

**Issue by laverman** [eclipse/vorto#340]
**Current state:**
Being able to define a certain namespace for each model is great. However, when adding new models to a new project it is cumbersome to change the default namespace for each and every model.

**After implementing this feature:**
It is possible to define a namespace per project. This namespace is than used as the default namespace when creating new models. However, the possibility to change the namespace per model is still given.

**Comment by aedelmann** [comment]
Hi @laverman 
we are working on the multi - tenancy feature of Vorto Repository which allows to specify a default namespace per tenant. As a consequence, every model that is created via the built-in Vorto Editor, will automatically specify the right namespace for the model and would not need to be added by hand anymore. 
Please track issue for further info and discussions: https://github.com/eclipse/vorto/issues/1088
