### ISSUE TITLE
Newly created model is not opened correctly

### ISSUE THREAD

**Issue by laverman** [eclipse/vorto#341]
**Steps taken:**
- Project already contains datatype models
- a new datatype model is created using the model wizard

**Expected result:**
- The newly created model is opened in the IDE

**Actual result:**
- The newly created model is opened
- However, the first dataType in the list is also opend and activated(*) in the IDE

(*) _activated_: Both models are opened, the activated one is the tab where the content is visible in the editor

**Comment by aedelmann** [comment]
Eclipse Toolset no longer supported.
