### ISSUE TITLE
Model Wizard should check if model already exists

### ISSUE THREAD

**Issue by laverman** [eclipse/vorto#342]
**Steps taken:**
- a datatype is created
- another datatype is created having the same NAME, NAMESPACE, VERSION as the first.

**Expected Result:**
- The model-wizard shows and error indicating that the model already exists

**Actual Result:**
- The wizard does not prohibit this by showing and error. 
- When creating the following error is given in the console:

[ERROR] File Generation failed !Resource '/MyType Classes/Vorto/workspace_vorto/MyType Classes/datatypes/com.mycompany.type_MyType_1_0_0.type' does not exist.

**Comment by aedelmann** [comment]
Eclipse toolset no longer supported
