### ISSUE TITLE
Documentation for Code-Generators Platform key

### ISSUE THREAD

**Issue by laverman** [eclipse/vorto#410]
Some code generators require information from mapping files. However, to create a mapping file a user needs to know the _Platform_ (Service-Key) of this generator. afaik this information is documented anywhere easy to find for a user, if documented at all.

Since a generator ignores mapping files where the platform does not 100% correspond to its service-key, this inhibits the usability! 

A possible solution could be a drop-down menu offered in the mapping-wizard, that lists all available code generators in the solution.

**Comment by Scriptkiddi** [comment]
fixed by #1145
