### ISSUE TITLE
Documentation for Code-Generators mappings

### ISSUE THREAD

**Issue by laverman** [eclipse/vorto#411]
Code-Generators can draw additional information from mapping files. To do so, it recognizes certain key-words. 

_Example_:

```
from TemperatureSensor.event.currentTemperature
to NAME_ID with {NAME: "VALUE"}
```

Note that a user does not know which values for _NAME_ID_ and _NAME_ the generator expects. 

**Solution**: This should be documented somewhere, clear and available to the user. Furthermore, a code-generator developer might specify a list of valid and/or expected values, which are offered via auto-completion.

**Comment by Scriptkiddi** [comment]
fixed by #1145
