### ISSUE TITLE
Compatability with other platforms

### ISSUE THREAD

**Issue by anandmahato29** [eclipse/vorto#420]
Does Vorto is compatable to IoT Platforms like OpenIoT, NetBeast, Zetta, Kaa, etc . If yes how can we implement ? Please provide some hints or ideas

**Comment by aedelmann** [comment]
Hi there. Great question. However addressing questions like this is more suitable to be raised through our forum under http://eclipse.org/forums/eclipse.vorto.
Could you please raise your question there, that way other people can take part in this discussion?

Thank you so much in advance!

Cheers, Alex
