### ISSUE TITLE
Model does not disappear from tree viewer when deleted

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#429]
Steps taken:
1. Add a model to the tree viewer
2. Right Click on the model and select 'Delete'

Expected: The model is removed from the tree viewer
Actual: The model remains in the treeviewer. When the project is saved and closed and re-opened again, the model has disappeared.

**Comment by shiv12095** [comment]
When a user tries to delete an editor that is not open in any of the tabs, this issue appears. 

Incase the tab is open and the user deletes it, the model is removed from the tree viewer
