### ISSUE TITLE
Model Browser only populated when the user searches based on the users' search criteria

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#430]
Currently the model browser fetches all models from the repository depending what type of model he is editing. When the user switches between tabs, the fetch is done again. This slows down the UI and responsiveness. 
Possible solution:
The fetch is only done when the user actively searches in the model browser, whereby async search requests are sent to the repository and the result is displayed in the model browser. 
When the user switches to the other tab, the search result and criteria is cleared and user has to search again.

**Comment by shiv12095** [comment]
Going ahead with the proposed solution
