### ISSUE TITLE
Deploy Bosch IoT Things Generator to Eclipse VM

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#439]
Confirmations:
- Bosch IoT Things Generator available as Micro Backend Service
- Generator has Bosch IoT Things Logo (not in code!)
-

**Comment by nagavijays** [comment]
On code, there is no logo included. Will take up this issue and create build with logo and deploy.

**Comment by nagavijays** [comment]
@aedelmann Deployed the generators to eclipse vm.
