### ISSUE TITLE
add tags for backend generators

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#454]
backend generators can be configured to have multiple tags that are returned by the /info restcall.

Tags can be used to filter the generators on the web frontend for example.

**Comment by nagavijays** [comment]
@erlemantos @aedelmann - As I understand the tags "production" needs to be added for "Prosyst" and "Bosch IoT Things Generator". Currently, the tags property is added only to "Prosyst" generator only. Is it sufficient to bring "Prosyst" generator only on top? Please clarify my understanding

**Comment by aedelmann** [comment]
@nagavijays @erlemantos 
You are right, both things and prosyst must have the tag production. Please change this in the code if needed.
