### ISSUE TITLE
Bosch IoT Things Generator Image is passed as Environment Variables to the Generator

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#485]
Confirmations:
- Store the generator image(s) on Eclipse VM under e.g. 
images/boschiotthings144.png 
images/boschiothings32.png
- Start generator with classpath variable , 
e.g. vorto.service.image144x144 = images/boschiotthings144.png

- Repeat this for the other following generators:
-- ProSyst Generator
-- ThingWorx Generator

**Comment by vlvanchin** [comment]
Configured both the images for both the generators and restarted the generators in Eclipse VM.
