### ISSUE TITLE
Create Docker-Compose for Eclipse VM to setup infra

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#499]
Confirmations:
- Create Docker-compose file contains pulling and running the following generators:
-- Bosch IoT Things Generator
-- ProSyst Generator
-- AWS Generator
-- Javabean Generator
-- ThingWorx Generator
-- Web UI
-- Markdown Generator
-- CoAP Generator
- Verify the correct behaviour of generators from the Vorto Repository Web Interface

**Comment by vlvanchin** [comment]
created docker-compose file and tested it locally.
