### ISSUE TITLE
vorto command line tool on OS X: download yields illegal file names

### ISSUE THREAD

**Issue by badryan** [eclipse/vorto#50]
When downloading a model using e.g.
`vorto info examples.datatypes.state.DoorState:1.0.0`
two files are being created. One is an empty, illegal directory called "\"
 and the other is the model, the file name unfortunately also preceded by "\", which requires one to rename the file before it can be opened.

**Comment by nagavijays** [comment]
I will look into this issue.

**Comment by nagavijays** [comment]
I will work on this issue.
