### ISSUE TITLE
Automated Deployment of Docker Containers to Eclipse from Hudson

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#504]
Whenever we have a stable milestone or release, the Vorto Hudson invokes the docker-compose.yml file on Eclipse VM which is parametrized with the Version/Tag to pull from docker-hub and spin up.

**Comment by vlvanchin** [comment]
Currently following with Eclipse VM team waiting for their guidance.

**Comment by vlvanchin** [comment]
Created a ticket in Eclipse Bugzilla : https://bugs.eclipse.org/bugs/show_bug.cgi?id=520666

**Comment by vlvanchin** [comment]
This is feature now integrated in Hudson
