### ISSUE TITLE
Mappings are not retrieved from the model repository to the vorto project space

### ISSUE THREAD

**Issue by deepagithub** [eclipse/vorto#518]
Test version : Vorto **0.9**

**Steps:**
Open eclipse IDE
Retrieve TI_SensorTag from the model repository and add it to the vorto project space
**Expected Result:**
All the dependencies (datatypes, functionblocks, infomationmodels and mappings) are retrieved 
**Actual Result:**
Mappings folder is empty.

**Comment by erlemantos** [comment]
I'll work on this.
