### ISSUE TITLE
Introduction of a UUID for Vorto-Models

### ISSUE THREAD

**Issue by laverman** [eclipse/vorto#528]
In Vorto models are identified by a combination of **namespace**, **name** and **version**. However, how these three properties are combined differs:

### Current Situation
REST-API: `<root>/<namespace>/<name>/<version>` // *separated by slashes*
DSL: `<namespace>.<name> ; <version>` // *separated by dot and semi-colon*
Repo: `<namespace>.<name>:<version>` // *separated by dot and colon*

### Proposed Solution
Since this is not consistent, this issue requests the introduction of a UUID for Vorto models.
The proposed UUID shall be made up of the same properties separated by colons, and looks the following:

    model-uuid := <namespace>:<name>:<version>

In order to achive consistency the follwoing changes shall be made:

REST-API: 

    <root>/uuid/<model-uuid>
    e.g.: <root>/uuid/my.company.models:MyModel:1.0-Snapshot

DSL:
    
    usage <model-uuid>
    e.g.: usage my.company.models:MyModel:1.0-Snapshot

Repo:

    Reference: <model-uuid>
    e.g.: Reference: my.company.models:MyModel:1.0-Snapshot

**Comment by aedelmann** [comment]
This feature is implemented since 0.10.0-M6 as far as the model IDs of repo and REST - API is concerned. 
The new pattern of model IDs are <namespace>:<name>:<version> 
The Model References in the DSL are not part of this change, but part of #1121
