### ISSUE TITLE
Eclipse Vorto Toolset, Code generators, Model repository bundled into virtual machine

### ISSUE THREAD

**Issue by nagavijays** [eclipse/vorto#531]
To take a quick look at Eclipse Vorto and all tools without worrying about installations, configurations settings etc. Its good to have all the tools bundled together in a Virtual Machine (VM) file. 

User can just download the file and launch a VM without worrying about setup instructions. 

Vorto also have Docker images, but still requires docker installation, configurations etc. 

If this is not feasible/valuable/out of scope feature, this ticket can be closed.

**Comment by aedelmann** [comment]
We are supporting docker as a lightweight virtualisation option to set up a repository and generators plus it supports a distribution server (docker hub) for users to download these images very easily. 
With this approach, we would need to support/maintain different full VM's as alternative to docker with different Linux flavours, Win etc. 
How else does it differ from docker and what advantages would you see compared to docker?

**Comment by nagavijays** [comment]
Things team uses Docker and Vagrant in their development and production deployments. Vagrant uses to package it as a virtual machine. 
In my opinion, both are not contradictory, rather both are complementary. Virtual machines offer certain advantages to user like configuration of network, memory customizations etc. I think its easy to login to a vm than running dockerized applications. 

Jhipster, one of the popular framework uses Docker and Vagrant. While Docker pulls are around 10K and Vagrant pulls around 19K. Certainly docker has advantages. No doubt about that. Virtual machine provides much more convenient way.
