### ISSUE TITLE
Manage menu item is visible after admin user logout 

### ISSUE THREAD

**Issue by vlvanchin** [eclipse/vorto#532]
In the Vorto Repo site, once the admin finishes the tasks and logout the **Manage** menu item is visible, that allows to manage without admin privileges. 

**Steps to reproduce**

- Login and Logout as admin user in vorto repository
- Menu **Manage** is still visible to the anonymous user
- Click on this link, the manage page is displayed were restore and backup links are available.
- try clicking on Backup Repository Content
- 401 response is what received.

**Expected functionality**

- Login and Logout as admin user in the vorto repository
- the menu **Manage** is not shown to the user.

**Comment by aedelmann** [comment]
This has been fixed AFAIK. Please re-open if still occurs.
