### ISSUE TITLE
Upload/Share models page should not visible without login

### ISSUE THREAD

**Issue by nagavijays** [eclipse/vorto#539]
Steps taken: 
- On a new browser tab, visit http://vorto.eclipse.org/#/upload

Expected Result : 
- Redirect to login page. 

Actual Result: 
- The upload/share model page is shown. 

Note: 
Upload of models without user logged-in results in "Unauthorized Operation", however the upload models page should not be shown to the user when directly entering the url in a browser.

**Comment by aedelmann** [comment]
This has been fixed afaik. Closing issue. If issue still occurs, please re-open.
