### ISSUE TITLE
Improper nesting of html tags

### ISSUE THREAD

**Issue by nagavijays** [eclipse/vorto#541]
Steps Taken: 
- Visit System requirements page 

Expected Result: 
- Page should be displayed correctly 

Actual Result: 
- Page is displayed correctly, but there are some extra html tags rendered (Attached)
![screen shot 2017-04-13 at 12 16 33 am](https://cloud.githubusercontent.com/assets/13414125/24968174/ff17a3d6-1fde-11e7-8310-cfb605e976ef.png)

Tested with Google Chrome, Firefox, Safari

**Comment by Ebolon** [comment]
Seems linke the issue has been resolved.

https://www.eclipse.org/vorto/documentation/overview/system-requirements.html

**Comment by aedelmann** [comment]
Seems like it :) thus, closing issue.
