### ISSUE TITLE
Vorto CLI error on Mac

### ISSUE THREAD

**Issue by nagavijays** [eclipse/vorto#542]
Steps Taken:
- Download the latest Vorto CLI for Mac
- Configured CLI as per the [documentation](http://www.eclipse.org/vorto/documentation/vorto-repository/cli-tool/configuring-cli-tool.html) as 
`vorto config -username <username> -password <password> -repo http://vorto.eclipse.org`
- Ran ./vorto query "*" or vorto query "*"

Expected Result:
 - Displays all the vorto models. 

Actual Result:
- Displaying error message (Attached)

>  "json: cannot unmarshal string into Go value of type int64"
![screen shot 2017-04-13 at 12 31 10 am](https://cloud.githubusercontent.com/assets/13414125/24968991/c94a95e4-1fe1-11e7-84f7-ae0cf985d7a3.png)
![screen shot 2017-04-13 at 12 35 09 am](https://cloud.githubusercontent.com/assets/13414125/24968990/c94a4cb0-1fe1-11e7-9966-8dea0f9878ea.png)

PS: User details masked.

**Comment by aedelmann** [comment]
Hi @nagavijays 
should be resolved now. Can you please verify ?
Thanks. Cheers, Alex

**Comment by aedelmann** [comment]
Closing , as issue has been fixed. If it re-occurs, please re-open. Thx
