### ISSUE TITLE
Generation through Model Repository does not work when using GeneratorServiceInfo Class from Version 0.9.0

### ISSUE THREAD

**Issue by marcusmunzert** [eclipse/vorto#596]
We have a code generator "IoT Gateway for Kura (with Vorto-Models)" registered with Vorto. That code generator is executed on our Virtual Developer platform when someone selects an information model on the Vorto model repository and clicks on "Generate". We use the class GeneratorServiceInfo (contained in artifact org.eclipse.vorto.codegen) from the released version 0.9.0 of Vorto to provide the generator metadata. That class does not yet include the fields "configTemplate" and "configKeys" (in 0.10.0 they _are_ included). So the actual model repository web app somehow depends on Vorto 0.10.0. For our generator a click on "Generate" causes an error in the JavaScript function "generate" in controllers.js.

As a workaround we simply have copied two source code files from 0.10.0 to use them to provide the JSON data. A better, more general solution might be to modify the JavaScript "generate" function to not depend on the presence of  "configTemplate" and "configKeys" in the JSON data.

Please note that at the time of writing this issue, a ready built version (e.g. SNAPSHOT) of 0.10.0 is not publicly available.

**Comment by aedelmann** [comment]
Hi Markus, 
we are gonna provide a fix in the javascript and deploy it by tmr. 
Thanks for the hint!

Cheers, Alex

**Comment by aedelmann** [comment]
Hi Marcus

We rolled out the fix. Can u please verify ? 
Thanks. 

Alex
