### ISSUE TITLE
Import of existing Vorto project doesn't work as expected

### ISSUE THREAD

**Issue by laverman** [eclipse/vorto#608]
**Steps Taken**
- Empty Eclipse Vorto instance with no projects yet
- `FILE > Import... > Existing Projects into workspace`
- Selected a Vorto project to be imported

**Expected Result**
- Project is automatically imported and displayed in _Vorto Model Project browser_

**Actual Result**
- Project is not displayed in _Vorto Model Project browser_
- Project is imported into workspace (visible via _Resource View_) 
- _Reset Perspective_ on Vorto perspective didn't fix it
- only a restart of Eclipse IDE fixed to issue.

**Comment by aedelmann** [comment]
Toolset no longer supported. Please use Vorto Repository to import Vorto or other model types.
