### ISSUE TITLE
absolute references in models without stated as "using" result in inconsistency in repo

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#622]
Steps to reproduce:
1) Create a functionblock model and datatype (org.example.MyType) using the Eclipse Toolset
2) define a operation e.g myop(param1 as org.example.MyType) without having dragged and dropped it
This results in having a functionblock model that is not referencing the type in "using" statements 

Expected: Validation error in operation param that model has to be imported / referenced in "using" 

Actual: model is valid. Therefore developers can check in the model. However code generation and dev-console breaks

**Comment by erlemantos** [comment]
I'll take this
