### ISSUE TITLE
Web Editor - Adding a function block with reference to an Information model throws an error message

### ISSUE THREAD

**Issue by deepagithub** [eclipse/vorto#630]
**Steps:**
Add an Information Model
Add a Function Block
Add a New entity
Drag Drop the entity to the function block
Drag Drop the Function block to the information model
**Expected Result:**
The function block should be included in the Information model reference. No error should be displayed
**Actual Result:**
An error "Failed to reference resource" is displayed

**Comment by shiv12095** [comment]
@deepagithub 
I tried to replicate this issue with the latest code (https://github.com/eclipse/vorto/commit/33b98c02c4830f15af1d8450974e8d2421f25583) by importing multiple entities into function blocks and then importing these function blocks to an information model. However I was not getting any error. Further, I also used multiple user accounts across different projects but could still not get the issue. 

Could you please try this out once again with the latest code and let me know if the issue persists. Also could you provide the last commit id at which you faced this issue. I can take a look from there and ascertain which future commit could have fixed this.

**Comment by deepagithub** [comment]
@shiv12095 , I'm testing on the commit version [7664fcc](https://github.com/eclipse/vorto/commit/7664fccb0e3ded2c3a7abd1a337533e7ec4a3c57)

**Comment by deepagithub** [comment]
This problem does not occur in the updated web editor
