### ISSUE TITLE
Web Editor - Deleting a reference from the project tree does not remove the referenced line from DSL

### ISSUE THREAD

**Issue by deepagithub** [eclipse/vorto#633]
**Steps:**
Add a new function block
Add a Data Type
Drag Drop the data type to the function block -> The function block DSL is updated with a reference to the data type
Delete the data type from the tree - > The deletion is successful
**Expected Result:**
The referencing line in DSL should be deleted from the function block
**Actual Result:**
The referencing line is not removed from the DSL of the function block

**Comment by shiv12095** [comment]
This is expected behaviour, meaning: the developer would have to manually remove the referencing line from the information model. 
The function block will no longer be available through content assist.
