### ISSUE TITLE
Save button does not save the editor session to persistence

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#645]
Steps to reproduce:
1) Create a project
2) Create an info model
3) do some changes to the info model , e.g. changing description or import a function block
4) Click "Save" button (next to Publish button)
5) Close project 
6) Re-open project

Expected: The changes are loaded into the editor
Actual: The editor does not contain the saved changes. In fact it is the state it had when you create a new info model

**Comment by shiv12095** [comment]
For the time being, while I am resolving this issue, you can use Cmd + S / Ctrl + S to save the files.
