### ISSUE TITLE
Allow the possibility to have a single project with many vorto models

### ISSUE THREAD

**Issue by nagavijays** [eclipse/vorto#65]
Migrated from https://bugs.eclipse.org/bugs/show_bug.cgi?id=484534

**Comment by OlafWeinmann** [comment]
This issue only covers the project structure. This includes the change of the wizzards and not the Vorto perspective.

**Comment by deepagithub** [comment]
1. Create Vorto Model Project
    - project
    - workspace
Produces eclipse project with Vorto nature
2. Menu items to create model files using a wizard for the model project.
3. Allow users to define using statements to reference models within the same project(auto completion?)
4. Scope provider for only supported models to be used in the model
