### ISSUE TITLE
Toolset - Drag and Drop of a DataType to the FB with validation error changes the values of namespace, name and version of the functionblock to null

### ISSUE THREAD

**Issue by deepagithub** [eclipse/vorto#655]
**Steps:**

1. Create a datatype e.g. 
```
entity TightenResult {
	  optional cellId as int
	  optional channelId as int 
}
```

2. Create a function block e.g. 
```
functionblock Magnetometer {
	operations {
                getval() returns TightenResult
	}
}
```
3. The function block has a validation error that the referenced model has to be imported
4. Drag and Drop the entity to the function block

**Expected Result:**
The datatype should be included in the function block. The function block should have a statement "using.." referencing the data type.

**Actual Result:**
The Functionblock's namespace, name and version becomes null.
This is related to [#622](https://github.com/eclipse/vorto/issues/622)

**Comment by erlemantos** [comment]
I can't reproduce this on Neon.2, Neon.3 and the latest Oxygen R with the latest nightly build

**Comment by erlemantos** [comment]
I've been able to reproduce this, but only when the return type is fully qualified, not when it's just the 'name'. Anyhow, there are workarounds for this so I think this is not that critical.
