### ISSUE TITLE
CLI for Windows - Vorto Commands are not working

### ISSUE THREAD

**Issue by deepagithub** [eclipse/vorto#682]
**Steps:**
Download the CLI for Windows
Open the command prompt and execute Vorto commands

**Expected Result:**
Results should be displayed based on the command

**Actual Result:**
No results are fetched from the repository.
e,g.
_C:\VortoCLI>vorto info devices.TISensorTag:1.0.0
Model does not exist
C:\VortoCLI>vorto generators
No active Code Generator
C:\VortoCLI>vorto query "*"
invalid character '<' looking for beginning of value_

**Comment by aedelmann** [comment]
This is because the GeneratorInfo objects in Go have not been updated to the latest state, containing the properties for the configuration UI.

**Comment by erlemantos** [comment]
The configuration UI properties are only for the Repo <-> Generators Gateway, it didn't change the API for the CLI <-> Repo.

**Comment by deepagithub** [comment]
Every command works except vorto share.
Sharing a model from command prompt does not appear in the repository
