### ISSUE TITLE
Archive older releases/milestone update-sites upon release

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#686]
Configure hudson that before the update-site.zip is uploaded to the update-site server, it archives the previous stable milestone/release in a subfolder
e.g. .../milestones/0.9.0

**Comment by vlvanchin** [comment]
Parameterization of old version is done.
update of script is in progress

**Comment by vlvanchin** [comment]
Parameterization of build type and current version is defined in the Hudson job. So on triggering the build job, we need to give the buildType (possible values: 'milestones', 'releases', 'nightly-snapshots') and currentVersion (eg. 0.10.0.M2).

This would create the necessary folder and copy and expand the zip in this folder.

This need to be configured in the relevant jobs.

**Comment by vlvanchin** [comment]
- Configuration of input parameters for the Jenkins Job
  - buildType - this represents the type of build that the Jenkins job has been triggered. The value that this parameter could possibly hold 'milestones', 'releases'. 
  - currentVersion - this represents the version of the build that the Jenkins job has been triggered. The value that this parameter could possibly hold is the release/milestone version. (ex. “0.10.0.M1”) 
- Based on the above two parameters, the shell script would create the necessary folder for currentVersion for the corresponding buildtype.
- The script will copy the artifact (zip file) to the newly created folder and expand the contents as well.

```
The syntax of the URI is as follows:
../vorto/update/<buildType>/<currentVersion>/?d

Example:
In the Jenkins job, if the buildType = milestones and currentVersion = 0.10.0.M1 then the following URL will have the artifacts. 

http://download.eclipse.org/vorto/update/milestones/0.10.0.M1/?d
```

**Comment by aedelmann** [comment]
Can we close this issue ? Meaning is this logic already deployed and running for releases/milestones in Jenkins ?

**Comment by vlvanchin** [comment]
The configurations are carried out in toolset release job in Hudson. Hence closing.
