### ISSUE TITLE
Toolset - Drag and Drop a function block to another function block is allowed

### ISSUE THREAD

**Issue by deepagithub** [eclipse/vorto#689]
Steps:
In a toolset, create 2 function blocks
Drag and drop a function block to another function block

Expected Result:
It should not be allowed. 

Actual Result:
Drag and Drop a function block to another function block is allowed

**Comment by aedelmann** [comment]
Hi @deepagithub 
it is expected behavior that functionblocks can be dragged onto another functionblock because functionblocks can inherit from each other.

**Comment by deepagithub** [comment]
Okay, Please help to close this issue.
