### ISSUE TITLE
Repository - Disable the CheckIn button once a model is shared successfully

### ISSUE THREAD

**Issue by deepagithub** [eclipse/vorto#693]
**Steps:**
Login to Vorto Repository 
Choose > Share > Browse for a valid model and Upload
Click CheckIn > Model will be uploaded successfully.
Click CheckIn once again
**Expected Result:**
CheckIn button should be disabled after being clicked once
**Actual Result:**
CheckIn button remains enabled and every duplicate click throws Internal Server Error

**Comment by aedelmann** [comment]
Fixed.
