### ISSUE TITLE
How to delete the older Information Model in http://vorto.eclipse.org

### ISSUE THREAD

**Issue by Junjie-Chen3711** [eclipse/vorto#704]
I have uploaded an Information Model in repository before, and now I want to delete this one, how can I do it?

**Comment by aedelmann** [comment]
Removing an information model can only be done by the admin at the moment. We are working on the feature, that model authors can delete their models as well. In the meantime, I can delete the model for you. What's the model ?

**Comment by aedelmann** [comment]
Hi @Junjie-Chen3711 
you should be able to delete your model now in vorto.eclipse.org repository. 

- Alex
