### ISSUE TITLE
AWS Code Generator tutorial

### ISSUE THREAD

**Issue by javaand** [eclipse/vorto#721]
Hi everybody,
Is there an tutorial post or document how to run code generated by AWS generator

thanks in advance

**Comment by javaand** [comment]
I have created Information model called MySwitch in vorto perspective and then by right clicking I generated aws code. In the generated code there are two sub folder alexa subfolder and shadow subfolder by running node index.js command in terminal opened in */alexa I get this error:
 
ReferenceError: MySwitch is not defined
    at Object.<anonymous> (/home/khalil/vorto-workspace1/MySwitch_aws_generated/aws/alexa/index.js:1:63)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

the content of index.js is:
MySwitch.prototype.intentHandlers = {
    // register custom intent handlers
    "on": function (intent, session, response) {
    	 var params = {
    	 	FunctionName: '<ADD ARN OF LAMBDA FUNCTION HERE>', /* should be ARN */
    	 	ClientContext: null,
    	 	InvocationType: 'RequestResponse',
    	 	LogType: 'Tail',
    	 	Payload: JSON.stringify({}),
    	 	Qualifier: '$LATEST'
    	 };
    	 lambda.invoke(params, function(err, data) {
    	 	if (err) console.log(err, err.stack); // an error occurred
    	 	else {
    	 		console.log(data); // successful response
    	 		response.tell("Okay I invoked on on MySwitch for you.");
    	 	}
    	 });
    	 
    },
    "off": function (intent, session, response) {
    	 var params = {
    	 	FunctionName: '<ADD ARN OF LAMBDA FUNCTION HERE>', /* should be ARN */
    	 	ClientContext: null,
    	 	InvocationType: 'RequestResponse',
    	 	LogType: 'Tail',
    	 	Payload: JSON.stringify({}),
    	 	Qualifier: '$LATEST'
    	 };
    	 lambda.invoke(params, function(err, data) {
    	 	if (err) console.log(err, err.stack); // an error occurred
    	 	else {
    	 		console.log(data); // successful response
    	 		response.tell("Okay I invoked off on MySwitch for you.");
    	 	}
    	 });
    	 
    },
    "toggle": function (intent, session, response) {
    	 var params = {
    	 	FunctionName: '<ADD ARN OF LAMBDA FUNCTION HERE>', /* should be ARN */
    	 	ClientContext: null,
    	 	InvocationType: 'RequestResponse',
    	 	LogType: 'Tail',
    	 	Payload: JSON.stringify({}),
    	 	Qualifier: '$LATEST'
    	 };
    	 lambda.invoke(params, function(err, data) {
    	 	if (err) console.log(err, err.stack); // an error occurred
    	 	else {
    	 		console.log(data); // successful response
    	 		response.tell("Okay I invoked toggle on MySwitch for you.");
    	 	}
    	 });
    	 
    },
    "onStatus": function (intent, session, response) {
    	var params = {
    		FunctionName: '<ADD ARN OF LAMBDA FUNCTION HERE>', /* should be ARN */
    	    ClientContext: null,
    	    InvocationType: 'RequestResponse',
    	    LogType: 'Tail',
    	    Qualifier: '$LATEST'
    	  };
    	  lambda.invoke(params, function(err, data) {
    	  	if (err) console.log(err, err.stack); // an error occurred
    	    else {
    	    	console.log(data); // successful response
    	    	response.tell("The current on status of the MySwitch is "+data.on+".");
    	    }
    	 });
    	 
    }
   };

Please anyone could help me
@aedelmann

**Comment by aedelmann** [comment]
Hi @javaand . The nodejs code generated by Vorto, is an Alexa skill set that would need to be run as lambda in AWS. I know that there is no documentation currently, but we are working on it. 
In the meantime, you might wanna try deploying the code as lambda functions in AWS.  

I would also suggest you to use the AWS generator from the 0.10.0 Milestone 1. It's a major improvement and much more intuitive to use it as it is only a single lambda function for the Alexa skill set. You can download the milestone 1 toolset from our Downloads page of our web site www.eclipse.org/vorto. 

Hope that helps. 
- Alex

**Comment by aedelmann** [comment]
Closing issue. Please re-open if needed.
