### ISSUE TITLE
Android-things Generator

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#737]
Confirmations:
- Vorto Generator (Backend + Toolset)
- Generates Simple API that is able to send telemetry data via MQTT to Eclipse Hono
- Generator invokes the JavaBean Generator for Model Classes
(Reference project invoking the javabean generator: https://github.com/eclipse/vorto/tree/development/generators/org.eclipse.vorto.codegen.mqtt)
- Model Classes can be serialized to JSON
- Short tutorial in the same format/outline as https://github.com/eclipse/vorto/blob/development/tutorials/tutorial_connect_xdk_ble.md 
- Generator has no dependency to Bosch related artifacts
- Generator is available in toolset and published as Generator in the Vorto Repository

See other similar generator for reference:
As the Arduino generator (see https://github.com/eclipse/vorto/tree/development/generators/org.eclipse.vorto.codegen.arduino)

**Comment by vlvanchin** [comment]
Size: XL
