### ISSUE TITLE
Signing of eclipse plugin bundles

### ISSUE THREAD

**Issue by nagavijays** [eclipse/vorto#79]
Migrated from https://bugs.eclipse.org/bugs/show_bug.cgi?id=483973

**Comment by aedelmann** [comment]
https://wiki.eclipse.org/JAR_Signing

**Comment by aedelmann** [comment]
Other eclipse project use a signer-plugin for maven:
https://www.eclipse.org/cbi/sitedocs/eclipse-jarsigner-plugin/plugin-info.html

**Comment by erlemantos** [comment]
Our code already has a profile for signing which can be executed by 

```
mvn clean install -P sign
```

Unfortunately, there is an error of some kind about not resolving  build.eclipse.org

```
[ERROR] Failed to execute goal org.eclipse.cbi.maven.plugins:eclipse-jarsigner-plugin:1.0.5:sign (sign) on project org.eclipse.vorto.core: Could not sign artifact org.eclipse.vorto:org.eclipse.vorto.core:eclipse-plugin:0.9.0-SNAPSHOT: Unknown host build.eclipse.org -> [Help 1]
```

I believe this is a proxy error on my side but even passing the usual parameters for using proxies doesn't work.

```
mvn clean install -P sign -Dhttp.proxyHost=<proxy host> -Dhttp.proxyPort=<proxy port> -Dhttp.proxyUser=<proxy user> -Dhttp.proxyPassword=<proxy password>
```

Even setting the environment variable for the proxy doesn't work

```
export http_proxy=http://<proxy user>:<proxy password>@<proxy host>:<proxy port>
```

Which leads me to conclude this must be an error on the jarsigner plugin not handling proxies well. Either that or there is another way to set the proxy being used by the jarsigner.

**Comment by erlemantos** [comment]
Can anyone who doesn't need a proxy confirm that ```mvn clean install -P sign``` works outside a proxied network?

**Comment by erlemantos** [comment]
By the way, this is the profile in our root pom.xml for signing ...

```
<profile>
			<id>sign</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.eclipse.cbi.maven.plugins</groupId>
						<artifactId>eclipse-jarsigner-plugin</artifactId>
						<version>1.1.3</version>
						<executions>
							<execution>
								<id>sign</id>
								<phase>verify</phase>
								<goals>
									<goal>sign</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
```
