### ISSUE TITLE
Automated deployment of nightly builds / releases to Maven Central

### ISSUE THREAD

**Issue by nagavijays** [eclipse/vorto#80]
Migrated from https://bugs.eclipse.org/bugs/show_bug.cgi?id=483971

**Comment by aedelmann** [comment]
Process to do that:

1.	Create GPG keys and sign public key (ttps://pgp.mit.edu/pks/lookup?op=vindex&search=0x385CBC1C7F667FAE) 
2.	ssh-access for vorto github for automatic tagging of hipp instance ( https://bugs.eclipse.org/bugs/show_bug.cgi?id=502359 )
3.	After the first release, create a sonartype ticket for maven-central sync job See sonartype documentation: https://issues.sonatype.org/browse/OSSRH-25428
4. Configure distribution management, nexus plugin and maven-gpg-plugin

**Comment by erlemantos** [comment]
Is there any  documentation for this process? I tried following the process above but it's quite cryptic.

**Comment by aedelmann** [comment]
Hi Erle, 
Can you check out the issue if it contains some links:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=508342
