### ISSUE TITLE
Sharing (uploading) from eclipse editor not working reliable

### ISSUE THREAD

**Issue by inno-steffg** [eclipse/vorto#847]
Hi,

I've just tried to upload several data types out of the Vorto Model Project Browser (V0.9.0) view via context menu entry "share", which seemed to work.
BUT eventually, the data type seemed not to be available as search did not find it.

Uploading via Share tab on the Repository Website worked as expected.

**Comment by aedelmann** [comment]
Please use the Web Editor instead of the Eclipse Toolset. The Eclipse Toolset is no longer supported.
