### ISSUE TITLE
Uploading function block with correct import is rejected

### ISSUE THREAD

**Issue by geglock** [eclipse/vorto#852]
I tried to upload a new function block model to the Vorto Repository. The model is rejected even so it looks correct and is validated correctly in an Eclipse workspace with Vorto.

The upload is rejected with the error:
`The following property (properties) [multiple Accessory] has not been imported (not in the "using" statement).`

The referenced data type was uploaded before:
[http://vorto.eclipse.org/#/details/com.acme.catalog/Accessory/2.0.0?s=com.acme](http://vorto.eclipse.org/#/details/com.acme.catalog/Accessory/2.0.0?s=com.acme)

The not accepted function block model looks like this:
```
namespace com.acme.catalog
version 2.0.0
displayname "Accessories"
description "Function block model for Accessories"
category example
using com.acme.catalog.Accessory; 2.0.0

functionblock Accessories {

	configuration{ 
	}

	status{ 
	}

	fault{
	}

	operations{
		retrieveSupportedAccessories() returns multiple Accessory
	}
}	
```

**Comment by aedelmann** [comment]
Hi @geglock 
That was indeed a bug in our validators. Fix is now available on vorto.eclipse.org.
