### ISSUE TITLE
Possibility to refine primitive datatypes

### ISSUE THREAD

**Issue by inno-steffg** [eclipse/vorto#856]
Proposal

It should be possible to add datatypes that base on primitive types but restricts them in some way.

Examples:
- positiveFloat extends float <MIN_EXCL 0.00>
- shortID extends string <REGEX "[a-z0-9]{3,64}">
- singleLine extends string <REGEX "[^\n]{0,255}">

**Comment by kolotu** [comment]
Constraints have been implemented - see vortolang specification for reference: https://github.com/eclipse/vorto/blob/development/docs/vortolang-1.0.md
