### ISSUE TITLE
The repository does not autorefresh after a model is deleted

### ISSUE THREAD

**Issue by deepagithub** [eclipse/vorto#866]
**Steps:**
Login to vorto repository as a user with delete rights 
Choose any model to delete
**Actual Result:**
The model is deleted successfully and the repository home page is displayed.
But, the deleted model is displayed in the search result.
The model gets removed from the search result after manually reloading the page.
**Expected Result:**
Once a model is deleted successfully, the model is removed from the search result automatically.

**Comment by aedelmann** [comment]
Issue cannot be reproduced anymore.
