### ISSUE TITLE
User must define the language version as part of the vorto model

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#889]
Based on the information of the syntax version identifier, Vorto can distinguish between different vorto meta model versions. If somebody commits a vorto model to Github/gitlab, the validator is able to validate against the correct meta model version.

Confirmation:
- All model files in Vorto must declare the syntax (meta-model) version inside the definition of the model
- Migrate existing models in Vorto to include the new syntax identifier.
Example:

syntax = "vorto1";
namespace mynamespace
version 1.0.0
description "Information Model for ModelX"
category iot

infomodel ModelX {
	
	functionblocks {
		...
	}
}

**Comment by Ebolon** [comment]
I would suggest to use `vortomodel 1.0.0` or simple `vorto 1.0.0` instead of the syntax identifier. This would allow to specify a range of compatible models.

**Comment by aedelmann** [comment]
@Ebolon 
How about 
`vortolang 1.0.0` ?
We are always talking about Vorto being a language for the IoT, why not mention that in the keyword as well ?

**Comment by Ebolon** [comment]
Great idea!

**Comment by aedelmann** [comment]
done
