### ISSUE TITLE
Install Vorto for Contributors throws error in pom.xml, so that bundles cannot be built correctly

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#910]
Confirmation:
- Improve installation guide for Vorto for Contributors

Details:
I tried to install the m2e connectors (suggested by the eclipse IDE when hovering over the parent tag in pom.xml files with error) namely the below 3.
1.	Buildhelper
2.	Groovy-Eclipse
3.	Tycho Configurator

When I tried to proceed with the installation I was met with the following error.

An error occurred while collecting items to be installed
session context was:(profile=epp.package.dsl, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.eclipse.m2e.archetype.common,1.7.0.20160603-1931
No repository found containing: osgi.bundle,org.eclipse.m2e.core,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.core.ui,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.discovery,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.editor,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.editor.xml,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.jdt,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.jdt.ui,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.launching,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.lifecyclemapping.defaults,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.maven.indexer,1.7.0.20160603-1931
No repository found containing: osgi.bundle,org.eclipse.m2e.maven.runtime,1.7.0.20160603-1931
No repository found containing: osgi.bundle,org.eclipse.m2e.maven.runtime.slf4j.simple,1.7.0.20160603-1931
No repository found containing: osgi.bundle,org.eclipse.m2e.model.edit,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.profiles.core,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.profiles.ui,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.refactoring,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.scm,1.7.0.20160603-1933
No repository found containing: org.eclipse.update.feature,org.eclipse.m2e.feature,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.importer,1.7.0.20160603-1933

Resolution: Added the following repository to the “Available Software Sites” in eclipse,
http://download.eclipse.org/technology/m2e/releases/1.7/1.7.0.20160603-1933

Please note that the corresponding entry for 1.5 was already available in the IDE.

**Comment by Scriptkiddi** [comment]
this is stale
