### ISSUE TITLE
Entity names can be unified in the tooling

### ISSUE THREAD

**Issue by e-grigorov** [eclipse/vorto#914]
Currently, we have different options for the same entity. I would suggest to unify them to improve UX. Examples:

* Data Type
  * "Datatypes" in Vorto Model Project Browser
  * "Datatype" in Preferences -> Vorto
  * "Data Types" in the [doc](http://www.eclipse.org/vorto/documentation/editors/datatype.html)

It seems that two words have to be used here i.e. Data Type

* Function Block
  * "Functionblocks" in Vorto Model Project Browser
  * "Functionblock" in Preferences -> Vorto
  * "Function Blocks" in the [doc](http://www.eclipse.org/vorto/documentation/editors/functionblock.html)
  * "New Functionblock" in the context menu
  * "Create Function Block Model" in the new wizard

It seems that two words have to be used here i.e. Function Block

* Information Model
  * "InformationModel" - in Preferences -> Vorto

It should be: Information Model

**Comment by aedelmann** [comment]
I don't quite understand it fully yet. What is your suggestion for improvement here ?

**Comment by Ebolon** [comment]
To standardise the wording for the different model types. Sometimes the words are written as two words sometimes not.

I suggest to use these everywhere:
- Datatype(s)
- Functionblock(s)
- Information Model

**Comment by e-grigorov** [comment]
> I suggest to use these everywhere:
> * Datatype(s)

I would suggest to use two words here: Data Type
https://en.wikipedia.org/wiki/Data_type
What is your point for a single word?

> * Functionblock(s)

The same argument i.e. Function Block

**Comment by Ebolon** [comment]
> What is your point for a single word?

For me it is more a gut feeling because the words are often written together in the source code and have there "own" meaning in the context of Vorto. From the grammar perspective you have a point there.

**Comment by e-grigorov** [comment]
I got your point here. You are right, DSL file contains
* functionblock - which maps to: Functionblock(s)
* infomodel - to keep it unified, we have to use: Informationmodel or Infomodel

I still like the "two words" idea because we have UI i.e. it should be human-readable.

**Comment by aedelmann** [comment]
Closing issue as Vorto Tooling is no longer supported.
