### ISSUE TITLE
Introduce a CHANGELOG.md

### ISSUE THREAD

**Issue by Ebolon** [eclipse/vorto#922]
As I understood Vorto now tries to archive an one month release cycle. This would help to get a quickly overview about the activity of the project.

A changelog should contain the following sections:

- features
- improvements
- bug fixes
- backwards incompatibilities / notes

Like used in the [terraform changelog](https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md)

Other resources: https://keepachangelog.com/

**Comment by aedelmann** [comment]
FYI : @Scriptkiddi
