### ISSUE TITLE
Generator Test Framework

### ISSUE THREAD

**Issue by Ebolon** [eclipse/vorto#923]
The Vorto Generator Test Framework supports the developer to implement a code generator in a test-driven way. Thus he creates a ZIP archive containing the expected generated files for a given information model and feeds it to the Generator FW , which is based on JUnit. The framework executes the generator and compares the actual ZIP archive from the generator against the expected. 
This allows the easy definition of test cases for code generators whereby the code generators can run as part of the automated build and test pipeline.

Confirmations:
- JUnit based Test framework that accepts an expected ZIP archive and a corrosponding information model. The framework internally executes the generator and produces the actual generated ZIP Archive. The test case fails if the actual and expected archives do not match.

**Comment by aedelmann** [comment]
Hi @Ebolon 
Yeah, we are currently very bad on making sure if the generators all work as expected. That is why, we are working internally on a Code Generator framework which allows us to easily run integration tests for our code generator infrastructure.

**Comment by aedelmann** [comment]
Fixed.
