### ISSUE TITLE
CLI tool for MAC / Linux could not be executed

### ISSUE THREAD

**Issue by deepagithub** [eclipse/vorto#937]
**Steps:**
From http://www.eclipse.org/vorto/downloads/index.html, choose CLI for MAC / Linux
**Expected Result**
The downloaded files should be executable
**Actual Result**
The files appear without any extension and could not be executed.

**Comment by melvinlee** [comment]
## Steps:
- From http://www.eclipse.org/vorto/downloads/index.html, choose CLI for MAC / Linux
- Update the access permissions
```sh
$ chmod 755 vorto
```
- Execute 
```sh
$ ./vorto
```

## Expected Result:
The downloaded files should run

## Actual Result:
The files appear executed with error throw.

```sh
$ ./vorto
zsh: exec format error: ./vorto
```
