### ISSUE TITLE
Invalid model in repository - examples.datatypes.state.Presence:1.0.0

### ISSUE THREAD

**Issue by Ebolon** [eclipse/vorto#946]
The REST API returns with HTTP error code 500 when I try to `downloadModelById` the model 
[examples.datatypes.state.Presence:1.0.0](http://vorto.eclipse.org/#/details/examples.datatypes.state/Presence/1.0.0). The simples solution would be to delete this model. (seems to have an outdated syntax)

**Comment by aedelmann** [comment]
I deleted this example model.
