### ISSUE TITLE
Allow currently reserved keywords as property/operation name

### ISSUE THREAD

**Issue by Ebolon** [eclipse/vorto#963]
These are currently all available reserved keywords in Xtext:
`'DEFAULT', 'MAX', 'MIMETYPE', 'MIN', 'NULLABLE', 'REGEX', 'SCALING', 'STRLEN', 'T', 'Z', 'as', 'boolean', 'breakable', 'byte', 'category', 'configuration', 'dateTime', 'description', 'dictionary', 'displayname', 'double', 'entity', 'enum', 'eventable', 'events', 'extends', 'extension', 'false', 'fault', 'float', 'functionblock', 'functionblocks', 'infomodel', 'int', 'long', 'mandatory', 'measurementUnit', 'multiple', 'namespace', 'operations', 'optional', 'readable', 'returns', 'short', 'status', 'string', 'true', 'using', 'version', 'with', 'writable'`

I see no problem to allow all, but variable names like `false` or `int` seems strange. Whats your opinion?

**Comment by aedelmann** [comment]
Hi @Ebolon 
I would suggest to allow the following keywords for now : 
breakable, category, configuration, dateTime, description, dictionary, displayname, extension, fault, functionblock, functionblocks, infomodel, namespace, operations, status, version

**Comment by aedelmann** [comment]
I came across his problem, therefore opening this issue again:
Using of 'as' in the property name, like 'gas' results in error :  _The following property (properties) [as] has not been imported (not in the "using" statement)_
Instead it should allow this to be specified and not result in an error. It possibly conflicts misakingly with the 'as' keyword, similarly with 'namespace'.
