### ISSUE TITLE
Operation name cannot be same as custom type (Enum / Entity) name

### ISSUE THREAD

**Issue by e-grigorov** [eclipse/vorto#965]
I got this error message with this model:
```
using com.mycompany.type.Record ; 1.0.0

functionblock Recorder {
	operations {
		mandatory record() returns Record
	}
}
```
It's somehow strange limitation. What is the reason to have this restriction?

**Comment by Ebolon** [comment]
I think you mean this error: "Operation name cannot be same as custom type (Enum / Entity) name". Yes this is strange. Would suggest to remove  the validation check `checkOpNameAgainstEntityName`. @aedelmann ?
