### ISSUE TITLE
Making Vorto generators configurable at runtime

### ISSUE THREAD

**Issue by nagavijays** [eclipse/vorto#98]
Migrated from https://bugs.eclipse.org/bugs/show_bug.cgi?id=488964

**Comment by laverman** [comment]
+1

**Comment by aedelmann** [comment]
Confirmations:
- Configuration parameters can be sent along when invoking a code generator via REST API 
- Swagger REST API Documentation, explaining the usage of these parameters
- InvocationContext in Generator API exposes configuration parameters that can be processed in the code generator implementation
