### ISSUE TITLE
Generatos not working

### ISSUE THREAD

**Issue by davidakr** [eclipse/vorto#998]
When a generator is invoked on a model it should download the generated code. Instead a Whitelabel Error Page is shown right now.

**Comment by andritoggenburger** [comment]
Same issue seems to be present again:

Whitelabel Er_ror Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Sep 04 11:12:23 UTC 2018
There was an unexpected error (type=Internal Server Error, status=500).
400 null_
